import type { ModelLesson } from '@/lib/model-lessons';

export const additionalLessons: Record<string, ModelLesson> = {
  'en-a1-01': {
    language: 'en',
    title: 'Primer contacto',
    level: 'A1.1',
    duration: '10–12 min',
    objective:
      'Puedo saludar, despedirme y usar expresiones básicas de cortesía.',
    introduction: {
      summary:
        'Aprende fórmulas breves para iniciar y cerrar un encuentro de manera amable.',
      concepts: [
        {
          title: 'Saludar',
          explanation:
            'Hello y Hi sirven para saludar. Hi es un poco más informal.',
          examples: ['Hello!', 'Hi, Diana!'],
        },
        {
          title: 'Presentarte',
          explanation: 'Usa I’m o My name is seguido de tu nombre.',
          examples: ["I'm Santiago.", 'My name is Diana.'],
        },
        {
          title: 'Cortesía y despedida',
          explanation:
            'Please acompaña peticiones; thank you agradece; goodbye y see you cierran el encuentro.',
          examples: ['Yes, please.', 'Thank you.', 'See you!'],
        },
      ],
      tip: 'En una conversación breve basta con saludar, decir tu nombre y responder con una fórmula amable.',
    },
    exercises: [
      {
        id: 'en-a1-01-01',
        kind: 'choice',
        phase: 'activar',
        prompt: 'Alguien dice “Hello!”. ¿Qué respuesta es natural?',
        hint: 'Responde con otro saludo.',
        options: ['Hello!', 'Goodbye!', 'Thank you!'],
        answer: 'Hello!',
        explanation:
          'Hello puede usarse tanto para iniciar como para responder a un saludo.',
      },
      {
        id: 'en-a1-01-02',
        kind: 'choice',
        phase: 'comprender',
        prompt: '¿Qué significa “Nice to meet you”?',
        hint: 'Se usa al conocer a alguien.',
        options: ['Mucho gusto.', 'Hasta mañana.', 'Perdón.'],
        answer: 'Mucho gusto.',
        explanation:
          'Nice to meet you expresa cortesía al conocer a una persona.',
      },
      {
        id: 'en-a1-01-03',
        kind: 'choice',
        phase: 'comprender',
        prompt: 'Te ofrecen agua. ¿Qué respuesta acepta cortésmente?',
        hint: 'Incluye la palabra de cortesía.',
        options: ['Yes, please.', 'No hello.', 'Goodbye water.'],
        answer: 'Yes, please.',
        explanation: 'Yes, please acepta el ofrecimiento de forma cortés.',
      },
      {
        id: 'en-a1-01-04',
        kind: 'order',
        phase: 'practicar',
        prompt: 'Ordena la presentación.',
        hint: 'Forma “Me llamo Diana”.',
        tokens: ['is', 'Diana', 'My', 'name'],
        answer: ['My', 'name', 'is', 'Diana'],
        explanation: 'La estructura es My name is + nombre.',
      },
      {
        id: 'en-a1-01-05',
        kind: 'choice',
        phase: 'practicar',
        prompt: '¿Qué dices al terminar una conversación?',
        hint: 'Elige una despedida.',
        options: ['See you!', 'Please?', 'My name.'],
        answer: 'See you!',
        explanation: 'See you es una despedida común e informal.',
      },
      {
        id: 'en-a1-01-06',
        kind: 'order',
        phase: 'practicar',
        prompt: 'Ordena la respuesta cortés.',
        hint: 'Responde a “Nice to meet you”.',
        tokens: ['too', 'you', 'meet', 'to', 'Nice'],
        answer: ['Nice', 'to', 'meet', 'you', 'too'],
        explanation: 'Nice to meet you too devuelve la fórmula de cortesía.',
      },
      {
        id: 'en-a1-01-07',
        kind: 'open',
        phase: 'transferir',
        prompt: 'Escribe: “Hola, me llamo Santiago”.',
        hint: 'Usa Hello y My name is.',
        accepted: [
          'Hello, my name is Santiago.',
          'Hello! My name is Santiago.',
          'Hi, my name is Santiago.',
          'Hi! My name is Santiago.',
          "Hello, I'm Santiago.",
          "Hello! I'm Santiago.",
          "Hi, I'm Santiago.",
          "Hi! I'm Santiago.",
        ],
        modelAnswer: 'Hello! My name is Santiago.',
        explanation: 'Hello/Hi + My name is permite saludar y presentarte.',
      },
      {
        id: 'en-a1-01-08',
        kind: 'open',
        phase: 'transferir',
        prompt: 'Saluda, di tu nombre y despídete en inglés.',
        hint: 'Puedes usar Hello, I’m… y See you.',
        accepted: [],
        modelAnswer: "Hello! I'm Diana. Nice to meet you. See you!",
        explanation:
          'La producción debe incluir saludo, nombre y una despedida apropiada.',
      },
    ],
  },
  'en-a1-02': {
    language: 'en',
    title: 'Mi identidad',
    level: 'A1.1',
    duration: '10–12 min',
    objective:
      'Puedo decir mi nombre, país, idioma y datos personales básicos.',
    introduction: {
      summary:
        'Practica las preguntas y respuestas esenciales para intercambiar información personal sin compartir datos sensibles.',
      concepts: [
        {
          title: 'Nombre',
          explanation:
            'Pregunta What’s your name? y responde My name is… o I’m…',
          examples: ["What's your name?", "I'm Diana."],
        },
        {
          title: 'Origen',
          explanation:
            'Where are you from? pregunta por el país o lugar de origen.',
          examples: ['Where are you from?', 'I’m from Mexico.'],
        },
        {
          title: 'Idiomas',
          explanation:
            'Usa I speak + idioma. Los idiomas se escriben con mayúscula en inglés.',
          examples: ['I speak Spanish.', 'I speak English and Spanish.'],
        },
      ],
      tip: 'Para practicar usa información ficticia si no quieres compartir datos personales reales.',
    },
    exercises: [
      {
        id: 'en-a1-02-01',
        kind: 'choice',
        phase: 'activar',
        prompt: '¿Qué pregunta pide el nombre?',
        hint: 'Busca name.',
        options: ["What's your name?", 'Where are you from?', 'How are you?'],
        answer: "What's your name?",
        explanation: "What's your name? significa “¿Cómo te llamas?”.",
      },
      {
        id: 'en-a1-02-02',
        kind: 'choice',
        phase: 'comprender',
        prompt: 'Completa: I ___ from Mexico.',
        hint: 'Usa el verbo be con I.',
        options: ['am', 'is', 'are'],
        answer: 'am',
        explanation: 'La forma del verbo be con I es am.',
      },
      {
        id: 'en-a1-02-03',
        kind: 'choice',
        phase: 'comprender',
        prompt: '¿Qué pregunta corresponde a “Soy de Colombia”?',
        hint: 'Pregunta por el origen.',
        options: ['Where are you from?', 'What do you speak?', 'What is this?'],
        answer: 'Where are you from?',
        explanation: 'Where are you from? pregunta de dónde es alguien.',
      },
      {
        id: 'en-a1-02-04',
        kind: 'order',
        phase: 'practicar',
        prompt: 'Ordena la frase.',
        hint: 'Forma “Hablo español”.',
        tokens: ['Spanish', 'speak', 'I'],
        answer: ['I', 'speak', 'Spanish'],
        explanation: 'El orden es sujeto + verbo + idioma.',
      },
      {
        id: 'en-a1-02-05',
        kind: 'choice',
        phase: 'practicar',
        prompt: 'Selecciona la escritura correcta.',
        hint: 'Los idiomas llevan mayúscula.',
        options: ['I speak English.', 'I speak english.', 'I English speak.'],
        answer: 'I speak English.',
        explanation: 'English se escribe con mayúscula y sigue al verbo speak.',
      },
      {
        id: 'en-a1-02-06',
        kind: 'order',
        phase: 'practicar',
        prompt: 'Ordena la respuesta sobre origen.',
        hint: 'Forma “Soy de México”.',
        tokens: ['Mexico', 'from', "I'm"],
        answer: ["I'm", 'from', 'Mexico'],
        explanation: "I'm from + lugar expresa origen.",
      },
      {
        id: 'en-a1-02-07',
        kind: 'open',
        phase: 'transferir',
        prompt: 'Escribe: “Me llamo Diana y soy de México”.',
        hint: 'Usa My name is e I’m from.',
        accepted: [
          "My name is Diana and I'm from Mexico.",
          'My name is Diana. I am from Mexico.',
          "I'm Diana and I'm from Mexico.",
        ],
        modelAnswer: "My name is Diana and I'm from Mexico.",
        explanation: 'Se aceptan dos frases o una oración unida con and.',
      },
      {
        id: 'en-a1-02-08',
        kind: 'open',
        phase: 'transferir',
        prompt: 'Escribe una presentación con nombre, país e idioma.',
        hint: 'Puedes usar datos ficticios.',
        accepted: [],
        modelAnswer: "I'm Alex. I'm from Canada. I speak English and French.",
        explanation:
          'La presentación debe contener nombre, origen y al menos un idioma.',
      },
    ],
  },
  'ja-02': {
    language: 'ja',
    title: 'Hiragana II',
    level: 'Pre-A1',
    duration: '12–14 min',
    objective:
      'Puedo reconocer series básicas, dakuten y sonidos contraídos para leer palabras breves.',
    introduction: {
      summary:
        'Amplía las cinco vocales combinándolas con consonantes y reconoce dos transformaciones frecuentes.',
      concepts: [
        {
          title: 'Series básicas',
          explanation:
            'Cada fila combina una consonante con a, i, u, e, o. Algunas lecturas cambian ligeramente.',
          examples: [
            'か き く け こ = ka ki ku ke ko',
            'さ し す せ そ = sa shi su se so',
            'た・な・は・ま・や・ら・わ の各行と ん',
          ],
        },
        {
          title: 'Dakuten',
          explanation:
            'Las dos marcas ゛vuelven sonora una consonante: k pasa a g y s pasa a z/j.',
          examples: ['か → が (ka → ga)', 'し → じ (shi → ji)'],
        },
        {
          title: 'Sonidos contraídos',
          explanation:
            'Una や, ゆ o よ pequeña se combina con kana terminados en i.',
          examples: ['き + ゃ → きゃ (kya)', 'し + ゅ → しゅ (shu)'],
        },
      ],
      tip: 'Distingue el tamaño: や es una mora independiente; ゃ pequeña se combina con el kana anterior.',
    },
    exercises: [
      {
        id: 'ja-02-01',
        kind: 'choice',
        phase: 'activar',
        prompt: '¿Cómo se lee か?',
        hint: 'Primera sílaba de la fila k.',
        options: ['ka', 'ki', 'ga'],
        answer: 'ka',
        explanation: 'か representa ka.',
      },
      {
        id: 'ja-02-02',
        kind: 'choice',
        phase: 'comprender',
        prompt: '¿Qué carácter representa la mora final “n”?',
        hint: 'Es el único kana básico que no termina en vocal.',
        options: ['ん', 'な', 'め'],
        answer: 'ん',
        explanation:
          'ん representa una mora nasal y cierra la secuencia básica.',
      },
      {
        id: 'ja-02-03',
        kind: 'choice',
        phase: 'comprender',
        prompt: '¿Qué ocurre al añadir dakuten a か?',
        hint: 'k se vuelve sonora.',
        options: ['が (ga)', 'ぱ (pa)', 'さ (sa)'],
        answer: 'が (ga)',
        explanation: 'か con dakuten se convierte en が y se lee ga.',
      },
      {
        id: 'ja-02-04',
        kind: 'choice',
        phase: 'practicar',
        prompt: '¿Cuál representa kya?',
        hint: 'La ゃ debe ser pequeña.',
        options: ['きゃ', 'きや', 'ぎゃ'],
        answer: 'きゃ',
        explanation:
          'き + ゃ pequeña forma きゃ (kya); きや mantiene dos moras.',
      },
      {
        id: 'ja-02-05',
        kind: 'order',
        phase: 'practicar',
        prompt: 'Ordena la fila s.',
        hint: 'Sigue las vocales a, i, u, e, o.',
        tokens: ['そ', 'し', 'せ', 'さ', 'す'],
        answer: ['さ', 'し', 'す', 'せ', 'そ'],
        explanation: 'La fila es さ・し・す・せ・そ.',
      },
      {
        id: 'ja-02-06',
        kind: 'choice',
        phase: 'practicar',
        prompt: '¿Qué palabra se lee “hana”?',
        hint: 'Combina ha + na, de dos filas distintas.',
        options: ['はな', 'なは', 'はま'],
        answer: 'はな',
        explanation: 'は = ha y な = na; juntos forman はな.',
      },
      {
        id: 'ja-02-07',
        kind: 'open',
        phase: 'transferir',
        prompt: 'Escribe en hiragana “neko”.',
        hint: 'ne = ね, ko = こ.',
        accepted: ['ねこ'],
        modelAnswer: 'ねこ',
        explanation: 'ねこ se segmenta ね (ne) + こ (ko).',
      },
      {
        id: 'ja-02-08',
        kind: 'open',
        phase: 'transferir',
        prompt: 'Escribe el hiragana contraído para “kya”.',
        hint: 'Usa き y una ゃ pequeña.',
        accepted: ['きゃ'],
        modelAnswer: 'きゃ',
        explanation: 'きゃ es una sola combinación contraída.',
      },
    ],
  },
  'ja-03': {
    language: 'ja',
    title: 'Katakana esencial',
    level: 'Pre-A1',
    duration: '12–14 min',
    objective:
      'Puedo reconocer katakana frecuente en nombres y préstamos y escribir palabras breves.',
    introduction: {
      summary:
        'El katakana representa las mismas moras que el hiragana, pero se usa con frecuencia para préstamos y nombres extranjeros.',
      concepts: [
        {
          title: 'Mismos sonidos, otras formas',
          explanation: 'Las vocales mantienen el mismo sonido.',
          examples: ['ア = a', 'イ = i', 'ウ = u', 'エ = e', 'オ = o'],
        },
        {
          title: 'Préstamos',
          explanation:
            'Muchas palabras extranjeras se adaptan a las moras japonesas.',
          examples: [
            'テレビ = terebi (televisión)',
            'カメラ = kamera (cámara)',
          ],
        },
        {
          title: 'Vocal larga',
          explanation: 'La raya ー prolonga la vocal anterior en katakana.',
          examples: ['コーヒー = kōhī (café)', 'ケーキ = kēki (pastel)'],
        },
      ],
      tip: 'No leas el katakana como letras latinas: identifica cada bloque como una mora japonesa.',
    },
    exercises: [
      {
        id: 'ja-03-01',
        kind: 'choice',
        phase: 'activar',
        prompt: '¿Qué sonido representa ア?',
        hint: 'Es la primera vocal.',
        options: ['a', 'i', 'o'],
        answer: 'a',
        explanation: 'ア representa a en katakana.',
      },
      {
        id: 'ja-03-02',
        kind: 'choice',
        phase: 'comprender',
        prompt: '¿Cuál es el katakana de “ka”?',
        hint: 'No elijas el hiragana か.',
        options: ['カ', 'か', 'ガ'],
        answer: 'カ',
        explanation: 'カ es ka; か es la forma en hiragana y ガ es ga.',
      },
      {
        id: 'ja-03-03',
        kind: 'choice',
        phase: 'comprender',
        prompt: '¿Qué función tiene ー en コーヒー?',
        hint: 'Modifica la vocal anterior.',
        options: [
          'Alarga la vocal.',
          'Duplica la consonante.',
          'Separa palabras.',
        ],
        answer: 'Alarga la vocal.',
        explanation: 'El signo ー marca una vocal larga en katakana.',
      },
      {
        id: 'ja-03-04',
        kind: 'choice',
        phase: 'practicar',
        prompt: '¿Qué palabra se lee “terebi”?',
        hint: 'Es un préstamo para televisión.',
        options: ['テレビ', 'カメラ', 'ラジオ'],
        answer: 'テレビ',
        explanation: 'テ・レ・ビ corresponde a te-re-bi.',
      },
      {
        id: 'ja-03-05',
        kind: 'order',
        phase: 'practicar',
        prompt: 'Ordena los caracteres para formar カメラ.',
        hint: 'Forma kamera.',
        tokens: ['ラ', 'カ', 'メ'],
        answer: ['カ', 'メ', 'ラ'],
        explanation: 'カ (ka) + メ (me) + ラ (ra) forma カメラ.',
      },
      {
        id: 'ja-03-06',
        kind: 'choice',
        phase: 'practicar',
        prompt: 'Selecciona “café” en katakana.',
        hint: 'Contiene dos vocales largas.',
        options: ['コーヒー', 'コヒ', 'ケーキ'],
        answer: 'コーヒー',
        explanation:
          'コーヒー es la adaptación japonesa de coffee y usa ー dos veces.',
      },
      {
        id: 'ja-03-07',
        kind: 'open',
        phase: 'transferir',
        prompt: 'Escribe “kamera” en katakana.',
        hint: 'ka = カ, me = メ, ra = ラ.',
        accepted: ['カメラ'],
        modelAnswer: 'カメラ',
        explanation: 'カメラ es la forma katakana de kamera.',
      },
      {
        id: 'ja-03-08',
        kind: 'open',
        phase: 'transferir',
        prompt: 'Escribe “Mexico” como メキシコ.',
        hint: 'Usa me-ki-shi-ko.',
        accepted: ['メキシコ'],
        modelAnswer: 'メキシコ',
        explanation: 'メ・キ・シ・コ forma メキシコ.',
      },
    ],
  },
  'en-a1-03': {
    language: 'en',
    title: 'Números y objetos',
    level: 'A1.1',
    duration: '10–12 min',
    objective: 'Puedo reconocer cantidades, precios y objetos cotidianos.',
    introduction: {
      summary:
        'Aprende a contar objetos, reconocer precios y señalar cosas cercanas o lejanas.',
      concepts: [
        {
          title: 'Números y precios',
          explanation:
            'Las decenas terminan en -ty; los números como 21 combinan decena y unidad.',
          examples: ['20 = twenty', '21 = twenty-one', '£15 = fifteen pounds'],
        },
        {
          title: 'A o an',
          explanation:
            'Usa a antes de sonido consonante y an antes de sonido vocálico.',
          examples: ['a book', 'an orange', 'an umbrella'],
        },
        {
          title: 'This o that',
          explanation:
            'This señala algo singular cercano; that señala algo singular más lejano.',
          examples: ['This is a phone.', 'That is a bag.'],
        },
      ],
      tip: 'Para a/an importa el sonido inicial, no solamente la primera letra.',
    },
    exercises: [
      {
        id: 'en-a1-03-01',
        kind: 'choice',
        phase: 'activar',
        prompt: '¿Qué número es “thirty”?',
        hint: 'Es una decena.',
        options: ['13', '30', '3'],
        answer: '30',
        explanation: 'Thirty es 30; thirteen es 13.',
      },
      {
        id: 'en-a1-03-02',
        kind: 'choice',
        phase: 'comprender',
        prompt: 'Elige el artículo correcto: ___ apple.',
        hint: 'Apple comienza con sonido vocálico.',
        options: ['an', 'a', 'this'],
        answer: 'an',
        explanation: 'Usamos an antes del sonido vocálico de apple.',
      },
      {
        id: 'en-a1-03-03',
        kind: 'choice',
        phase: 'comprender',
        prompt: 'Tienes un libro en la mano. ¿Qué dices?',
        hint: 'El objeto está cerca.',
        options: ['This is a book.', 'That are a book.', 'These is book.'],
        answer: 'This is a book.',
        explanation: 'This + is señala un objeto singular cercano.',
      },
      {
        id: 'en-a1-03-04',
        kind: 'order',
        phase: 'practicar',
        prompt: 'Ordena la pregunta sobre precio.',
        hint: 'Forma “¿Cuánto cuesta esto?”.',
        tokens: ['this', 'much', 'is', 'How'],
        answer: ['How', 'much', 'is', 'this'],
        explanation: 'How much is this? pregunta el precio de algo cercano.',
      },
      {
        id: 'en-a1-03-05',
        kind: 'choice',
        phase: 'practicar',
        prompt: '¿Cómo se escribe 42?',
        hint: 'Combina forty y two.',
        options: ['forty-two', 'fourty-two', 'fourteen-two'],
        answer: 'forty-two',
        explanation: '40 se escribe forty, sin u; 42 es forty-two.',
      },
      {
        id: 'en-a1-03-06',
        kind: 'choice',
        phase: 'practicar',
        prompt:
          'El objeto está al otro lado del cuarto. Completa: ___ is my bag.',
        hint: 'Está lejos.',
        options: ['That', 'This', 'An'],
        answer: 'That',
        explanation: 'That señala un objeto singular alejado.',
      },
      {
        id: 'en-a1-03-07',
        kind: 'open',
        phase: 'transferir',
        prompt: 'Escribe en inglés: “Esto es un paraguas”.',
        hint: 'Usa this y an.',
        accepted: ['This is an umbrella.', 'This is an umbrella'],
        modelAnswer: 'This is an umbrella.',
        explanation: 'This is señala el objeto cercano y umbrella requiere an.',
      },
      {
        id: 'en-a1-03-08',
        kind: 'open',
        phase: 'transferir',
        prompt: 'Escribe el precio £25 con palabras en una oración.',
        hint: 'Usa It is… pounds.',
        accepted: [
          'It is twenty-five pounds.',
          'It’s twenty-five pounds.',
          'It is twenty-five pounds',
        ],
        modelAnswer: 'It is twenty-five pounds.',
        explanation: '25 se escribe twenty-five.',
      },
    ],
  },
  'en-a1-04': {
    language: 'en',
    title: 'Familia y personas',
    level: 'A1.1',
    duration: '10–12 min',
    objective:
      'Puedo presentar a mi familia y describir a una persona con frases breves.',
    introduction: {
      summary:
        'Presenta relaciones familiares y describe rasgos sencillos con have got, posesivos y adjetivos.',
      concepts: [
        {
          title: 'Familia',
          explanation:
            'Usa my para indicar relación contigo y ’s para relacionar a otra persona.',
          examples: ['This is my sister.', "Diana is Alex's mother."],
        },
        {
          title: 'Have got',
          explanation: 'I/you/we/they usan have got; he/she/it usan has got.',
          examples: ["I've got two brothers.", 'She has got brown eyes.'],
        },
        {
          title: 'Descripción',
          explanation:
            'Los adjetivos de apariencia pueden acompañar hair, eyes o una descripción con be.',
          examples: ['He is tall.', 'She has got long, black hair.'],
        },
      ],
      tip: 'Elige have o has según el sujeto, no según el objeto descrito.',
    },
    exercises: [
      {
        id: 'en-a1-04-01',
        kind: 'choice',
        phase: 'activar',
        prompt: '¿Qué significa “sister”?',
        hint: 'Es un miembro de la familia.',
        options: ['hermana', 'madre', 'prima'],
        answer: 'hermana',
        explanation: 'Sister significa hermana.',
      },
      {
        id: 'en-a1-04-02',
        kind: 'choice',
        phase: 'comprender',
        prompt: 'Completa: She ___ got blue eyes.',
        hint: 'Con she usamos has.',
        options: ['has', 'have', 'is'],
        answer: 'has',
        explanation: 'She has got describe una característica o posesión.',
      },
      {
        id: 'en-a1-04-03',
        kind: 'choice',
        phase: 'comprender',
        prompt: '¿Qué significa “Diana’s brother”?',
        hint: 'Observa el posesivo ’s.',
        options: [
          'el hermano de Diana',
          'la hermana Diana',
          'Diana y su madre',
        ],
        answer: 'el hermano de Diana',
        explanation: 'El posesivo ’s relaciona brother con Diana.',
      },
      {
        id: 'en-a1-04-04',
        kind: 'order',
        phase: 'practicar',
        prompt: 'Ordena la presentación.',
        hint: 'Forma “Este es mi padre”.',
        tokens: ['father', 'is', 'my', 'This'],
        answer: ['This', 'is', 'my', 'father'],
        explanation: 'This is my + familiar sirve para presentarlo.',
      },
      {
        id: 'en-a1-04-05',
        kind: 'choice',
        phase: 'practicar',
        prompt: 'Selecciona la descripción correcta.',
        hint: 'Hair se describe con has got.',
        options: [
          'He has got short hair.',
          'He have short hair.',
          'He is got short hair.',
        ],
        answer: 'He has got short hair.',
        explanation: 'Con he usamos has got.',
      },
      {
        id: 'en-a1-04-06',
        kind: 'choice',
        phase: 'practicar',
        prompt: 'Sam is my mother’s son. Sam is my…',
        hint: 'Comparte madre contigo.',
        options: ['brother', 'uncle', 'father'],
        answer: 'brother',
        explanation: 'El hijo de tu madre puede ser tu hermano.',
      },
      {
        id: 'en-a1-04-07',
        kind: 'open',
        phase: 'transferir',
        prompt: 'Escribe: “Esta es mi hermana. Tiene el cabello largo”.',
        hint: 'Usa This is y has got.',
        accepted: [
          'This is my sister. She has got long hair.',
          'This is my sister; she has got long hair.',
          'This is my sister. She has long hair.',
          'This is my sister; she has long hair.',
          "This is my sister. She's got long hair.",
          "This is my sister; she's got long hair.",
        ],
        modelAnswer: 'This is my sister. She has got long hair.',
        explanation: 'She has got concuerda con sister.',
      },
      {
        id: 'en-a1-04-08',
        kind: 'open',
        phase: 'transferir',
        prompt: 'Presenta y describe brevemente a un familiar ficticio.',
        hint: 'Incluye relación y un rasgo.',
        accepted: [],
        modelAnswer:
          'This is my brother Leo. He is tall and he has got brown eyes.',
        explanation:
          'La respuesta debe incluir una relación familiar y al menos una descripción clara.',
      },
    ],
  },
  'ja-04': {
    language: 'ja',
    title: 'Saludos y reparación',
    level: 'A1.1',
    duration: '10–12 min',
    objective: 'Puedo saludar, despedirme, agradecer y pedir que repitan.',
    introduction: {
      summary:
        'Aprende fórmulas fijas para iniciar una interacción y resolver el problema más común del principiante: no haber entendido.',
      concepts: [
        {
          title: 'Saludos',
          explanation: 'El saludo cambia según el momento y la situación.',
          examples: [
            'おはようございます = buenos días',
            'こんにちは = hola/buenas tardes',
            'こんばんは = buenas noches',
          ],
        },
        {
          title: 'Agradecer y disculparte',
          explanation:
            'Estas fórmulas cortas mantienen una interacción cortés.',
          examples: [
            'ありがとうございます = muchas gracias',
            'すみません = disculpe/perdón',
          ],
        },
        {
          title: 'Pedir repetición',
          explanation: 'Si no entiendes, puedes pedir que lo digan otra vez.',
          examples: [
            'もういちど おねがいします = otra vez, por favor',
            'よく わかりません = no entiendo bien',
          ],
        },
      ],
      tip: 'Aprende estas expresiones como bloques completos; podrás analizarlas gramaticalmente más adelante.',
    },
    exercises: [
      {
        id: 'ja-04-01',
        kind: 'choice',
        phase: 'activar',
        prompt: '¿Qué saludo significa “buenos días”?',
        hint: 'Es la fórmula cortés de la mañana.',
        options: ['おはようございます', 'こんにちは', 'こんばんは'],
        answer: 'おはようございます',
        explanation: 'おはようございます se usa como saludo matutino cortés.',
      },
      {
        id: 'ja-04-02',
        kind: 'choice',
        phase: 'comprender',
        prompt: '¿Qué dices para agradecer cortésmente?',
        hint: 'Busca “muchas gracias”.',
        options: ['ありがとうございます', 'すみません', 'さようなら'],
        answer: 'ありがとうございます',
        explanation:
          'ありがとうございます es una fórmula cortés de agradecimiento.',
      },
      {
        id: 'ja-04-03',
        kind: 'choice',
        phase: 'comprender',
        prompt: 'No entendiste. ¿Qué expresión pide repetir?',
        hint: 'もういちど significa “otra vez”.',
        options: ['もういちど おねがいします', 'こんばんは', 'はじめまして'],
        answer: 'もういちど おねがいします',
        explanation: 'La expresión completa pide que se repita algo.',
      },
      {
        id: 'ja-04-04',
        kind: 'order',
        phase: 'practicar',
        prompt: 'Ordena “Otra vez, por favor”.',
        hint: 'Primero “otra vez”, después “por favor”.',
        tokens: ['おねがいします', 'もういちど'],
        answer: ['もういちど', 'おねがいします'],
        explanation: 'El orden es もういちど おねがいします.',
      },
      {
        id: 'ja-04-05',
        kind: 'choice',
        phase: 'practicar',
        prompt: 'Llegas por la tarde. ¿Qué saludo eliges?',
        hint: 'No es todavía de noche.',
        options: ['こんにちは', 'おはようございます', 'おやすみなさい'],
        answer: 'こんにちは',
        explanation: 'こんにちは es el saludo general del día o la tarde.',
      },
      {
        id: 'ja-04-06',
        kind: 'choice',
        phase: 'practicar',
        prompt: '¿Qué expresión comunica “No entiendo bien”?',
        hint: 'わかりません expresa falta de comprensión.',
        options: [
          'よく わかりません',
          'よく できました',
          'ありがとうございます',
        ],
        answer: 'よく わかりません',
        explanation: 'よく わかりません comunica que no se ha entendido bien.',
      },
      {
        id: 'ja-04-07',
        kind: 'open',
        phase: 'transferir',
        prompt: 'Escribe en japonés: “Muchas gracias”.',
        hint: 'Usa la fórmula cortés completa.',
        accepted: ['ありがとうございます'],
        modelAnswer: 'ありがとうございます',
        explanation:
          'ありがとうございます es la forma trabajada en esta unidad.',
      },
      {
        id: 'ja-04-08',
        kind: 'open',
        phase: 'transferir',
        prompt: 'Escribe la frase para pedir que repitan.',
        hint: '“Otra vez, por favor”.',
        accepted: ['もういちど おねがいします', 'もういちどお願いします'],
        modelAnswer: 'もういちど おねがいします',
        explanation: 'Se acepta la frase con o sin espacio.',
      },
    ],
  },
  'ja-05': {
    language: 'ja',
    title: 'Presentarme',
    level: 'A1.1',
    duration: '12–14 min',
    objective:
      'Puedo decir mi nombre, origen e idiomas y preguntar información básica.',
    introduction: {
      summary:
        'Construye una presentación breve con patrones fijos y partículas básicas.',
      concepts: [
        {
          title: 'Nombre + です',
          explanation:
            'です cierra una identificación cortés. は marca el tema y se pronuncia wa como partícula.',
          examples: [
            'サンティアゴです = Soy Santiago',
            'わたしは ディアナです = Yo soy Diana',
          ],
        },
        {
          title: 'Origen',
          explanation: 'Lugar + から来ました expresa de dónde vienes.',
          examples: [
            'メキシコから来ました = Vengo de México',
            'ブラジルから来ました = Vengo de Brasil',
          ],
        },
        {
          title: 'También',
          explanation: 'も sustituye a は para indicar “también”.',
          examples: [
            'わたしも メキシコから来ました = Yo también vengo de México',
          ],
        },
        {
          title: 'Idioma y preguntas',
          explanation:
            'Idioma + ができます expresa que puedes usar ese idioma; Nは？ pregunta por un dato entendido en contexto.',
          examples: [
            'スペイン語ができます = Hablo/puedo usar español',
            'お名前は？ = ¿Su nombre?',
          ],
        },
      ],
      tip: 'En una conversación natural puedes omitir わたしは cuando ya está claro que hablas de ti.',
    },
    exercises: [
      {
        id: 'ja-05-01',
        kind: 'choice',
        phase: 'activar',
        prompt: '¿Cómo dices “Soy Santiago”?',
        hint: 'Nombre + です.',
        options: ['サンティアゴです', 'サンティアゴから', 'サンティアゴも'],
        answer: 'サンティアゴです',
        explanation: 'Nombre + です sirve para identificarse cortésmente.',
      },
      {
        id: 'ja-05-02',
        kind: 'choice',
        phase: 'comprender',
        prompt: 'En わたしは ディアナです, は marca…',
        hint: 'Se pronuncia wa en esta función.',
        options: ['el tema', 'una pregunta', 'el pasado'],
        answer: 'el tema',
        explanation: 'La partícula は presenta el tema del enunciado.',
      },
      {
        id: 'ja-05-03',
        kind: 'choice',
        phase: 'comprender',
        prompt: '¿Qué significa メキシコから来ました?',
        hint: 'から señala el punto de origen.',
        options: ['Vengo de México.', 'Voy a México.', 'Hablo mexicano.'],
        answer: 'Vengo de México.',
        explanation: 'Lugar + から来ました expresa procedencia.',
      },
      {
        id: 'ja-05-04',
        kind: 'order',
        phase: 'practicar',
        prompt: 'Ordena “Yo soy Diana”.',
        hint: 'Tema + nombre + です.',
        tokens: ['ディアナ', 'です', 'わたしは'],
        answer: ['わたしは', 'ディアナ', 'です'],
        explanation: 'El patrón es わたしは N です.',
      },
      {
        id: 'ja-05-05',
        kind: 'choice',
        phase: 'practicar',
        prompt: 'Otra persona viene de México y tú también. ¿Qué dices?',
        hint: 'Usa も para “también”.',
        options: [
          'わたしも メキシコから来ました',
          'わたしは メキシコも',
          'メキシコですか',
        ],
        answer: 'わたしも メキシコから来ました',
        explanation: 'も presenta a “yo” como otro caso con el mismo origen.',
      },
      {
        id: 'ja-05-06',
        kind: 'choice',
        phase: 'practicar',
        prompt: '¿Qué significa スペイン語ができます?',
        hint: 'スペイン語 es “idioma español”.',
        options: [
          'Puedo hablar español.',
          'Vengo de España.',
          'Mi nombre es España.',
        ],
        answer: 'Puedo hablar español.',
        explanation:
          'Idioma + ができます expresa capacidad para usar ese idioma.',
      },
      {
        id: 'ja-05-07',
        kind: 'open',
        phase: 'transferir',
        prompt: 'Escribe: “Soy Santiago. Vengo de México”.',
        hint: 'Usa です y から来ました.',
        accepted: [
          'サンティアゴです。メキシコから来ました。',
          'サンティアゴです。 メキシコから来ました。',
          '私はサンティアゴです。メキシコから来ました。',
          '私はサンティアゴです。 メキシコから来ました。',
        ],
        modelAnswer: 'サンティアゴです。メキシコから来ました。',
        explanation: 'Las dos fórmulas crean una presentación básica.',
      },
      {
        id: 'ja-05-08',
        kind: 'open',
        phase: 'transferir',
        prompt: 'Escribe una presentación breve con nombre, origen e idioma.',
        hint: 'Puedes usar información ficticia y el patrón ができます.',
        accepted: [],
        modelAnswer:
          'はじめまして。ディアナです。メキシコから来ました。スペイン語ができます。',
        explanation:
          'La presentación debe incluir nombre con です, origen con から来ました e idioma con ができます.',
      },
    ],
  },
};
