import type { ModelLesson } from '@/lib/model-lessons';

export const batch4Lessons: Record<string, ModelLesson> = {
  'en-a1-05': {
    language: 'en',
    title: 'Mi día',
    level: 'A1.2',
    duration: '10–12 min',
    objective: 'Puedo decir la hora y explicar una rutina sencilla.',
    introduction: {
      summary:
        'Combina horas, presente simple y verbos cotidianos para contar cómo es un día normal.',
      concepts: [
        {
          title: 'La hora',
          explanation:
            'Usa It’s + hora; o’clock para la hora exacta y half past para y media.',
          examples: ["It's seven o'clock.", "It's half past eight."],
        },
        {
          title: 'Rutinas',
          explanation: 'El presente simple describe acciones habituales.',
          examples: ['I get up at seven.', 'She goes to work at eight.'],
        },
        {
          title: 'Orden del día',
          explanation: 'First, then y finally conectan actividades.',
          examples: ['First, I get dressed.', 'Then, I have breakfast.'],
        },
      ],
      tip: 'Con he/she recuerda añadir -s o -es al verbo.',
    },
    exercises: [
      {
        id: 'en-a1-05-01',
        kind: 'choice',
        phase: 'activar',
        prompt: '¿Qué significa “It’s seven o’clock”?',
        hint: 'Es una hora exacta.',
        options: ['Son las siete.', 'Son las siete y media.', 'Son las seis.'],
        answer: 'Son las siete.',
        explanation: 'O’clock indica una hora exacta.',
      },
      {
        id: 'en-a1-05-02',
        kind: 'choice',
        phase: 'comprender',
        prompt: 'Completa: I ___ breakfast at 8:00.',
        hint: 'La expresión es have breakfast.',
        options: ['have', 'has', 'am'],
        answer: 'have',
        explanation: 'Con I usamos la forma base have.',
      },
      {
        id: 'en-a1-05-03',
        kind: 'choice',
        phase: 'comprender',
        prompt: 'Completa: She ___ to work at nine.',
        hint: 'Tercera persona de go.',
        options: ['goes', 'go', 'going'],
        answer: 'goes',
        explanation: 'Con she, go cambia a goes.',
      },
      {
        id: 'en-a1-05-04',
        kind: 'order',
        phase: 'practicar',
        prompt: 'Ordena la rutina.',
        hint: 'Forma “Me levanto a las siete”.',
        tokens: ['at seven', 'get up', 'I'],
        answer: ['I', 'get up', 'at seven'],
        explanation: 'Sujeto + verbo + expresión de tiempo.',
      },
      {
        id: 'en-a1-05-05',
        kind: 'choice',
        phase: 'practicar',
        prompt: '¿Qué hora es 8:30?',
        hint: 'Usa half past.',
        options: [
          "It's half past eight.",
          "It's eight o'clock.",
          "It's half to eight.",
        ],
        answer: "It's half past eight.",
        explanation: 'Half past eight significa ocho y media.',
      },
      {
        id: 'en-a1-05-06',
        kind: 'order',
        phase: 'practicar',
        prompt: 'Ordena la secuencia.',
        hint: 'Primero desayuno; después voy al trabajo.',
        tokens: ['Then, I go to work.', 'First, I have breakfast.'],
        answer: ['First, I have breakfast.', 'Then, I go to work.'],
        explanation: 'First introduce la primera acción y then la siguiente.',
      },
      {
        id: 'en-a1-05-07',
        kind: 'open',
        phase: 'transferir',
        prompt: 'Escribe: “Voy a la cama a las diez”.',
        hint: 'Usa go to bed.',
        accepted: ['I go to bed at ten.', 'I go to bed at ten o’clock.'],
        modelAnswer: 'I go to bed at ten.',
        explanation: 'Go to bed describe la acción habitual.',
      },
      {
        id: 'en-a1-05-08',
        kind: 'open',
        phase: 'transferir',
        prompt: 'Describe tres acciones de tu día en orden.',
        hint: 'Usa first, then y finally.',
        accepted: [],
        modelAnswer:
          'First, I get up at seven. Then, I have breakfast. Finally, I go to work.',
        explanation:
          'Debe incluir tres actividades comprensibles y un orden claro.',
      },
    ],
  },
  'en-a1-06': {
    language: 'en',
    title: 'Lo que me gusta',
    level: 'A1.2',
    duration: '10–12 min',
    objective: 'Puedo expresar gustos y preguntar por preferencias.',
    introduction: {
      summary:
        'Expresa preferencias con like, love y hate, y pregunta a otras personas con do.',
      concepts: [
        {
          title: 'Grados de preferencia',
          explanation:
            'Love expresa gusto fuerte, like gusto y hate rechazo fuerte.',
          examples: ['I love music.', 'I like coffee.', 'I hate cold weather.'],
        },
        {
          title: 'Preguntar',
          explanation:
            'Do you like + sustantivo? pregunta por una preferencia.',
          examples: ['Do you like pizza?', 'Do you like books?'],
        },
        {
          title: 'Respuestas cortas',
          explanation: 'Responde Yes, I do o No, I don’t.',
          examples: ['Yes, I do.', 'No, I don’t.'],
        },
      ],
      tip: 'Después de like/love/hate puedes usar un sustantivo; la actividad con verbo + -ing se verá después.',
    },
    exercises: [
      {
        id: 'en-a1-06-01',
        kind: 'choice',
        phase: 'activar',
        prompt: '¿Qué frase expresa gusto?',
        hint: 'Busca like.',
        options: ['I like tea.', 'I am tea.', 'I do tea.'],
        answer: 'I like tea.',
        explanation: 'Like + sustantivo expresa preferencia.',
      },
      {
        id: 'en-a1-06-02',
        kind: 'choice',
        phase: 'comprender',
        prompt: '¿Qué palabra expresa el gusto más fuerte?',
        hint: 'Más intensa que like.',
        options: ['love', 'like', 'do'],
        answer: 'love',
        explanation: 'Love expresa una preferencia muy fuerte.',
      },
      {
        id: 'en-a1-06-03',
        kind: 'choice',
        phase: 'comprender',
        prompt: 'Completa: ___ you like coffee?',
        hint: 'Pregunta en presente simple.',
        options: ['Do', 'Are', 'Does'],
        answer: 'Do',
        explanation: 'Con you usamos Do al inicio.',
      },
      {
        id: 'en-a1-06-04',
        kind: 'order',
        phase: 'practicar',
        prompt: 'Ordena la pregunta.',
        hint: 'Pregunta si le gusta la música.',
        tokens: ['music', 'you', 'like', 'Do'],
        answer: ['Do', 'you', 'like', 'music'],
        explanation: 'Do + sujeto + verbo + complemento.',
      },
      {
        id: 'en-a1-06-05',
        kind: 'choice',
        phase: 'practicar',
        prompt: '“Do you like pizza?” Responde afirmativamente.',
        hint: 'Respuesta corta con do.',
        options: ['Yes, I do.', 'Yes, I like.', 'Yes, I am.'],
        answer: 'Yes, I do.',
        explanation: 'La respuesta corta repite el auxiliar do.',
      },
      {
        id: 'en-a1-06-06',
        kind: 'choice',
        phase: 'practicar',
        prompt: '¿Qué frase expresa rechazo fuerte?',
        hint: 'Busca hate.',
        options: ['I hate spiders.', 'I love spiders.', 'I do spiders.'],
        answer: 'I hate spiders.',
        explanation: 'Hate expresa disgusto intenso.',
      },
      {
        id: 'en-a1-06-07',
        kind: 'open',
        phase: 'transferir',
        prompt: 'Escribe: “Me gusta el café, pero no me gusta el té”.',
        hint: 'Usa like, don’t like y but.',
        accepted: [
          "I like coffee, but I don't like tea.",
          "I like coffee but I don't like tea.",
        ],
        modelAnswer: "I like coffee, but I don't like tea.",
        explanation: 'Don’t like expresa una preferencia negativa.',
      },
      {
        id: 'en-a1-06-08',
        kind: 'open',
        phase: 'transferir',
        prompt: 'Escribe una pregunta sobre gustos y una respuesta corta.',
        hint: 'Usa Do you like…?',
        accepted: [],
        modelAnswer: 'Do you like music? Yes, I do.',
        explanation:
          'Debe incluir una pregunta correcta y una respuesta coherente.',
      },
    ],
  },
  'ja-06': {
    language: 'ja',
    title: 'Familia y personas',
    level: 'A1.1',
    duration: '12–14 min',
    objective: 'Puedo presentar brevemente a mi familia y describir personas.',
    introduction: {
      summary:
        'Aprende vocabulario familiar y usa これ, この y の para identificar personas en una foto.',
      concepts: [
        {
          title: 'Familia',
          explanation: 'Estas palabras se usan al hablar de tu propia familia.',
          examples: [
            '父（ちち）= mi padre',
            '母（はは）= mi madre',
            '兄（あに）= mi hermano mayor',
            '妹（いもうと）= mi hermana menor',
          ],
        },
        {
          title: 'これ y この',
          explanation:
            'これ funciona solo; この acompaña siempre a un sustantivo.',
          examples: [
            'これは 写真です = Esto es una foto',
            'この人 = esta persona',
          ],
        },
        {
          title: 'Relación con の',
          explanation:
            'N1 の N2 conecta nombres y expresa relación o pertenencia.',
          examples: ['私の母 = mi madre', '家族の写真 = foto de la familia'],
        },
      ],
      tip: 'En japonés las palabras para tu propia familia pueden diferir de las usadas para la familia de otra persona.',
    },
    exercises: [
      {
        id: 'ja-06-01',
        kind: 'choice',
        phase: 'activar',
        prompt: '¿Qué significa 母（はは）?',
        hint: 'Miembro de tu propia familia.',
        options: ['mi madre', 'mi padre', 'mi hermana menor'],
        answer: 'mi madre',
        explanation: '母（はは）se usa para hablar de la propia madre.',
      },
      {
        id: 'ja-06-02',
        kind: 'choice',
        phase: 'comprender',
        prompt: 'Completa: これは ___ です。',
        hint: '“Esta es mi madre”.',
        options: ['私の母', '私母', '母の私'],
        answer: '私の母',
        explanation: '私の母 significa “mi madre”.',
      },
      {
        id: 'ja-06-03',
        kind: 'choice',
        phase: 'comprender',
        prompt: '¿Cuál forma significa “esta persona”?',
        hint: 'この acompaña a un nombre.',
        options: ['この人', 'これ人', '人この'],
        answer: 'この人',
        explanation: 'この debe ir antes del sustantivo 人.',
      },
      {
        id: 'ja-06-04',
        kind: 'order',
        phase: 'practicar',
        prompt: 'Ordena “Esta es una foto de mi familia”.',
        hint: 'Usa 家族の写真.',
        tokens: ['です', 'これは', '家族の写真'],
        answer: ['これは', '家族の写真', 'です'],
        explanation:
          'これは presenta el tema y 家族の写真 identifica el objeto.',
      },
      {
        id: 'ja-06-05',
        kind: 'choice',
        phase: 'practicar',
        prompt: '¿Qué significa 私の兄?',
        hint: '兄 es hermano mayor.',
        options: ['mi hermano mayor', 'mi hermano menor', 'mi padre'],
        answer: 'mi hermano mayor',
        explanation: '私の conecta “yo” con 兄.',
      },
      {
        id: 'ja-06-06',
        kind: 'choice',
        phase: 'practicar',
        prompt: '¿Qué pregunta significa “¿Quién es esta persona?”?',
        hint: 'だれ significa quién.',
        options: [
          'この人は だれですか？',
          'これは いくらですか？',
          '何歳ですか？',
        ],
        answer: 'この人は だれですか？',
        explanation: 'この人は だれですか pregunta quién es la persona.',
      },
      {
        id: 'ja-06-07',
        kind: 'open',
        phase: 'transferir',
        prompt: 'Escribe: “Esta es mi madre”.',
        hint: 'Usa これは y 私の母.',
        accepted: ['これは私の母です。', 'これは 私の母です。'],
        modelAnswer: 'これは 私の母です。',
        explanation: '私の母 identifica la relación familiar.',
      },
      {
        id: 'ja-06-08',
        kind: 'open',
        phase: 'transferir',
        prompt: 'Presenta a un familiar ficticio en una frase.',
        hint: 'Usa これは 私の…です.',
        accepted: [],
        modelAnswer: 'これは 私の兄です。',
        explanation:
          'La frase debe identificar claramente una relación familiar.',
      },
    ],
  },
  'ja-07': {
    language: 'ja',
    title: 'Comida y gustos',
    level: 'A1.1',
    duration: '12–14 min',
    objective: 'Puedo decir qué me gusta y pedir algo sencillo.',
    introduction: {
      summary:
        'Expresa gustos con が好きです y realiza un pedido básico con をください.',
      concepts: [
        {
          title: 'Gustos',
          explanation: 'El elemento que te gusta lleva が antes de 好きです.',
          examples: [
            'すしが好きです = Me gusta el sushi',
            'コーヒーが好きです = Me gusta el café',
          ],
        },
        {
          title: 'Preguntar gustos',
          explanation: '何が好きですか pregunta qué le gusta a alguien.',
          examples: ['何が好きですか？', 'ラーメンが好きです。'],
        },
        {
          title: 'Pedir',
          explanation: 'El objeto pedido lleva を y termina con ください.',
          examples: [
            '水をください = Agua, por favor',
            'これをください = Esto, por favor',
          ],
        },
      ],
      tip: '好き no funciona aquí como el verbo español “gustar”: aprende el patrón completo Nが好きです.',
    },
    exercises: [
      {
        id: 'ja-07-01',
        kind: 'choice',
        phase: 'activar',
        prompt: '¿Qué significa すしが好きです?',
        hint: '好き expresa gusto.',
        options: [
          'Me gusta el sushi.',
          'Quiero comprar sushi.',
          'No como sushi.',
        ],
        answer: 'Me gusta el sushi.',
        explanation: 'Nが好きです expresa que N te gusta.',
      },
      {
        id: 'ja-07-02',
        kind: 'choice',
        phase: 'comprender',
        prompt: 'Completa: コーヒー___好きです。',
        hint: 'Partícula del elemento gustado.',
        options: ['が', 'を', 'はを'],
        answer: 'が',
        explanation: 'El objeto del gusto se marca con が.',
      },
      {
        id: 'ja-07-03',
        kind: 'choice',
        phase: 'comprender',
        prompt: '¿Qué significa 水をください?',
        hint: 'Es una petición.',
        options: [
          'Agua, por favor.',
          'Me gusta el agua.',
          '¿Dónde está el agua?',
        ],
        answer: 'Agua, por favor.',
        explanation: 'Nをください pide N de manera sencilla.',
      },
      {
        id: 'ja-07-04',
        kind: 'order',
        phase: 'practicar',
        prompt: 'Ordena “Me gusta el ramen”.',
        hint: 'N + が + 好きです.',
        tokens: ['好きです', 'ラーメンが'],
        answer: ['ラーメンが', '好きです'],
        explanation: 'ラーメンが好きです es el patrón completo.',
      },
      {
        id: 'ja-07-05',
        kind: 'choice',
        phase: 'practicar',
        prompt: '¿Cómo preguntas “¿Qué te gusta?”?',
        hint: '何 significa qué.',
        options: ['何が好きですか？', '何をください？', 'どこが好きですか？'],
        answer: '何が好きですか？',
        explanation: '何が好きですか pregunta por una preferencia.',
      },
      {
        id: 'ja-07-06',
        kind: 'choice',
        phase: 'practicar',
        prompt: 'Señalas un producto. ¿Cómo dices “Esto, por favor”?',
        hint: 'これ = esto.',
        options: ['これをください', 'これが好きですか', 'これは何ですか'],
        answer: 'これをください',
        explanation:
          'これをください es una petición básica en una tienda o mostrador.',
      },
      {
        id: 'ja-07-07',
        kind: 'open',
        phase: 'transferir',
        prompt: 'Escribe: “Me gusta el café”.',
        hint: 'コーヒー + が好きです.',
        accepted: ['コーヒーが好きです。', 'コーヒーが好きです'],
        modelAnswer: 'コーヒーが好きです。',
        explanation: 'El elemento gustado lleva が.',
      },
      {
        id: 'ja-07-08',
        kind: 'open',
        phase: 'transferir',
        prompt: 'Pide agua en japonés.',
        hint: '水（みず） + をください.',
        accepted: [
          '水をください。',
          '水をください',
          'みずをください。',
          'みずをください',
        ],
        modelAnswer: '水をください。',
        explanation: 'を marca el objeto solicitado.',
      },
    ],
  },
};
