import type { ModelLesson } from '@/lib/model-lessons';
export const batch5Lessons: Record<string, ModelLesson> = {
  'en-a1-07': {
    language: 'en',
    title: 'Lugares y direcciones',
    level: 'A1.2',
    duration: '10–12 min',
    objective:
      'Puedo identificar lugares comunes y seguir indicaciones muy sencillas.',
    introduction: {
      summary:
        'Describe qué lugares hay y dónde están, y sigue instrucciones breves.',
      concepts: [
        {
          title: 'There is / are',
          explanation: 'There is va con singular; there are con plural.',
          examples: ['There is a bank.', 'There are two cafés.'],
        },
        {
          title: 'Ubicación',
          explanation: 'In, on y next to sitúan un lugar u objeto.',
          examples: ['in the park', 'on King Street', 'next to the bank'],
        },
        {
          title: 'Indicaciones',
          explanation: 'Los imperativos dan instrucciones directas.',
          examples: ['Go straight.', 'Turn left.', 'Stop here.'],
        },
      ],
      tip: 'Busca primero si el nombre es singular o plural.',
    },
    exercises: [
      {
        id: 'en-a1-07-01',
        kind: 'choice',
        phase: 'activar',
        prompt: 'Completa: There ___ a bank near here.',
        hint: 'Bank es singular.',
        options: ['is', 'are', 'be'],
        answer: 'is',
        explanation: 'There is se usa con un lugar singular.',
      },
      {
        id: 'en-a1-07-02',
        kind: 'choice',
        phase: 'comprender',
        prompt: 'Completa: There ___ two cafés.',
        hint: 'Two cafés es plural.',
        options: ['are', 'is', 'am'],
        answer: 'are',
        explanation: 'There are se usa con plural.',
      },
      {
        id: 'en-a1-07-03',
        kind: 'choice',
        phase: 'comprender',
        prompt: 'The pharmacy is next to the bank. ¿Dónde está?',
        hint: 'Next to indica cercanía inmediata.',
        options: [
          'Al lado del banco.',
          'Dentro del banco.',
          'Lejos del banco.',
        ],
        answer: 'Al lado del banco.',
        explanation: 'Next to significa al lado de.',
      },
      {
        id: 'en-a1-07-04',
        kind: 'order',
        phase: 'practicar',
        prompt: 'Ordena la indicación.',
        hint: 'Forma “Gira a la izquierda”.',
        tokens: ['left', 'Turn'],
        answer: ['Turn', 'left'],
        explanation: 'El imperativo comienza con el verbo Turn.',
      },
      {
        id: 'en-a1-07-05',
        kind: 'choice',
        phase: 'practicar',
        prompt: '¿Qué instrucción significa “Sigue derecho”?',
        hint: 'Busca straight.',
        options: ['Go straight.', 'Turn right.', 'Go back.'],
        answer: 'Go straight.',
        explanation: 'Go straight indica continuar sin girar.',
      },
      {
        id: 'en-a1-07-06',
        kind: 'choice',
        phase: 'practicar',
        prompt: '¿Qué pregunta busca un café cercano?',
        hint: 'Usa Is there…?',
        options: [
          'Is there a café near here?',
          'Are a café here?',
          'Where café is?',
        ],
        answer: 'Is there a café near here?',
        explanation: 'Is there + singular pregunta si existe algo.',
      },
      {
        id: 'en-a1-07-07',
        kind: 'open',
        phase: 'transferir',
        prompt: 'Escribe: “Hay un parque junto al hotel”.',
        hint: 'Usa there is y next to.',
        accepted: [
          'There is a park next to the hotel.',
          'There’s a park next to the hotel.',
        ],
        modelAnswer: 'There is a park next to the hotel.',
        explanation: 'There is presenta el lugar y next to lo sitúa.',
      },
      {
        id: 'en-a1-07-08',
        kind: 'open',
        phase: 'transferir',
        prompt: 'Da dos indicaciones sencillas en inglés.',
        hint: 'Usa go straight y turn.',
        accepted: [],
        modelAnswer: 'Go straight. Then turn right.',
        explanation: 'Debe contener dos instrucciones claras en orden.',
      },
    ],
  },
  'en-a1-08': {
    language: 'en',
    title: 'Proyecto: mi mundo',
    level: 'A1 consolidación',
    duration: '12–15 min',
    objective:
      'Puedo crear un perfil, presentar mi rutina y resolver intercambios básicos.',
    introduction: {
      summary:
        'Integra lo aprendido en A1 para presentarte, describir tu día y manejar un intercambio sencillo.',
      concepts: [
        {
          title: 'Perfil',
          explanation: 'Combina saludo, nombre, origen e idioma.',
          examples: ["Hi! I'm Diana.", "I'm from Mexico. I speak Spanish."],
        },
        {
          title: 'Rutina y gustos',
          explanation: 'Usa presente simple, horas y preferencias.',
          examples: ['I get up at seven.', 'I like music.'],
        },
        {
          title: 'Reparar',
          explanation: 'Pide repetición o aclara que no entiendes.',
          examples: ['Sorry, can you repeat that?', 'I don’t understand.'],
        },
      ],
      tip: 'El objetivo es comunicar un mensaje completo, aunque las frases sean cortas.',
    },
    exercises: [
      {
        id: 'en-a1-08-01',
        kind: 'choice',
        phase: 'activar',
        prompt: 'Elige la presentación completa.',
        hint: 'Debe incluir nombre y origen.',
        options: [
          "Hi, I'm Alex. I'm from Canada.",
          'Hi Canada Alex.',
          'From Alex is.',
        ],
        answer: "Hi, I'm Alex. I'm from Canada.",
        explanation: 'La opción usa dos estructuras A1 correctas.',
      },
      {
        id: 'en-a1-08-02',
        kind: 'choice',
        phase: 'comprender',
        prompt: 'No entendiste. ¿Qué dices?',
        hint: 'Pide repetición.',
        options: ['Sorry, can you repeat that?', 'Turn left.', 'I like pizza.'],
        answer: 'Sorry, can you repeat that?',
        explanation: 'La frase repara la comunicación.',
      },
      {
        id: 'en-a1-08-03',
        kind: 'choice',
        phase: 'comprender',
        prompt: 'Completa: She ___ breakfast at eight.',
        hint: 'Tercera persona.',
        options: ['has', 'have', 'having'],
        answer: 'has',
        explanation: 'Con she, have cambia a has.',
      },
      {
        id: 'en-a1-08-04',
        kind: 'order',
        phase: 'practicar',
        prompt: 'Ordena el perfil.',
        hint: 'Nombre, origen e idioma.',
        tokens: ['I speak Spanish.', 'I’m Diana.', 'I’m from Mexico.'],
        answer: ['I’m Diana.', 'I’m from Mexico.', 'I speak Spanish.'],
        explanation: 'La secuencia presenta identidad, origen e idioma.',
      },
      {
        id: 'en-a1-08-05',
        kind: 'choice',
        phase: 'practicar',
        prompt: '“Do you like tea?” Responde negativamente.',
        hint: 'Respuesta corta.',
        options: ["No, I don't.", 'No, I am not.', 'No, I like.'],
        answer: "No, I don't.",
        explanation: 'Las preguntas con do usan do en la respuesta.',
      },
      {
        id: 'en-a1-08-06',
        kind: 'order',
        phase: 'practicar',
        prompt: 'Ordena la rutina.',
        hint: 'Primero levantarse; luego desayunar.',
        tokens: ['Then, I have breakfast.', 'First, I get up at seven.'],
        answer: ['First, I get up at seven.', 'Then, I have breakfast.'],
        explanation: 'First y then organizan las acciones.',
      },
      {
        id: 'en-a1-08-07',
        kind: 'open',
        phase: 'transferir',
        prompt: 'Escribe un perfil con nombre, país, idioma y un gusto.',
        hint: 'Usa cuatro frases cortas.',
        accepted: [],
        modelAnswer:
          "Hi! I'm Diana. I'm from Mexico. I speak Spanish. I like music.",
        explanation: 'Debe cubrir los cuatro datos solicitados.',
      },
      {
        id: 'en-a1-08-08',
        kind: 'open',
        phase: 'transferir',
        prompt: 'Describe dos acciones de tu rutina y su hora.',
        hint: 'Usa presente simple y at.',
        accepted: [],
        modelAnswer: 'I get up at seven. I go to work at nine.',
        explanation: 'Debe incluir dos acciones con referencias horarias.',
      },
    ],
  },
  'ja-08': {
    language: 'ja',
    title: 'Casa y ubicación',
    level: 'A1.2',
    duration: '12–14 min',
    objective:
      'Puedo decir qué hay y preguntar dónde se encuentra alguien o algo.',
    introduction: {
      summary:
        'Distingue la existencia de objetos y seres vivos y sitúalos con に.',
      concepts: [
        {
          title: 'あります',
          explanation: 'Se usa para cosas que no se mueven por sí mismas.',
          examples: ['ここに机があります。', '本は部屋にあります。'],
        },
        {
          title: 'います',
          explanation: 'Se usa para personas y animales.',
          examples: ['猫がいます。', '田中さんは食堂にいます。'],
        },
        {
          title: 'Preguntar dónde',
          explanation: 'Nはどこにありますか/いますか pregunta la ubicación.',
          examples: [
            'トイレはどこにありますか？',
            '山田さんはどこにいますか？',
          ],
        },
      ],
      tip: 'Elige あります o います según qué existe, no según el lugar.',
    },
    exercises: [
      {
        id: 'ja-08-01',
        kind: 'choice',
        phase: 'activar',
        prompt: 'Hay una mesa. ¿Qué verbo eliges?',
        hint: 'Es un objeto.',
        options: ['あります', 'います', 'ですか'],
        answer: 'あります',
        explanation: 'あります se usa para objetos.',
      },
      {
        id: 'ja-08-02',
        kind: 'choice',
        phase: 'comprender',
        prompt: 'Hay un gato. Completa: 猫が___.',
        hint: 'Es un animal.',
        options: ['います', 'あります', 'します'],
        answer: 'います',
        explanation: 'います se usa para animales y personas.',
      },
      {
        id: 'ja-08-03',
        kind: 'choice',
        phase: 'comprender',
        prompt: '¿Qué significa 本は部屋にあります?',
        hint: '本 es libro; 部屋 es habitación.',
        options: [
          'El libro está en la habitación.',
          'Hay una persona en la habitación.',
          'La habitación es un libro.',
        ],
        answer: 'El libro está en la habitación.',
        explanation: 'Lugar + にあります sitúa un objeto.',
      },
      {
        id: 'ja-08-04',
        kind: 'order',
        phase: 'practicar',
        prompt: 'Ordena “Aquí hay un refrigerador”.',
        hint: 'Lugar に objeto があります.',
        tokens: ['冷蔵庫があります', 'ここに'],
        answer: ['ここに', '冷蔵庫があります'],
        explanation: 'ここに marca el lugar de existencia.',
      },
      {
        id: 'ja-08-05',
        kind: 'choice',
        phase: 'practicar',
        prompt: '¿Cómo preguntas dónde está el baño?',
        hint: 'Es un lugar/cosa, usa あります.',
        options: [
          'トイレはどこにありますか？',
          'トイレはだれですか？',
          'どこがトイレいますか？',
        ],
        answer: 'トイレはどこにありますか？',
        explanation: 'La estructura pregunta la ubicación de una cosa.',
      },
      {
        id: 'ja-08-06',
        kind: 'choice',
        phase: 'practicar',
        prompt: '田中さんは食堂にいます significa…',
        hint: '田中さん es una persona.',
        options: [
          'Tanaka está en el comedor.',
          'Hay una mesa en el comedor.',
          'Tanaka tiene un comedor.',
        ],
        answer: 'Tanaka está en el comedor.',
        explanation: 'Persona + は + lugar + にいます.',
      },
      {
        id: 'ja-08-07',
        kind: 'open',
        phase: 'transferir',
        prompt: 'Escribe: “Aquí hay un gato”.',
        hint: 'ここに + 猫がいます.',
        accepted: [
          'ここに猫がいます。',
          'ここに 猫がいます。',
          'ここに猫がいます',
        ],
        modelAnswer: 'ここに 猫がいます。',
        explanation: 'Como 猫 es animal, usamos います.',
      },
      {
        id: 'ja-08-08',
        kind: 'open',
        phase: 'transferir',
        prompt: 'Pregunta dónde está un libro.',
        hint: '本はどこに…?',
        accepted: ['本はどこにありますか？', '本は どこにありますか？'],
        modelAnswer: '本はどこにありますか？',
        explanation: 'Para un objeto usamos ありますか.',
      },
    ],
  },
  'ja-09': {
    language: 'ja',
    title: 'Hora y rutina',
    level: 'A1.2',
    duration: '12–14 min',
    objective: 'Puedo comprender horarios y describir acciones cotidianas.',
    introduction: {
      summary: 'Di la hora y conecta acciones cotidianas con に, から y まで.',
      concepts: [
        {
          title: 'Hora',
          explanation: '時 indica hora y 分 minutos.',
          examples: ['7時 = las siete', '7時30分 = siete y treinta'],
        },
        {
          title: 'Acción y hora',
          explanation: 'La hora específica lleva に antes del verbo en ます.',
          examples: ['7時に起きます。', '12時に昼ご飯を食べます。'],
        },
        {
          title: 'Desde y hasta',
          explanation: 'から marca inicio y まで final.',
          examples: ['9時から5時まで働きます。'],
        },
      ],
      tip: 'La lectura de algunos minutos cambia; aquí practicamos horarios frecuentes.',
    },
    exercises: [
      {
        id: 'ja-09-01',
        kind: 'choice',
        phase: 'activar',
        prompt: '¿Qué significa 7時?',
        hint: '時 marca la hora.',
        options: ['las siete', 'siete minutos', 'las siete y media'],
        answer: 'las siete',
        explanation: '7時 se lee しちじ y significa las siete.',
      },
      {
        id: 'ja-09-02',
        kind: 'choice',
        phase: 'comprender',
        prompt: 'Completa: 7時___起きます。',
        hint: 'Partícula para una hora específica.',
        options: ['に', 'を', 'が'],
        answer: 'に',
        explanation: 'La hora de una acción se marca con に.',
      },
      {
        id: 'ja-09-03',
        kind: 'choice',
        phase: 'comprender',
        prompt: '¿Qué significa 9時から5時まで?',
        hint: 'から = desde; まで = hasta.',
        options: [
          'de nueve a cinco',
          'a las nueve y cinco',
          'cinco minutos antes de nueve',
        ],
        answer: 'de nueve a cinco',
        explanation: 'から y まで delimitan un intervalo.',
      },
      {
        id: 'ja-09-04',
        kind: 'order',
        phase: 'practicar',
        prompt: 'Ordena “Me levanto a las seis”.',
        hint: 'Hora に + verbo.',
        tokens: ['起きます', '6時に'],
        answer: ['6時に', '起きます'],
        explanation: '6時に起きます expresa la hora de levantarse.',
      },
      {
        id: 'ja-09-05',
        kind: 'choice',
        phase: 'practicar',
        prompt: '¿Cómo escribes 8:30?',
        hint: '30分 son treinta minutos.',
        options: ['8時30分', '8分30時', '8時3分'],
        answer: '8時30分',
        explanation: 'Primero hora con 時 y luego minutos con 分.',
      },
      {
        id: 'ja-09-06',
        kind: 'choice',
        phase: 'practicar',
        prompt: '昼ご飯を食べます significa…',
        hint: '昼ご飯 es almuerzo.',
        options: ['Como el almuerzo.', 'Me levanto.', 'Me duermo.'],
        answer: 'Como el almuerzo.',
        explanation: '昼ご飯 es “almuerzo” y 食べます significa “comer”.',
      },
      {
        id: 'ja-09-07',
        kind: 'open',
        phase: 'transferir',
        prompt: 'Escribe: “Me levanto a las siete”.',
        hint: '7時に + 起きます.',
        accepted: ['7時に起きます。', '7時に 起きます。', '7時に起きます'],
        modelAnswer: '7時に起きます。',
        explanation: 'La hora lleva に.',
      },
      {
        id: 'ja-09-08',
        kind: 'open',
        phase: 'transferir',
        prompt: 'Escribe un horario de trabajo de nueve a cinco.',
        hint: '9時から5時まで + 働きます.',
        accepted: ['9時から5時まで働きます。', '9時から5時まで 働きます。'],
        modelAnswer: '9時から5時まで働きます。',
        explanation: 'から y まで expresan el intervalo.',
      },
    ],
  },
};
