export type CurriculumUnit = {
  id: string;
  level: string;
  title: string;
  canDo: string;
  languageFocus: string[];
  skills: string[];
  exerciseTypes: string[];
};

const unit = (
  id: string,
  level: string,
  title: string,
  canDo: string,
  languageFocus: string[],
  skills: string[],
  exerciseTypes: string[],
): CurriculumUnit => ({
  id,
  level,
  title,
  canDo,
  languageFocus,
  skills,
  exerciseTypes,
});

export const englishCurriculum: CurriculumUnit[] = [
  unit(
    'en-a1-01',
    'A1.1',
    'Primer contacto',
    'Puedo saludar, despedirme y usar expresiones básicas de cortesía.',
    ['be: I am/you are', 'saludos', 'please/thank you'],
    ['escuchar', 'interactuar'],
    ['respuesta situacional', 'ordenar diálogo', 'repetición'],
  ),
  unit(
    'en-a1-02',
    'A1.1',
    'Mi identidad',
    'Puedo decir y deletrear mi nombre, país, idioma y datos básicos.',
    ['alfabeto', 'pronombres sujeto', 'be afirmativo'],
    ['hablar', 'escribir'],
    ['deletreo', 'formulario', 'presentación guiada'],
  ),
  unit(
    'en-a1-03',
    'A1.1',
    'Números y objetos',
    'Puedo reconocer cantidades, precios y objetos cotidianos.',
    ['números 0–100', 'a/an', 'this/that'],
    ['escuchar', 'leer'],
    ['sonido-número', 'etiquetar', 'selección visual'],
  ),
  unit(
    'en-a1-04',
    'A1.1',
    'Familia y personas',
    'Puedo presentar a mi familia y describir a una persona con frases breves.',
    ['have got', 'posesivos', 'adjetivos básicos'],
    ['hablar', 'leer'],
    ['árbol familiar', 'descripción', 'completar perfil'],
  ),
  unit(
    'en-a1-05',
    'A1.2',
    'Mi día',
    'Puedo decir la hora y explicar una rutina sencilla.',
    ['presente simple afirmativo', 'horas', 'verbos cotidianos'],
    ['escuchar', 'hablar'],
    ['reloj', 'ordenar rutina', 'dictado corto'],
  ),
  unit(
    'en-a1-06',
    'A1.2',
    'Lo que me gusta',
    'Puedo expresar gustos y preguntar por preferencias.',
    ['like/love/hate + noun', 'do questions', 'respuestas cortas'],
    ['interactuar', 'escribir'],
    ['encuesta', 'clasificar gustos', 'mini diálogo'],
  ),
  unit(
    'en-a1-07',
    'A1.2',
    'Lugares y direcciones',
    'Puedo identificar lugares comunes y seguir indicaciones muy sencillas.',
    ['there is/are inicial', 'in/on/next to', 'imperativos'],
    ['escuchar', 'leer'],
    ['mapa', 'seguir ruta', 'emparejar señal'],
  ),
  unit(
    'en-a1-08',
    'A1 consolidación',
    'Proyecto: mi mundo',
    'Puedo crear un perfil, presentar mi rutina y resolver intercambios básicos.',
    ['repaso A1', 'preguntas frecuentes', 'estrategias de aclaración'],
    ['todas'],
    ['misión integrada', 'presentación', 'diagnóstico A2'],
  ),
  unit(
    'en-01',
    'A2.1',
    'Punto de partida',
    'Puedo presentarme, pedir información personal y mantener un intercambio breve.',
    ['presente simple', 'preguntas con be/do', 'datos personales'],
    ['hablar', 'escuchar'],
    ['selección contextual', 'ordenar diálogo', 'respuesta oral'],
  ),
  unit(
    'en-02',
    'A2.1',
    'Rutinas y tiempo',
    'Puedo describir mi rutina, frecuencia y horarios.',
    ['presente simple', 'adverbios de frecuencia', 'preposiciones de tiempo'],
    ['hablar', 'escribir'],
    ['completar frase', 'agenda interactiva', 'dictado'],
  ),
  unit(
    'en-03',
    'A2.1',
    'Hogar y comunidad',
    'Puedo describir mi casa, mi barrio y dónde están las cosas.',
    ['there is/are', 'preposiciones de lugar', 'cuantificadores'],
    ['leer', 'hablar'],
    ['etiquetar imagen', 'descripción guiada', 'verdadero/falso'],
  ),
  unit(
    'en-04',
    'A2.1',
    'Comida y compras',
    'Puedo pedir comida, comparar precios y expresar preferencias.',
    ['countable/uncountable', 'some/any', 'comparativos'],
    ['escuchar', 'interactuar'],
    ['menú ramificado', 'clasificación', 'role-play'],
  ),
  unit(
    'en-05',
    'A2.2',
    'Experiencias pasadas',
    'Puedo contar qué hice y ordenar acontecimientos sencillos.',
    ['pasado simple', 'marcadores temporales', 'conectores básicos'],
    ['hablar', 'escribir'],
    ['línea temporal', 'transformación', 'relato breve'],
  ),
  unit(
    'en-06',
    'A2.2',
    'Viajes prácticos',
    'Puedo pedir indicaciones, comprar billetes y resolver necesidades de viaje.',
    ['imperativos', 'can/could', 'preguntas indirectas básicas'],
    ['escuchar', 'interactuar'],
    ['mapa y ruta', 'diálogo', 'escucha selectiva'],
  ),
  unit(
    'en-07',
    'A2.2',
    'Planes y acuerdos',
    'Puedo proponer un plan, aceptar, rechazar y acordar detalles.',
    ['be going to', 'presente continuo futuro', 'expresiones de tiempo'],
    ['hablar', 'escuchar'],
    ['calendario', 'reconstruir chat', 'respuesta libre'],
  ),
  unit(
    'en-08',
    'A2.2',
    'Salud cotidiana',
    'Puedo describir síntomas y comprender consejos sencillos.',
    ['should/shouldn’t', 'have got', 'partes del cuerpo'],
    ['escuchar', 'hablar'],
    ['emparejar síntoma', 'consulta simulada', 'pronunciación'],
  ),
  unit(
    'en-09',
    'B1.1',
    'Historias y recuerdos',
    'Puedo narrar una experiencia conectando acciones y contexto.',
    ['past simple/continuous', 'when/while', 'secuenciadores'],
    ['hablar', 'escribir'],
    ['ordenar historia', 'corregir error', 'narración'],
  ),
  unit(
    'en-10',
    'B1.1',
    'Trabajo y estudios',
    'Puedo explicar responsabilidades, habilidades y objetivos.',
    ['present perfect básico', 'for/since', 'verbos de habilidad'],
    ['leer', 'hablar'],
    ['perfil profesional', 'entrevista', 'resumen'],
  ),
  unit(
    'en-11',
    'B1.1',
    'Opiniones y razones',
    'Puedo expresar una opinión y justificarla con razones sencillas.',
    ['because/so/although', 'verbos de opinión', 'grado'],
    ['hablar', 'escribir'],
    ['debate guiado', 'clasificar argumentos', 'párrafo'],
  ),
  unit(
    'en-12',
    'B1.1',
    'Noticias y medios',
    'Puedo comprender los puntos principales de noticias claras.',
    ['voz pasiva básica', 'estilo indirecto inicial', 'titulares'],
    ['leer', 'escuchar'],
    ['titular-resumen', 'idea principal', 'noticia breve'],
  ),
  unit(
    'en-13',
    'B1.1',
    'Relaciones y comunicación',
    'Puedo pedir favores, responder a noticias y aclarar malentendidos.',
    ['peticiones corteses', 'phrasal verbs frecuentes', 'entonación'],
    ['interactuar', 'escuchar'],
    ['respuesta adecuada', 'reparar diálogo', 'role-play'],
  ),
  unit(
    'en-14',
    'B1.2',
    'Decisiones y posibilidades',
    'Puedo comparar opciones y explicar consecuencias posibles.',
    ['primer condicional', 'might/may', 'comparativos avanzados'],
    ['hablar', 'leer'],
    ['árbol de decisión', 'escenario', 'recomendación'],
  ),
  unit(
    'en-15',
    'B1.2',
    'Tecnología diaria',
    'Puedo explicar un problema técnico y seguir instrucciones.',
    ['relative clauses', 'imperativos secuenciados', 'vocabulario digital'],
    ['leer', 'interactuar'],
    ['manual breve', 'soporte simulado', 'ordenar pasos'],
  ),
  unit(
    'en-16',
    'B1.2',
    'Cultura y entretenimiento',
    'Puedo reseñar una obra y recomendarla con razones.',
    ['present perfect vs past', 'adjetivos -ed/-ing', 'lenguaje de reseña'],
    ['leer', 'escribir'],
    ['reseña comparada', 'cloze', 'recomendación oral'],
  ),
  unit(
    'en-17',
    'B1.2',
    'Medio ambiente',
    'Puedo explicar un problema y proponer medidas realistas.',
    ['pasiva', 'cuantificadores', 'causa y efecto'],
    ['escuchar', 'hablar'],
    ['infografía', 'mini presentación', 'priorizar soluciones'],
  ),
  unit(
    'en-18',
    'B1.2',
    'Consolidación B1',
    'Puedo integrar comprensión, interacción y producción en situaciones familiares.',
    ['repaso B1', 'estrategias de compensación', 'autocorrección'],
    ['todas'],
    ['misión integrada', 'prueba adaptativa', 'reflexión'],
  ),
  unit(
    'en-19',
    'B2.1',
    'Argumentar con claridad',
    'Puedo sostener una postura, matizarla y responder a otra opinión.',
    ['conectores discursivos', 'hedging', 'énfasis'],
    ['hablar', 'escribir'],
    ['debate', 'reescritura de tono', 'ensayo corto'],
  ),
  unit(
    'en-20',
    'B2.1',
    'Textos complejos',
    'Puedo identificar tesis, postura e implicaciones en artículos extensos.',
    ['referencia textual', 'cohesión', 'léxico abstracto'],
    ['leer', 'mediar'],
    ['anotar argumento', 'inferencias', 'resumen'],
  ),
  unit(
    'en-21',
    'B2.1',
    'Habla natural',
    'Puedo seguir conversaciones extensas y participar con fluidez razonable.',
    ['discourse markers', 'connected speech', 'turn-taking'],
    ['escuchar', 'interactuar'],
    ['shadowing', 'detectar actitud', 'conversación abierta'],
  ),
  unit(
    'en-22',
    'B2.2',
    'Entornos profesionales',
    'Puedo participar en reuniones, negociar y redactar mensajes formales claros.',
    [
      'registro formal',
      'condicionales mixtos iniciales',
      'colocaciones laborales',
    ],
    ['interactuar', 'escribir'],
    ['reunión simulada', 'correo', 'negociación'],
  ),
  unit(
    'en-23',
    'B2.2',
    'Presentar y mediar',
    'Puedo explicar información compleja y hacerla accesible para otra persona.',
    ['reformulación', 'signposting', 'lenguaje de datos'],
    ['hablar', 'mediar'],
    ['presentación', 'explicar gráfica', 'síntesis cruzada'],
  ),
  unit(
    'en-24',
    'B2.2',
    'Proyecto B2',
    'Puedo investigar, defender y presentar una propuesta detallada.',
    ['integración B2', 'revisión y edición', 'precisión léxica'],
    ['todas'],
    ['proyecto', 'entrevista oral', 'portafolio final'],
  ),
];

export const japaneseCurriculum: CurriculumUnit[] = [
  unit(
    'ja-01',
    'Pre-A1',
    'Sonidos y hiragana I',
    'Puedo reconocer y pronunciar las vocales y la primera serie de hiragana.',
    ['あいうえお', 'かきくけこ', 'ritmo silábico'],
    ['leer', 'pronunciar'],
    ['trazo guiado', 'sonido-caracter', 'discriminación auditiva'],
  ),
  unit(
    'ja-02',
    'Pre-A1',
    'Hiragana II',
    'Puedo leer palabras breves escritas con las series básicas.',
    ['さ～ん', 'dakuten', 'sonidos contraídos'],
    ['leer', 'escribir'],
    ['trazo', 'construir palabra', 'dictado kana'],
  ),
  unit(
    'ja-03',
    'Pre-A1',
    'Katakana esencial',
    'Puedo reconocer katakana frecuente en nombres y préstamos.',
    ['katakana básico', 'vocales largas', 'préstamos'],
    ['leer', 'escribir'],
    ['parejas kana', 'nombre propio', 'detección visual'],
  ),
  unit(
    'ja-04',
    'A1.1',
    'Saludos y reparación',
    'Puedo saludar, despedirme, agradecer y pedir que repitan.',
    ['こんにちは', 'ありがとうございます', 'もういちど おねがいします'],
    ['escuchar', 'interactuar'],
    ['respuesta situacional', 'ordenar diálogo', 'shadowing'],
  ),
  unit(
    'ja-05',
    'A1.1',
    'Presentarme',
    'Puedo decir mi nombre, origen e idiomas y preguntar lo mismo.',
    ['Nです', 'は/も', 'から きました'],
    ['hablar', 'escribir'],
    ['tarjeta personal', 'entrevista', 'partículas'],
  ),
  unit(
    'ja-06',
    'A1.1',
    'Familia y personas',
    'Puedo presentar brevemente a mi familia y describir personas.',
    ['これ/この', 'posesión の', 'vocabulario familiar'],
    ['hablar', 'leer'],
    ['árbol familiar', 'descripción', 'selección de referente'],
  ),
  unit(
    'ja-07',
    'A1.1',
    'Comida y gustos',
    'Puedo decir qué me gusta y pedir algo sencillo.',
    ['〜が好きです', 'を〜ください', 'partículas が/を'],
    ['interactuar', 'escuchar'],
    ['menú', 'pedido simulado', 'clasificar gustos'],
  ),
  unit(
    'ja-08',
    'A1.2',
    'Casa y ubicación',
    'Puedo decir qué hay y preguntar dónde se encuentra alguien o algo.',
    ['あります/います', 'に', '位置'],
    ['hablar', 'leer'],
    ['mapa', 'etiquetar estancia', 'pregunta-respuesta'],
  ),
  unit(
    'ja-09',
    'A1.2',
    'Hora y rutina',
    'Puedo comprender horarios y describir acciones cotidianas.',
    ['ます形', '時/分', 'から/まで'],
    ['escuchar', 'hablar'],
    ['reloj', 'agenda', 'ordenar rutina'],
  ),
  unit(
    'ja-10',
    'A1.2',
    'Aficiones e invitaciones',
    'Puedo hablar de aficiones e invitar a una actividad.',
    ['Vますか', 'ませんか', 'いいですね'],
    ['interactuar', 'escuchar'],
    ['invitación ramificada', 'preferencias', 'diálogo'],
  ),
  unit(
    'ja-11',
    'A1.2',
    'Moverme por la ciudad',
    'Puedo preguntar por transporte y comprender indicaciones simples.',
    ['へ/で', 'どこ/どうやって', 'direcciones'],
    ['escuchar', 'interactuar'],
    ['mapa', 'anuncio breve', 'ruta'],
  ),
  unit(
    'ja-12',
    'A1.2',
    'Comprar',
    'Puedo pedir productos, cantidades y precios.',
    ['これ/それ/あれ', 'いくら', 'contadores'],
    ['leer', 'interactuar'],
    ['tienda simulada', 'precio-sonido', 'selección contextual'],
  ),
  unit(
    'ja-13',
    'A1 consolidación',
    'Fin de semana',
    'Puedo decir qué hice y qué quiero hacer.',
    ['pasado ました', 'たいです', 'marcadores temporales'],
    ['hablar', 'escribir'],
    ['diario breve', 'línea temporal', 'planes'],
  ),
  unit(
    'ja-14',
    'A2.1',
    'Mi situación actual',
    'Puedo explicar de forma breve dónde vivo, trabajo o estudio.',
    ['forma diccionario', 'ています', 'profesiones'],
    ['hablar', 'leer'],
    ['perfil', 'entrevista', 'comprensión específica'],
  ),
  unit(
    'ja-15',
    'A2.1',
    'Clima y estaciones',
    'Puedo comprender un pronóstico y hablar de cambios del tiempo.',
    ['adjetivos い/な', 'なります', 'comparación'],
    ['escuchar', 'hablar'],
    ['pronóstico', 'comparar ciudades', 'descripción'],
  ),
  unit(
    'ja-16',
    'A2.1',
    'Salud y bienestar',
    'Puedo describir mi estado y comprender consejos básicos.',
    ['～んです', 'ないでください', 'ほうがいい'],
    ['interactuar', 'escuchar'],
    ['consulta', 'emparejar consejo', 'role-play'],
  ),
  unit(
    'ja-17',
    'A2.1',
    'Experiencias',
    'Puedo hablar de experiencias y actividades que sé hacer.',
    ['たことがあります', 'ことができます', 'や/など'],
    ['hablar', 'escribir'],
    ['encuesta', 'relato', 'transformación'],
  ),
  unit(
    'ja-18',
    'A2.2',
    'Reglas y convivencia',
    'Puedo comprender reglas y explicar permiso u obligación.',
    ['てもいい', 'てはいけない', 'なければならない'],
    ['leer', 'interactuar'],
    ['señales', 'escenario', 'reformular regla'],
  ),
  unit(
    'ja-19',
    'A2.2',
    'Planes y coordinación',
    'Puedo acordar lugar, hora y cambios sencillos en un plan.',
    ['つもりです', '予定です', 'なら'],
    ['interactuar', 'escuchar'],
    ['chat reconstruido', 'calendario', 'negociación breve'],
  ),
  unit(
    'ja-20',
    'A2 consolidación',
    'Proyecto de vida diaria',
    'Puedo resolver una secuencia de tareas cotidianas usando japonés sencillo.',
    ['integración A2', 'kanji elemental', 'estrategias de reparación'],
    ['todas'],
    ['misión integrada', 'presentación breve', 'portafolio'],
  ),
  unit(
    'ja-21',
    'B1.1',
    'Relatar experiencias',
    'Puedo narrar una experiencia personal con una secuencia clara y detalles relevantes.',
    ['普通形', '～とき', 'conectores narrativos'],
    ['hablar', 'escribir'],
    ['línea temporal', 'relato oral', 'revisión'],
  ),
  unit(
    'ja-22',
    'B1.1',
    'Explicar razones',
    'Puedo explicar decisiones, causas y consecuencias sobre temas familiares.',
    ['～ので/～から', '～ために', 'causa-efecto'],
    ['hablar', 'interactuar'],
    ['unir argumentos', 'explicación', 'role-play'],
  ),
  unit(
    'ja-23',
    'B1.1',
    'Opiniones cotidianas',
    'Puedo expresar una opinión sencilla y reaccionar respetuosamente a otra.',
    ['～と思います', '～かもしれません', 'acuerdo/desacuerdo'],
    ['interactuar', 'escuchar'],
    ['mini debate', 'intención del hablante', 'respuesta abierta'],
  ),
  unit(
    'ja-24',
    'B1.1',
    'Noticias cercanas',
    'Puedo comprender los puntos principales de noticias claras sobre temas conocidos.',
    ['受身 inicial', '～そうです', 'lenguaje informativo'],
    ['leer', 'escuchar'],
    ['titular-resumen', 'idea principal', 'reporte breve'],
  ),
  unit(
    'ja-25',
    'B1.1',
    'Trabajo y estudio',
    'Puedo describir responsabilidades, procedimientos y metas personales.',
    ['～ことになっています', '～ようにしています', 'léxico académico/laboral'],
    ['hablar', 'leer'],
    ['entrevista', 'ordenar procedimiento', 'perfil'],
  ),
  unit(
    'ja-26',
    'B1.2',
    'Resolver problemas',
    'Puedo explicar un problema, pedir ayuda y negociar una solución práctica.',
    ['～てしまいました', '～てもらえませんか', 'condicional ～たら'],
    ['interactuar', 'escuchar'],
    ['soporte simulado', 'árbol de decisión', 'reparar diálogo'],
  ),
  unit(
    'ja-27',
    'B1.2',
    'Cultura y recomendaciones',
    'Puedo reseñar una experiencia cultural y recomendarla dando razones.',
    ['～し～し', '～ほうが', 'evaluación y matiz'],
    ['escribir', 'hablar'],
    ['reseña', 'recomendación', 'comparar opciones'],
  ),
  unit(
    'ja-28',
    'B1 consolidación',
    'Proyecto B1',
    'Puedo investigar un tema familiar y presentar conclusiones conectadas.',
    ['integración B1', 'cohesión', 'autocorrección'],
    ['todas'],
    ['proyecto', 'preguntas del público', 'portafolio'],
  ),
  unit(
    'ja-29',
    'B2.1',
    'Argumentar y matizar',
    'Puedo defender una postura, reconocer otra perspectiva y matizar afirmaciones.',
    ['～一方で', '～とは限らない', 'hedging japonés'],
    ['hablar', 'escribir'],
    ['debate', 'reescritura de tono', 'ensayo corto'],
  ),
  unit(
    'ja-30',
    'B2.1',
    'Comprensión extensa',
    'Puedo seguir las ideas principales y secundarias de textos y charlas complejas.',
    ['cohesión referencial', 'nominalización', 'léxico abstracto'],
    ['leer', 'escuchar'],
    ['mapa de argumento', 'inferencia', 'resumen'],
  ),
  unit(
    'ja-31',
    'B2.1',
    'Registro y adecuación',
    'Puedo adaptar mi forma de hablar según relación, propósito y situación.',
    ['敬語 funcional', 'registro formal/informal', 'atenuación'],
    ['interactuar', 'mediar'],
    ['cambiar registro', 'escenario social', 'corregir adecuación'],
  ),
  unit(
    'ja-32',
    'B2.1',
    'Sociedad contemporánea',
    'Puedo discutir cuestiones sociales conocidas usando evidencia y ejemplos.',
    ['～に対して', '～によると', 'citar y contrastar'],
    ['leer', 'hablar'],
    ['síntesis de fuentes', 'discusión', 'presentación'],
  ),
  unit(
    'ja-33',
    'B2.2',
    'Comunicación profesional',
    'Puedo participar en reuniones y redactar mensajes profesionales claros.',
    ['敬語 aplicado', 'lenguaje de reuniones', 'correo formal'],
    ['interactuar', 'escribir'],
    ['reunión simulada', 'correo', 'seguimiento'],
  ),
  unit(
    'ja-34',
    'B2.2',
    'Mediar información',
    'Puedo reformular y explicar información compleja para otra persona.',
    ['言い換え', 'definición', 'organización discursiva'],
    ['mediar', 'hablar'],
    ['explicar gráfica', 'síntesis cruzada', 'paráfrasis'],
  ),
  unit(
    'ja-35',
    'B2.2',
    'Narrativa y perspectiva',
    'Puedo interpretar y producir relatos detallados con distintos puntos de vista.',
    ['estilo indirecto', 'perspectiva', 'recursos narrativos'],
    ['leer', 'escribir'],
    ['cambiar perspectiva', 'análisis', 'relato extendido'],
  ),
  unit(
    'ja-36',
    'B2 consolidación',
    'Proyecto B2',
    'Puedo investigar, presentar y defender una propuesta detallada en japonés.',
    ['integración B2', 'revisión', 'precisión pragmática'],
    ['todas'],
    ['proyecto final', 'defensa oral', 'portafolio'],
  ),
];

export const frenchCurriculum: CurriculumUnit[] = [
  unit(
    'fr-01',
    'A1.1',
    'Premiers mots',
    'Puedo saludar, despedirme y emplear fórmulas básicas de cortesía.',
    ['bonjour/au revoir', 'tu/vous', 'sons du français'],
    ['escuchar', 'interactuar'],
    ['respuesta situacional', 'shadowing', 'ordenar diálogo'],
  ),
  unit(
    'fr-02',
    'A1.1',
    'Mon identité',
    'Puedo presentarme, deletrear y dar información personal básica.',
    ['être/s’appeler', 'alphabet', 'questions simples'],
    ['hablar', 'escribir'],
    ['formulario', 'deletreo', 'entrevista'],
  ),
  unit(
    'fr-03',
    'A1.1',
    'Pays et langues',
    'Puedo decir mi origen, nacionalidad, lugar de residencia e idiomas.',
    ['habiter/venir', 'à/en/au/aux', 'genre'],
    ['hablar', 'leer'],
    ['mapa', 'transformación de género', 'perfil'],
  ),
  unit(
    'fr-04',
    'A1.1',
    'Famille et entourage',
    'Puedo presentar a familiares y describir relaciones cercanas.',
    ['avoir', 'possessifs', 'c’est/il est'],
    ['hablar', 'leer'],
    ['árbol familiar', 'referentes', 'descripción'],
  ),
  unit(
    'fr-05',
    'A1.2',
    'Nombres et horaires',
    'Puedo comprender números, precios, fechas y horas.',
    ['nombres', 'il est… heure', 'dates'],
    ['escuchar', 'leer'],
    ['sonido-número', 'reloj', 'calendario'],
  ),
  unit(
    'fr-06',
    'A1.2',
    'Ma journée',
    'Puedo describir una rutina cotidiana con frases sencillas.',
    ['présent régulier', 'verbes pronominaux', 'fréquence'],
    ['hablar', 'escribir'],
    ['ordenar rutina', 'conjugación contextual', 'diario'],
  ),
  unit(
    'fr-07',
    'A1.2',
    'Goûts et loisirs',
    'Puedo hablar de gustos y preguntar por actividades preferidas.',
    ['aimer/adorer/détester', 'faire/jouer', 'articles'],
    ['interactuar', 'escuchar'],
    ['encuesta', 'clasificar', 'invitación breve'],
  ),
  unit(
    'fr-08',
    'A1 consolidación',
    'Projet: me présenter',
    'Puedo mantener un intercambio básico sobre mí y mi vida cotidiana.',
    ['repaso A1', 'preguntas frecuentes', 'pronunciación básica'],
    ['todas'],
    ['misión integrada', 'presentación', 'diagnóstico A2'],
  ),
  unit(
    'fr-09',
    'A2.1',
    'Maison et quartier',
    'Puedo describir mi vivienda, barrio y ubicación de servicios.',
    ['il y a', 'prépositions de lieu', 'on'],
    ['hablar', 'leer'],
    ['mapa', 'etiquetar', 'descripción'],
  ),
  unit(
    'fr-10',
    'A2.1',
    'Courses et quantités',
    'Puedo comprar, pedir cantidades y comparar productos sencillos.',
    ['partitifs', 'combien', 'comparatifs'],
    ['interactuar', 'escuchar'],
    ['tienda simulada', 'lista de compra', 'comparación'],
  ),
  unit(
    'fr-11',
    'A2.1',
    'Au restaurant',
    'Puedo comprender un menú, pedir comida y expresar preferencias.',
    ['je voudrais', 'articles partitifs', 'pronoms toniques'],
    ['leer', 'interactuar'],
    ['menú', 'role-play', 'escucha selectiva'],
  ),
  unit(
    'fr-12',
    'A2.1',
    'Se déplacer',
    'Puedo pedir y seguir indicaciones y utilizar transporte público.',
    ['impératif', 'aller/prendre', 'où/comment'],
    ['escuchar', 'interactuar'],
    ['mapa', 'anuncio', 'ruta'],
  ),
  unit(
    'fr-13',
    'A2.2',
    'Passé récent',
    'Puedo contar actividades y acontecimientos pasados sencillos.',
    ['passé composé', 'auxiliaires', 'marqueurs temporels'],
    ['hablar', 'escribir'],
    ['línea temporal', 'auxiliar correcto', 'relato'],
  ),
  unit(
    'fr-14',
    'A2.2',
    'Projets et invitations',
    'Puedo proponer un plan, responder y acordar detalles.',
    ['futur proche', 'vouloir/pouvoir', 'expressions de temps'],
    ['interactuar', 'escuchar'],
    ['calendario', 'chat reconstruido', 'negociación breve'],
  ),
  unit(
    'fr-15',
    'A2.2',
    'Santé quotidienne',
    'Puedo describir síntomas y comprender recomendaciones básicas.',
    ['avoir mal', 'devoir/il faut', 'corps'],
    ['escuchar', 'hablar'],
    ['consulta', 'síntoma-consejo', 'pronunciación'],
  ),
  unit(
    'fr-16',
    'A2 consolidación',
    'Projet: séjour francophone',
    'Puedo resolver una secuencia de tareas durante una estancia.',
    ['repaso A2', 'reparación', 'registro cotidiano'],
    ['todas'],
    ['misión integrada', 'correo', 'interacción'],
  ),
  unit(
    'fr-17',
    'B1.1',
    'Récits et souvenirs',
    'Puedo narrar una experiencia conectando contexto y acontecimientos.',
    ['imparfait/passé composé', 'quand/pendant', 'séquence'],
    ['hablar', 'escribir'],
    ['ordenar historia', 'contraste verbal', 'relato'],
  ),
  unit(
    'fr-18',
    'B1.1',
    'Travail et études',
    'Puedo explicar formación, responsabilidades y objetivos.',
    ['depuis/pendant', 'relatifs qui/que', 'lexique professionnel'],
    ['hablar', 'leer'],
    ['perfil', 'entrevista', 'resumen'],
  ),
  unit(
    'fr-19',
    'B1.1',
    'Donner son avis',
    'Puedo expresar y justificar una opinión sobre temas conocidos.',
    ['parce que/donc/pourtant', 'verbes d’opinion', 'accord'],
    ['hablar', 'escribir'],
    ['mini debate', 'argumentos', 'párrafo'],
  ),
  unit(
    'fr-20',
    'B1.1',
    'Médias et information',
    'Puedo identificar ideas principales en noticias claras.',
    ['discours rapporté initial', 'passif', 'titres'],
    ['leer', 'escuchar'],
    ['titular-resumen', 'idea principal', 'reporte'],
  ),
  unit(
    'fr-21',
    'B1.2',
    'Relations et émotions',
    'Puedo reaccionar a noticias y explicar sentimientos con matices básicos.',
    ['subjonctif fréquent', 'pronoms y/en', 'intensité'],
    ['interactuar', 'escuchar'],
    ['respuesta adecuada', 'reformular', 'diálogo'],
  ),
  unit(
    'fr-22',
    'B1.2',
    'Choix et conséquences',
    'Puedo comparar opciones y explicar posibles consecuencias.',
    ['si + présent/futur', 'conditionnel de politesse', 'comparaison'],
    ['hablar', 'leer'],
    ['árbol de decisión', 'recomendación', 'escenario'],
  ),
  unit(
    'fr-23',
    'B1.2',
    'Culture francophone',
    'Puedo reseñar y recomendar una obra o experiencia cultural.',
    ['relatifs dont/où', 'adjectifs évaluatifs', 'registre critique'],
    ['leer', 'escribir'],
    ['reseña', 'comparar perspectivas', 'recomendación'],
  ),
  unit(
    'fr-24',
    'B1 consolidación',
    'Projet B1',
    'Puedo investigar un tema familiar y presentar conclusiones conectadas.',
    ['integración B1', 'cohesión', 'autocorrección'],
    ['todas'],
    ['proyecto', 'preguntas', 'portafolio'],
  ),
  unit(
    'fr-25',
    'B2.1',
    'Argumenter',
    'Puedo defender una postura y responder a argumentos contrarios.',
    ['connecteurs', 'concession', 'mise en relief'],
    ['hablar', 'escribir'],
    ['debate', 'plan argumental', 'ensayo'],
  ),
  unit(
    'fr-26',
    'B2.1',
    'Comprendre l’implicite',
    'Puedo identificar postura, tono e información implícita en textos complejos.',
    ['modalisation', 'implicite', 'référence textuelle'],
    ['leer', 'escuchar'],
    ['inferencia', 'actitud', 'resumen crítico'],
  ),
  unit(
    'fr-27',
    'B2.1',
    'Parler avec aisance',
    'Puedo participar en conversaciones extensas con fluidez razonable.',
    ['marqueurs discursifs', 'enchaînement', 'prise de parole'],
    ['escuchar', 'interactuar'],
    ['shadowing', 'turnos', 'conversación abierta'],
  ),
  unit(
    'fr-28',
    'B2.1',
    'Société et débats',
    'Puedo discutir cuestiones sociales usando evidencia y ejemplos.',
    ['nominalisation', 'cause/conséquence', 'lexique abstrait'],
    ['leer', 'hablar'],
    ['síntesis', 'discusión', 'presentación'],
  ),
  unit(
    'fr-29',
    'B2.2',
    'Monde professionnel',
    'Puedo negociar y redactar comunicación profesional clara.',
    ['registre formel', 'conditionnel', 'collocations'],
    ['interactuar', 'escribir'],
    ['reunión', 'correo', 'negociación'],
  ),
  unit(
    'fr-30',
    'B2.2',
    'Médiation',
    'Puedo reformular y explicar información compleja para otras personas.',
    ['paraphrase', 'définition', 'organisation'],
    ['mediar', 'hablar'],
    ['explicar gráfica', 'síntesis cruzada', 'reformulación'],
  ),
  unit(
    'fr-31',
    'B2.2',
    'Écriture détaillée',
    'Puedo producir textos claros y detallados adaptando género y registro.',
    ['cohésion', 'subjonctif/indicatif', 'révision'],
    ['escribir', 'leer'],
    ['transformar registro', 'edición', 'texto extenso'],
  ),
  unit(
    'fr-32',
    'B2 consolidación',
    'Projet B2',
    'Puedo investigar, presentar y defender una propuesta detallada.',
    ['integración B2', 'precisión', 'autoevaluación'],
    ['todas'],
    ['proyecto final', 'defensa oral', 'portafolio'],
  ),
];

export const russianCurriculum: CurriculumUnit[] = [
  unit(
    'ru-01',
    'Pre-A1',
    'Кириллица I',
    'Puedo reconocer, escribir y pronunciar las letras cirílicas transparentes.',
    ['А Е К М О Т', 'sonido-grafía', 'trazo'],
    ['leer', 'pronunciar'],
    ['trazo guiado', 'sonido-letra', 'detección'],
  ),
  unit(
    'ru-02',
    'Pre-A1',
    'Кириллица II',
    'Puedo distinguir letras nuevas y falsos amigos gráficos.',
    ['Б В Г Д Ж З', 'Н Р С У Х', 'contraste latino'],
    ['leer', 'escribir'],
    ['pares mínimos', 'transliteración', 'dictado'],
  ),
  unit(
    'ru-03',
    'Pre-A1',
    'Sonidos y acento',
    'Puedo producir contrastes básicos y reconocer la sílaba tónica.',
    ['palatalización', 'reducción vocálica', 'acento'],
    ['escuchar', 'pronunciar'],
    ['discriminación', 'marcar acento', 'shadowing'],
  ),
  unit(
    'ru-04',
    'Pre-A1',
    'Leer palabras',
    'Puedo leer palabras breves y señales frecuentes.',
    ['alfabeto completo', 'ь/ъ', 'grupos consonánticos'],
    ['leer', 'escuchar'],
    ['construir palabra', 'señales', 'dictado'],
  ),
  unit(
    'ru-05',
    'A1.1',
    'Привет!',
    'Puedo saludar, despedirme, agradecer y disculparme.',
    ['привет/здравствуйте', 'пока/до свидания', 'registro'],
    ['escuchar', 'interactuar'],
    ['respuesta situacional', 'ordenar diálogo', 'shadowing'],
  ),
  unit(
    'ru-06',
    'A1.1',
    'О себе',
    'Puedo decir mi nombre, origen, idioma y ocupación.',
    ['это/я', 'pronombres', 'cópula cero'],
    ['hablar', 'escribir'],
    ['perfil', 'entrevista', 'transformación'],
  ),
  unit(
    'ru-07',
    'A1.1',
    'Люди и семья',
    'Puedo presentar a familiares y describir personas brevemente.',
    ['género', 'posesivos', 'nominativo'],
    ['hablar', 'leer'],
    ['árbol familiar', 'acuerdo', 'descripción'],
  ),
  unit(
    'ru-08',
    'A1.1',
    'Числа и время',
    'Puedo comprender números, edades, teléfonos y horas.',
    ['números', 'который час', 'años'],
    ['escuchar', 'leer'],
    ['sonido-número', 'reloj', 'datos'],
  ),
  unit(
    'ru-09',
    'A1.2',
    'Мой день',
    'Puedo describir acciones cotidianas en presente.',
    ['conjugaciones', 'adverbios de tiempo', 'aspecto inicial'],
    ['hablar', 'escribir'],
    ['ordenar rutina', 'conjugación', 'diario'],
  ),
  unit(
    'ru-10',
    'A1.2',
    'Где это?',
    'Puedo preguntar y decir dónde se encuentra algo.',
    ['prepositivo en в/на', 'где', 'lugares'],
    ['hablar', 'leer'],
    ['mapa', 'caso contextual', 'pregunta-respuesta'],
  ),
  unit(
    'ru-11',
    'A1.2',
    'Еда и покупки',
    'Puedo pedir productos, comprender precios y expresar gustos.',
    ['acusativo', 'хотеть/любить', 'cantidades'],
    ['interactuar', 'escuchar'],
    ['tienda', 'menú', 'clasificar'],
  ),
  unit(
    'ru-12',
    'A1 consolidación',
    'Проект: обо мне',
    'Puedo presentarme y resolver intercambios cotidianos elementales.',
    ['repaso A1', 'reparación', 'pronunciación'],
    ['todas'],
    ['misión integrada', 'presentación', 'diagnóstico A2'],
  ),
  unit(
    'ru-13',
    'A2.1',
    'Дом и город',
    'Puedo describir vivienda, barrio y servicios cercanos.',
    ['genitivo de ausencia', 'adjetivos', 'preposiciones'],
    ['hablar', 'leer'],
    ['mapa', 'descripción', 'selección de caso'],
  ),
  unit(
    'ru-14',
    'A2.1',
    'Передвижение',
    'Puedo explicar cómo me desplazo y pedir indicaciones.',
    ['verbos de movimiento básicos', 'instrumental', 'imperativo'],
    ['escuchar', 'interactuar'],
    ['ruta', 'movimiento correcto', 'anuncio'],
  ),
  unit(
    'ru-15',
    'A2.1',
    'Прошлое',
    'Puedo contar actividades pasadas y ordenar hechos.',
    ['pasado', 'aspecto inicial', 'marcadores'],
    ['hablar', 'escribir'],
    ['línea temporal', 'acuerdo', 'relato'],
  ),
  unit(
    'ru-16',
    'A2.1',
    'Планы',
    'Puedo expresar planes, intención y acuerdos próximos.',
    ['буду + infinitivo', 'собираться', 'fechas'],
    ['interactuar', 'escuchar'],
    ['calendario', 'chat', 'negociación'],
  ),
  unit(
    'ru-17',
    'A2.2',
    'Здоровье',
    'Puedo describir síntomas y comprender consejos sencillos.',
    ['dativo de estado', 'нужно/можно/нельзя', 'imperativo'],
    ['escuchar', 'hablar'],
    ['consulta', 'síntoma-consejo', 'role-play'],
  ),
  unit(
    'ru-18',
    'A2.2',
    'Experiencias y habilidades',
    'Puedo hablar de experiencias, intereses y capacidades.',
    ['уметь/мочь', 'aspecto', 'instrumental'],
    ['hablar', 'escribir'],
    ['encuesta', 'contraste modal', 'perfil'],
  ),
  unit(
    'ru-19',
    'A2.2',
    'Comunicación práctica',
    'Puedo pedir ayuda, aclarar y resolver un problema sencillo.',
    ['peticiones', 'pronombres negativos', 'genitivo'],
    ['interactuar', 'escuchar'],
    ['soporte simulado', 'reparar diálogo', 'escenario'],
  ),
  unit(
    'ru-20',
    'A2 consolidación',
    'Проект A2',
    'Puedo resolver una secuencia de tareas de vida diaria.',
    ['integración A2', 'seis casos básicos', 'aspecto'],
    ['todas'],
    ['misión integrada', 'correo', 'portafolio'],
  ),
  unit(
    'ru-21',
    'B1.1',
    'Истории',
    'Puedo narrar experiencias conectando contexto y acontecimientos.',
    ['aspecto verbal', 'movimiento con prefijos', 'secuencia'],
    ['hablar', 'escribir'],
    ['ordenar historia', 'elegir aspecto', 'narración'],
  ),
  unit(
    'ru-22',
    'B1.1',
    'Учёба и работа',
    'Puedo explicar responsabilidades, formación y metas.',
    ['participios pasivos iniciales', 'casos en régimen', 'léxico profesional'],
    ['hablar', 'leer'],
    ['entrevista', 'perfil', 'resumen'],
  ),
  unit(
    'ru-23',
    'B1.1',
    'Мнение',
    'Puedo expresar una opinión y justificarla con razones.',
    ['потому что/поэтому', 'я считаю', 'concesión básica'],
    ['hablar', 'escribir'],
    ['mini debate', 'argumentos', 'párrafo'],
  ),
  unit(
    'ru-24',
    'B1.1',
    'Новости',
    'Puedo comprender los puntos principales de noticias claras.',
    ['discurso indirecto', 'pasiva refleja', 'titulares'],
    ['leer', 'escuchar'],
    ['titular-resumen', 'idea principal', 'reporte'],
  ),
  unit(
    'ru-25',
    'B1.2',
    'Решения',
    'Puedo comparar opciones y explicar consecuencias posibles.',
    ['если', 'condicional con бы', 'comparativos'],
    ['hablar', 'leer'],
    ['árbol de decisión', 'recomendación', 'escenario'],
  ),
  unit(
    'ru-26',
    'B1.2',
    'Отношения',
    'Puedo reaccionar a noticias y manejar desacuerdos cotidianos.',
    ['emociones', 'partículas pragmáticas', 'atenuación'],
    ['interactuar', 'escuchar'],
    ['respuesta adecuada', 'entonación', 'role-play'],
  ),
  unit(
    'ru-27',
    'B1.2',
    'Культура',
    'Puedo reseñar una obra y recomendarla con razones.',
    ['relativas который', 'evaluación', 'aspecto'],
    ['leer', 'escribir'],
    ['reseña', 'recomendación', 'comparación'],
  ),
  unit(
    'ru-28',
    'B1 consolidación',
    'Проект B1',
    'Puedo investigar un tema familiar y presentar conclusiones conectadas.',
    ['integración B1', 'cohesión', 'autocorrección'],
    ['todas'],
    ['proyecto', 'preguntas', 'portafolio'],
  ),
  unit(
    'ru-29',
    'B2.1',
    'Аргументация',
    'Puedo defender una postura, matizarla y responder a objeciones.',
    ['conectores', 'concesión', 'modalización'],
    ['hablar', 'escribir'],
    ['debate', 'reescritura', 'ensayo'],
  ),
  unit(
    'ru-30',
    'B2.1',
    'Сложные тексты',
    'Puedo identificar tesis, estructura e implicaciones en textos complejos.',
    ['nominalización', 'cohesión', 'léxico abstracto'],
    ['leer', 'mediar'],
    ['mapa argumental', 'inferencia', 'resumen'],
  ),
  unit(
    'ru-31',
    'B2.1',
    'Естественная речь',
    'Puedo seguir y participar en conversaciones extensas con fluidez razonable.',
    ['partículas', 'reducción oral', 'turn-taking'],
    ['escuchar', 'interactuar'],
    ['shadowing', 'actitud', 'conversación abierta'],
  ),
  unit(
    'ru-32',
    'B2.1',
    'Общество',
    'Puedo discutir temas sociales usando evidencia y ejemplos.',
    ['fuentes y citas', 'causa-efecto', 'registro público'],
    ['leer', 'hablar'],
    ['síntesis', 'discusión', 'presentación'],
  ),
  unit(
    'ru-33',
    'B2.2',
    'Профессиональная среда',
    'Puedo participar en reuniones y redactar comunicación profesional.',
    ['registro formal', 'participios', 'colocaciones'],
    ['interactuar', 'escribir'],
    ['reunión', 'correo', 'negociación'],
  ),
  unit(
    'ru-34',
    'B2.2',
    'Медиация',
    'Puedo reformular y explicar información compleja para otra persona.',
    ['paráfrasis', 'definición', 'estructura informativa'],
    ['mediar', 'hablar'],
    ['explicar gráfica', 'síntesis cruzada', 'reformulación'],
  ),
  unit(
    'ru-35',
    'B2.2',
    'Точность и стиль',
    'Puedo adaptar estilo y registro y revisar textos detallados.',
    ['gerundios', 'participios', 'edición'],
    ['escribir', 'leer'],
    ['cambiar registro', 'corrección', 'texto extenso'],
  ),
  unit(
    'ru-36',
    'B2 consolidación',
    'Проект B2',
    'Puedo investigar, presentar y defender una propuesta detallada.',
    ['integración B2', 'precisión', 'autoevaluación'],
    ['todas'],
    ['proyecto final', 'defensa oral', 'portafolio'],
  ),
];

export const sharedExercisePrinciples = [
  'Recuperación activa antes de mostrar pistas.',
  'Variación entre reconocimiento, producción y uso comunicativo.',
  'Distractores basados en errores previsibles, no en trampas arbitrarias.',
  'Repaso espaciado: 1, 3, 7, 14 y 30 días, ajustado por desempeño.',
  'Dominio por objetivo: al menos 80% en dos intentos separados y una tarea de producción.',
  'Mezcla progresiva de contenido nuevo (60%), reciente (25%) y acumulativo (15%).',
];

/** Primeiro bloque de Português para hispanofalantes (A1). */
export const portugueseCurriculum: CurriculumUnit[] = [
  unit(
    'pt-01',
    'A1.1',
    'Sons e primeiros contatos',
    'Puedo reconocer sonidos básicos, saludar y despedirme en portugués.',
    ['alfabeto', 'ç y dígrafos', 'olá/tchau', 'cortesía'],
    ['escuchar', 'interactuar'],
    ['sonido-letra', 'respuesta situacional', 'ordenar diálogo'],
  ),
  unit(
    'pt-02',
    'A1.1',
    'Presentarme',
    'Puedo decir mi nombre, origen e idioma con frases sencillas.',
    ['ser/estar', 'chamar-se', 'de/da/do', 'pronombres'],
    ['hablar', 'escribir'],
    ['completar perfil', 'selección', 'producción guiada'],
  ),
  unit(
    'pt-03',
    'A1.1',
    'Números y datos personales',
    'Puedo decir números, edad y datos básicos en una interacción breve.',
    ['números 0–20', 'ter', 'idade', 'preguntas básicas'],
    ['escuchar', 'interactuar'],
    ['dictado de números', 'formulario', 'mini diálogo'],
  ),
  unit(
    'pt-04',
    'A1.2',
    'Familia y personas',
    'Puedo describir a mi familia y usar género y plural básicos.',
    ['família', 'artículos', 'género y plural', 'adjetivos'],
    ['leer', 'hablar'],
    ['árbol familiar', 'concordancia', 'descripción breve'],
  ),
  unit(
    'pt-05',
    'A1.2',
    'Mi rutina',
    'Puedo hablar de mi rutina diaria y decir a qué hora hago actividades.',
    ['presente', 'verbos cotidianos', 'horas', 'às/aos'],
    ['escuchar', 'hablar'],
    ['ordenar rutina', 'reloj', 'producción breve'],
  ),
  unit(
    'pt-06',
    'A1.2',
    'Comida y pedidos',
    'Puedo pedir comida y expresar preferencias sencillas.',
    ['comida', 'querer', 'gostar de', 'por favor'],
    ['interactuar', 'leer'],
    ['menú', 'diálogo', 'selección contextual'],
  ),
  unit(
    'pt-07',
    'A1.2',
    'Lugares y ubicación',
    'Puedo decir dónde están lugares comunes y preguntar cómo llegar.',
    ['há/tem', 'em/no/na', 'perguntas de lugar', 'imperativo inicial'],
    ['leer', 'interactuar'],
    ['mapa', 'completar diálogo', 'ordenar indicaciones'],
  ),
  unit(
    'pt-08',
    'A1.2',
    'Gustos y tiempo libre',
    'Puedo decir qué me gusta hacer y preguntar por las preferencias de otra persona.',
    ['gostar de', 'também/também não', 'atividades', 'perguntas'],
    ['hablar', 'escribir'],
    ['encuesta', 'respuesta breve', 'mini diálogo'],
  ),
  unit(
    'pt-09',
    'A2.1',
    'Transporte y viajes',
    'Puedo comprar un billete y explicar cómo viajo.',
    ['ir de/para', 'meios de transporte', 'bilhete', 'horarios'],
    ['leer', 'interactuar'],
    ['taquilla', 'horario', 'diálogo funcional'],
  ),
  unit(
    'pt-10',
    'A2.1',
    'Ayer y el fin de semana',
    'Puedo contar acciones recientes usando el pretérito perfeito.',
    ['pretérito perfeito', 'ontem', 'marcadores temporales'],
    ['hablar', 'escribir'],
    ['línea temporal', 'ordenar relato', 'producción breve'],
  ),
  unit(
    'pt-11',
    'A2.1',
    'Salud y clima',
    'Puedo describir un malestar sencillo y hablar del tiempo.',
    ['estar com', 'dói', 'tempo meteorológico', 'porque'],
    ['interactuar', 'escuchar'],
    ['consulta', 'pronóstico', 'respuesta causal'],
  ),
  unit(
    'pt-12',
    'A2.2',
    'Compras y preferencias',
    'Puedo preguntar precios, tallas y elegir productos.',
    ['quanto custa', 'tamanho', 'demonstrativos', 'comparativos'],
    ['leer', 'interactuar'],
    ['tienda', 'comparar', 'diálogo de compra'],
  ),
  unit('pt-13', 'A2.2', 'Casa y entorno', 'Puedo describir mi vivienda y preguntar por servicios del barrio.', ['casa', 'hay/estar', 'divisiones', 'preposiciones'], ['hablar', 'leer'], ['plano', 'descripción', 'pregunta-respuesta']),
  unit('pt-14', 'A2.2', 'Trabajo y estudios', 'Puedo hablar de mi trabajo o estudios y de mis horarios.', ['trabalhar/estudar', 'presente', 'porque', 'horarios'], ['hablar', 'escribir'], ['perfil', 'entrevista', 'producción breve']),
  unit('pt-15', 'A2.2', 'Invitaciones y planes', 'Puedo invitar a alguien, aceptar o rechazar y acordar un plan.', ['querer/poder', 'vamos', 'marcadores de tiempo', 'cortesía'], ['interactuar', 'escuchar'], ['diálogo', 'agenda', 'respuesta situacional']),
  unit('pt-16', 'A2.2', 'Experiencias personales', 'Puedo contar una experiencia pasada y expresar una reacción sencilla.', ['pretérito', 'já/ainda', 'adjetivos', 'conectores'], ['hablar', 'escribir'], ['relato breve', 'ordenar historia', 'opinión']),
  unit('pt-17', 'B1.1', 'Historias y secuencias', 'Puedo narrar un acontecimiento con contexto, acciones y resultado.', ['pretérito perfeito/imperfeito', 'quando/enquanto', 'conectores'], ['hablar', 'escribir'], ['relato', 'línea temporal', 'reformulación']),
  unit('pt-18', 'B1.1', 'Opiniones y razones', 'Puedo expresar una opinión y justificarla con ejemplos.', ['acho que', 'porque/por isso', 'concordar'], ['interactuar', 'escribir'], ['debate breve', 'argumento', 'respuesta abierta']),
  unit('pt-19', 'B1.1', 'Mensajes y comunicación digital', 'Puedo escribir mensajes claros y adaptar el registro.', ['informal/formal', 'pedidos', 'conectores'], ['leer', 'escribir'], ['mensaje', 'registro', 'respuesta funcional']),
  unit('pt-20', 'B1.2', 'Trabajo y proyectos', 'Puedo explicar una tarea, proponer una solución y acordar próximos pasos.', ['futuro próximo', 'dever/poder', 'organización'], ['interactuar', 'hablar'], ['reunión', 'plan', 'mediación']),
  unit('pt-21', 'B1.2', 'Textos y noticias', 'Puedo identificar la idea principal y detalles de textos breves.', ['títulos', 'conectores', 'inferência', 'vocabulário'], ['leer', 'escuchar'], ['idea principal', 'ordenar información', 'resumen']),
  unit('pt-22', 'B1.2', 'Problemas y soluciones', 'Puedo explicar un problema y proponer alternativas razonables.', ['deveria', 'seria melhor', 'condicional inicial', 'causa'], ['interactuar', 'escribir'], ['diagnóstico', 'propuesta', 'respuesta abierta']),
  unit('pt-23', 'B1.2', 'Cultura y comparación', 'Puedo comparar hábitos y expresar diferencias culturales con respeto.', ['mais/menos que', 'costumes', 'embora', 'relativizar'], ['hablar', 'leer'], ['comparación', 'mediación', 'opinión']),
  unit('pt-24', 'B1 consolidación', 'Proyecto de comunicación', 'Puedo preparar y presentar una propuesta breve con argumentos.', ['organización B1', 'presentación', 'conectores', 'revisión'], ['todas'], ['proyecto', 'presentación', 'autoevaluación']),
  unit('pt-25', 'B2.1', 'Argumentación formal', 'Puedo defender una posición con razones, ejemplos y matices.', ['no entanto', 'além disso', 'apesar de', 'registro formal'], ['leer', 'escribir'], ['ensayo breve', 'contraargumento', 'revisión']),
  unit('pt-26', 'B2.1', 'Mediación y síntesis', 'Puedo resumir información y explicarla a otra persona con claridad.', ['resumo', 'reformulação', 'fontes', 'conectores'], ['leer', 'hablar'], ['síntesis', 'mediación', 'explicación']),
  unit('pt-27', 'B2.2', 'Negociación profesional', 'Puedo negociar condiciones, prioridades y compromisos.', ['condicional', 'concessão', 'prioridades', 'acordo'], ['interactuar', 'hablar'], ['reunión', 'negociación', 'decisión']),
  unit('pt-28', 'B2.2', 'Presentación de propuestas', 'Puedo presentar una propuesta compleja y responder preguntas.', ['estructura discursiva', 'datos', 'responder objeciones', 'registro'], ['todas'], ['presentación', 'preguntas', 'proyecto']),
  unit('pt-29', 'B2.2', 'Precisión y registro', 'Puedo adaptar tono, precisión y cortesía a distintas situaciones.', ['formalidade', 'modalizadores', 'colocação', 'revisão'], ['leer', 'escribir'], ['reescritura', 'registro', 'edición']),
  unit('pt-30', 'B2.2', 'Informes y datos', 'Puedo describir tendencias y extraer conclusiones de información.', ['gráficos', 'tendências', 'aumento/reducción', 'conclusão'], ['leer', 'hablar'], ['gráfico', 'síntesis', 'presentación']),
  unit('pt-31', 'B2 consolidación', 'Debate y mediación avanzada', 'Puedo debatir una cuestión compleja y reformular posiciones.', ['concessão', 'contraargumento', 'reformulação', 'turnos'], ['interactuar', 'hablar'], ['debate', 'mediación', 'evaluación']),
  unit('pt-32', 'B2 consolidación', 'Proyecto final B2', 'Puedo investigar, presentar y defender una propuesta detallada.', ['integración B2', 'precisión', 'autoevaluación', 'proyecto'], ['todas'], ['proyecto final', 'defensa oral', 'portafolio']),
];
