import type { ModelLesson } from './model-lessons';

type PortugueseLesson = ModelLesson & { language: 'pt' };

const lesson = (
  id: string,
  title: string,
  level: string,
  objective: string,
  summary: string,
  concepts: PortugueseLesson['introduction']['concepts'],
  exercises: PortugueseLesson['exercises'],
  tip: string,
): PortugueseLesson => ({
  language: 'pt',
  title,
  level,
  objective,
  duration: '10–12 min',
  introduction: { summary, concepts, tip },
  exercises,
});

export const portugueseLessons: Record<string, PortugueseLesson> = {
  'pt-01': lesson(
    'pt-01',
    'Sons y primeros contactos',
    'A1.1',
    'Puedo reconocer sonidos básicos, saludar y despedirme en portugués.',
    'Aprenderás diferencias iniciales entre español y portugués y expresiones de contacto cotidiano.',
    [
      { title: 'Saludos', explanation: 'Olá es un saludo general; bom dia, boa tarde y boa noite dependen del momento.', examples: ['Olá!', 'Bom dia!'] },
      { title: 'Cortesía', explanation: 'Por favor y obrigado/obrigada aparecen en peticiones y agradecimientos.', examples: ['Por favor.', 'Obrigada!'] },
      { title: 'Despedidas', explanation: 'Tchau es informal; até logo y até amanhã indican que volverás a ver a la persona.', examples: ['Tchau!', 'Até logo!'] },
    ],
    [
      { id: 'pt-01-01', kind: 'choice', phase: 'activar', prompt: '¿Cuál significa “Buenos días”?', hint: 'Elige el saludo de la mañana.', options: ['Bom dia!', 'Boa noite!', 'Tchau!'], answer: 'Bom dia!', explanation: 'Bom dia se usa por la mañana.' },
      { id: 'pt-01-02', kind: 'choice', phase: 'comprender', prompt: 'Completa: “___, tudo bem?”', hint: 'Es un saludo general.', options: ['Olá', 'Até amanhã', 'Boa noite'], answer: 'Olá', explanation: 'Olá funciona como saludo general.' },
      { id: 'pt-01-03', kind: 'order', phase: 'practicar', prompt: 'Ordena el saludo.', hint: 'Primero saluda y después pregunta cómo está la persona.', tokens: ['bem?', 'Olá,', 'tudo'], answer: ['Olá,', 'tudo', 'bem?'], explanation: 'La expresión habitual es “Olá, tudo bem?”.' },
      { id: 'pt-01-04', kind: 'choice', phase: 'practicar', prompt: '¿Qué dices al agradecer?', hint: 'Recuerda las formas según quien habla.', options: ['Obrigado/Obrigada', 'Desculpa', 'Até logo'], answer: 'Obrigado/Obrigada', explanation: 'Obrigado lo usa un hombre y obrigada una mujer.' },
      { id: 'pt-01-05', kind: 'choice', phase: 'practicar', prompt: '¿Cuál es una despedida informal?', hint: 'Es parecida a “chao”.', options: ['Tchau!', 'Por favor!', 'Bom dia!'], answer: 'Tchau!', explanation: 'Tchau es una despedida informal muy frecuente.' },
      { id: 'pt-01-06', kind: 'order', phase: 'transferir', prompt: 'Ordena una despedida.', hint: 'Usa até logo.', tokens: ['logo!', 'Até'], answer: ['Até', 'logo!'], explanation: 'Até logo significa “hasta luego”.' },
      { id: 'pt-01-07', kind: 'open', phase: 'transferir', prompt: 'Escribe un saludo y una despedida en portugués.', hint: 'Puedes usar Olá y Tchau.', accepted: ['Olá! Tchau!', 'Olá, tchau!', 'Bom dia! Até logo!'], modelAnswer: 'Olá! Tchau!', explanation: 'La respuesta debe incluir un saludo y una despedida comprensibles.' },
      { id: 'pt-01-08', kind: 'choice', phase: 'transferir', prompt: 'Llegas por la noche. ¿Qué saludo es adecuado?', hint: 'Usa la expresión nocturna.', options: ['Boa noite!', 'Bom dia!', 'Até amanhã!'], answer: 'Boa noite!', explanation: 'Boa noite funciona como saludo por la noche.' },
    ],
    'Atiende a las vocales nasales y no supongas que una palabra parecida al español tiene siempre el mismo uso.',
  ),
  'pt-02': lesson(
    'pt-02',
    'Presentarme',
    'A1.1',
    'Puedo decir mi nombre, origen e idioma con frases sencillas.',
    'Practicarás presentaciones breves y la diferencia entre ser, estar y chamar-se.',
    [
      { title: 'Nombre', explanation: 'Me chamo y meu nome é sirven para decir cómo te llamas.', examples: ['Eu me chamo Ana.', 'Meu nome é Carlos.'] },
      { title: 'Origen', explanation: 'Sou de expresa origen o procedencia; de cambia a do/da con algunos lugares.', examples: ['Sou do México.', 'Sou de Lisboa.'] },
      { title: 'Idioma', explanation: 'Falo português expresa el idioma que hablas.', examples: ['Falo espanhol.', 'Falo português.'] },
    ],
    [
      { id: 'pt-02-01', kind: 'choice', phase: 'activar', prompt: '¿Cómo dices “Me llamo Laura”?', hint: 'Usa me chamo.', options: ['Eu me chamo Laura.', 'Eu estou Laura.', 'Eu tenho Laura.'], answer: 'Eu me chamo Laura.', explanation: 'Me chamo se usa para presentar el nombre.' },
      { id: 'pt-02-02', kind: 'choice', phase: 'comprender', prompt: 'Completa: “Eu ___ do México.”', hint: 'Expresa origen.', options: ['sou', 'estou', 'tenho'], answer: 'sou', explanation: 'Sou de/do indica origen.' },
      { id: 'pt-02-03', kind: 'order', phase: 'practicar', prompt: 'Ordena la presentación.', hint: 'Sujeto + verbo + idioma.', tokens: ['português.', 'falo', 'Eu'], answer: ['Eu', 'falo', 'português.'], explanation: '“Eu falo português” es una presentación del idioma.' },
      { id: 'pt-02-04', kind: 'choice', phase: 'practicar', prompt: '¿Qué pregunta por el nombre?', hint: 'Incluye como se chama.', options: ['Como você se chama?', 'Onde você está?', 'Quantos anos você tem?'], answer: 'Como você se chama?', explanation: 'Como você se chama? pregunta el nombre.' },
      { id: 'pt-02-05', kind: 'choice', phase: 'practicar', prompt: 'Elige la frase correcta.', hint: 'Para “Soy de Lisboa”.', options: ['Sou de Lisboa.', 'Estou de Lisboa.', 'Tenho de Lisboa.'], answer: 'Sou de Lisboa.', explanation: 'Sou de se usa con ciudades y países sin artículo.' },
      { id: 'pt-02-06', kind: 'order', phase: 'transferir', prompt: 'Ordena una presentación completa.', hint: 'Origen e idioma.', tokens: ['português.', 'Eu', 'sou', 'do Brasil.', 'e', 'falo'], answer: ['Eu', 'sou', 'do Brasil.', 'e', 'falo', 'português.'], explanation: 'Una presentación puede unir origen e idioma.' },
      { id: 'pt-02-07', kind: 'open', phase: 'transferir', prompt: 'Escribe dos frases para presentarte en portugués.', hint: 'Incluye tu nombre y tu país.', accepted: [], modelAnswer: 'Eu me chamo Ana. Sou do México.', explanation: 'Debe incluir nombre y origen en dos frases comprensibles.' },
      { id: 'pt-02-08', kind: 'choice', phase: 'transferir', prompt: '¿Qué respuesta corresponde a “Você fala espanhol?”', hint: 'Responde afirmativamente.', options: ['Sim, falo espanhol.', 'Sim, sou espanhol.', 'Sim, estou espanhol.'], answer: 'Sim, falo espanhol.', explanation: 'Falo expresa la acción de hablar un idioma.' },
    ],
    'En portugués brasileño es común omitir el pronombre, pero lo incluimos al inicio para hacer visible la estructura.',
  ),
  'pt-03': lesson(
    'pt-03',
    'Números y datos personales',
    'A1.1',
    'Puedo decir números, edad y datos básicos en una interacción breve.',
    'Usarás los números del 0 al 20 y la construcción ter para hablar de edad.',
    [
      { title: 'Números', explanation: 'Practica las formas básicas y observa que quatro y oito no coinciden con el español.', examples: ['um, dois, três', 'quatro, oito, dez'] },
      { title: 'Edad', explanation: 'En portugués se usa ter: Tenho vinte anos.', examples: ['Tenho 20 anos.', 'Quantos anos você tem?'] },
      { title: 'Datos', explanation: 'Perguntas con qual, onde y quantos ayudan a completar información personal.', examples: ['Qual é o seu telefone?', 'Onde você mora?'] },
    ],
    [
      { id: 'pt-03-01', kind: 'choice', phase: 'activar', prompt: '¿Cuál es “tres” en portugués?', hint: 'Se parece al español, pero termina en s.', options: ['três', 'treis', 'tres'], answer: 'três', explanation: 'La forma normativa es três.' },
      { id: 'pt-03-02', kind: 'choice', phase: 'comprender', prompt: 'Completa: “Tenho ___ anos.”', hint: 'Habla de edad.', options: ['vinte', 'sou', 'estou'], answer: 'vinte', explanation: 'La edad se expresa con ter + número + anos.' },
      { id: 'pt-03-03', kind: 'order', phase: 'practicar', prompt: 'Ordena la pregunta por edad.', hint: 'Pregunta cuántos años tiene la persona.', tokens: ['tem?', 'anos', 'Quantos', 'você'], answer: ['Quantos', 'anos', 'você', 'tem?'], explanation: 'La pregunta habitual es “Quantos anos você tem?”.' },
      { id: 'pt-03-04', kind: 'choice', phase: 'practicar', prompt: '¿Cómo dices “ocho”?', hint: 'Lleva oi.', options: ['oito', 'ocho', 'oitcho'], answer: 'oito', explanation: 'Oito significa ocho.' },
      { id: 'pt-03-05', kind: 'choice', phase: 'practicar', prompt: '¿Qué pregunta por el teléfono?', hint: 'Usa telefone.', options: ['Qual é o seu telefone?', 'Onde é o seu telefone?', 'Quem é o seu telefone?'], answer: 'Qual é o seu telefone?', explanation: 'Qual pergunta cuál es el dato.' },
      { id: 'pt-03-06', kind: 'order', phase: 'transferir', prompt: 'Ordena la respuesta.', hint: 'Usa tengo + número + años.', tokens: ['anos.', 'Tenho', 'vinte', 'e', 'cinco'], answer: ['Tenho', 'vinte', 'e', 'cinco', 'anos.'], explanation: 'La edad se construye con Tenho ... anos.' },
      { id: 'pt-03-07', kind: 'open', phase: 'transferir', prompt: 'Escribe tu edad en portugués.', hint: 'Usa Tenho ... anos.', accepted: [], modelAnswer: 'Tenho vinte e cinco anos.', explanation: 'Debe aparecer tenho, un número y anos.' },
      { id: 'pt-03-08', kind: 'choice', phase: 'transferir', prompt: '¿Qué significa “Onde você mora?”', hint: 'Pregunta por un lugar.', options: ['¿Dónde vives?', '¿Cuántos años tienes?', '¿Qué idioma hablas?'], answer: '¿Dónde vives?', explanation: 'Onde pregunta por el lugar.' },
    ],
    'Memoriza los números en grupos pequeños y pronúncialos en voz alta antes de escribirlos.',
  ),
  'pt-04': lesson(
    'pt-04',
    'Familia y personas',
    'A1.2',
    'Puedo describir a mi familia y usar género y plural básicos.',
    'Aprenderás vocabulario familiar y concordancia elemental de artículos y adjetivos.',
    [
      { title: 'Familia', explanation: 'Pai, mãe, irmão y irmã son palabras frecuentes para hablar de la familia.', examples: ['meu pai', 'minha irmã'] },
      { title: 'Artículos y género', explanation: 'O/a y um/uma concuerdan con el sustantivo.', examples: ['uma irmã', 'um irmão'] },
      { title: 'Descripción', explanation: 'El adjetivo suele concordar en género y número.', examples: ['Ela é simpática.', 'Eles são altos.'] },
    ],
    [
      { id: 'pt-04-01', kind: 'choice', phase: 'activar', prompt: '¿Cómo dices “mi madre”?', hint: 'Mãe es femenino.', options: ['minha mãe', 'meu mãe', 'minhas mãe'], answer: 'minha mãe', explanation: 'Minha concuerda con el sustantivo femenino mãe.' },
      { id: 'pt-04-02', kind: 'choice', phase: 'comprender', prompt: 'Elige el artículo correcto: ___ irmão.', hint: 'Irmão es masculino singular.', options: ['um', 'uma', 'umas'], answer: 'um', explanation: 'Um se usa con masculinos singulares.' },
      { id: 'pt-04-03', kind: 'order', phase: 'practicar', prompt: 'Ordena la descripción.', hint: 'Sujeto + ser + adjetivo.', tokens: ['simpática.', 'Ela', 'é'], answer: ['Ela', 'é', 'simpática.'], explanation: 'Ela é simpática describe a una mujer.' },
      { id: 'pt-04-04', kind: 'choice', phase: 'practicar', prompt: 'Completa: “Meus irmãos ___ altos.”', hint: 'Plural de ser.', options: ['são', 'é', 'está'], answer: 'são', explanation: 'São concuerda con un sujeto plural.' },
      { id: 'pt-04-05', kind: 'choice', phase: 'practicar', prompt: '¿Cuál es “hermana”?', hint: 'Termina en -ã.', options: ['irmã', 'irmão', 'prima'], answer: 'irmã', explanation: 'Irmã significa hermana; irmão significa hermano.' },
      { id: 'pt-04-06', kind: 'order', phase: 'transferir', prompt: 'Ordena la frase posesiva.', hint: 'Mi + hermano.', tokens: ['irmão.', 'meu'], answer: ['meu', 'irmão.'], explanation: 'Meu concuerda con irmão.' },
      { id: 'pt-04-07', kind: 'open', phase: 'transferir', prompt: 'Escribe una frase sobre una persona de tu familia.', hint: 'Usa meu/minha y una descripción.', accepted: [], modelAnswer: 'Minha irmã é simpática.', explanation: 'Debe incluir una relación familiar y una descripción comprensible.' },
      { id: 'pt-04-08', kind: 'choice', phase: 'transferir', prompt: '¿Qué opción tiene concordancia correcta?', hint: 'Mira género y número.', options: ['minhas irmãs', 'meu irmãs', 'minha irmãos'], answer: 'minhas irmãs', explanation: 'Posesivo y sustantivo están en femenino plural.' },
    ],
    'No traduzcas meu/minha palabra por palabra: el posesivo debe concordar con la cosa poseída.',
  ),
  'pt-05': lesson(
    'pt-05', 'Mi rutina', 'A1.2',
    'Puedo hablar de mi rutina diaria y decir a qué hora hago actividades.',
    'Practicarás el presente y expresiones de hora para describir un día normal.',
    [
      { title: 'Rutina', explanation: 'Verbos como acordar, trabalhar, estudar y dormir describen acciones habituales.', examples: ['Eu estudo de manhã.', 'Eu durmo cedo.'] },
      { title: 'Hora', explanation: 'Usa às para horas y ao meio-dia para el mediodía.', examples: ['Às oito horas.', 'Ao meio-dia.'] },
    ],
    [
      { id: 'pt-05-01', kind: 'choice', phase: 'activar', prompt: '¿Cuál significa “estudio por la mañana”?', hint: 'Busca estudo y de manhã.', options: ['Eu estudo de manhã.', 'Eu estou manhã.', 'Eu durmo de manhã.'], answer: 'Eu estudo de manhã.', explanation: 'Estudo expresa estudiar y de manhã indica el momento.' },
      { id: 'pt-05-02', kind: 'choice', phase: 'comprender', prompt: 'Completa: “Eu acordo ___ sete horas.”', hint: 'Preposición delante de una hora.', options: ['às', 'em', 'de'], answer: 'às', explanation: 'Às se usa con horas plurales.' },
      { id: 'pt-05-03', kind: 'order', phase: 'practicar', prompt: 'Ordena la frase.', hint: 'Sujeto + verbo + momento.', tokens: ['cedo.', 'Eu', 'durmo'], answer: ['Eu', 'durmo', 'cedo.'], explanation: 'Eu durmo cedo significa “duermo temprano”.' },
      { id: 'pt-05-04', kind: 'choice', phase: 'practicar', prompt: '¿Qué haces “à noite”?', hint: 'Es el momento nocturno.', options: ['Duermo à noite.', 'Almoço à noite.', 'Acordo à noite siempre.'], answer: 'Duermo à noite.', explanation: 'À noite significa por la noche.' },
      { id: 'pt-05-05', kind: 'choice', phase: 'practicar', prompt: 'Elige la hora correcta: 8:00.', hint: 'Usa oito.', options: ['às oito horas', 'às oito anos', 'em oito horas'], answer: 'às oito horas', explanation: 'Horas usa horas, no anos.' },
      { id: 'pt-05-06', kind: 'order', phase: 'transferir', prompt: 'Ordena una rutina.', hint: 'Primero despertar, después trabajar.', tokens: ['trabalho.', 'Acordo', 'e', 'depois'], answer: ['Acordo', 'e', 'depois', 'trabalho.'], explanation: 'Depois conecta la segunda acción.' },
      { id: 'pt-05-07', kind: 'open', phase: 'transferir', prompt: 'Escribe una frase sobre tu rutina y una hora.', hint: 'Usa Eu ... às ... horas.', accepted: [], modelAnswer: 'Eu estudo às oito horas.', explanation: 'Debe incluir una acción cotidiana y una hora.' },
      { id: 'pt-05-08', kind: 'choice', phase: 'transferir', prompt: '¿Cuál es una rutina comprensible?', hint: 'Revisa verbo y momento.', options: ['Eu trabalho de manhã.', 'Eu trabalho de manhã horas.', 'Eu trabalho sou manhã.'], answer: 'Eu trabalho de manhã.', explanation: 'La frase combina verbo y expresión temporal correctamente.' },
    ],
    'La preposición se contrae en expresiones fijas de tiempo: às oito, ao meio-dia.',
  ),
  'pt-06': lesson(
    'pt-06', 'Comida y pedidos', 'A1.2',
    'Puedo pedir comida y expresar preferencias sencillas.',
    'Aprenderás a pedir algo con cortesía y a decir qué te gusta comer.',
    [
      { title: 'Pedir', explanation: 'Quero y gostaria de introducen pedidos; por favor suaviza la petición.', examples: ['Quero água, por favor.', 'Gostaria de um café.'] },
      { title: 'Gustos', explanation: 'Gosto de se usa para expresar preferencias.', examples: ['Gosto de arroz.', 'Não gosto de peixe.'] },
    ],
    [
      { id: 'pt-06-01', kind: 'choice', phase: 'activar', prompt: '¿Cómo pides agua?', hint: 'Usa quero y por favor.', options: ['Quero água, por favor.', 'Sou água, por favor.', 'Tenho água, por favor.'], answer: 'Quero água, por favor.', explanation: 'Quero expresa lo que deseas pedir.' },
      { id: 'pt-06-02', kind: 'choice', phase: 'comprender', prompt: 'Completa: “Eu gosto ___ café.”', hint: 'Gosto necesita una preposición.', options: ['de', 'em', 'a'], answer: 'de', explanation: 'La construcción es gostar de.' },
      { id: 'pt-06-03', kind: 'order', phase: 'practicar', prompt: 'Ordena el pedido.', hint: 'Pedido + cortesía.', tokens: ['favor.', 'Quero', 'por', 'um café,'], answer: ['Quero', 'um café,', 'por', 'favor.'], explanation: 'Quero um café, por favor es una petición natural.' },
      { id: 'pt-06-04', kind: 'choice', phase: 'practicar', prompt: '¿Qué significa “Não gosto de peixe”?', hint: 'Busca la negación.', options: ['No me gusta el pescado.', 'Quiero pescado.', 'Tengo pescado.'], answer: 'No me gusta el pescado.', explanation: 'Não niega la preferencia.' },
      { id: 'pt-06-05', kind: 'choice', phase: 'practicar', prompt: 'En un restaurante, ¿qué opción es cortés?', hint: 'Usa gostaria de.', options: ['Gostaria de uma sopa.', 'Sou uma sopa.', 'Tenho uma sopa agora.'], answer: 'Gostaria de uma sopa.', explanation: 'Gostaria de formula un pedido cortés.' },
      { id: 'pt-06-06', kind: 'order', phase: 'transferir', prompt: 'Ordena una preferencia negativa.', hint: 'Negación + gostar de.', tokens: ['carne.', 'Não', 'gosto', 'de'], answer: ['Não', 'gosto', 'de', 'carne.'], explanation: 'Não gosto de carne expresa una preferencia negativa.' },
      { id: 'pt-06-07', kind: 'open', phase: 'transferir', prompt: 'Escribe un pedido de comida en portugués.', hint: 'Usa Quero o Gostaria de y por favor.', accepted: [], modelAnswer: 'Gostaria de um café, por favor.', explanation: 'Debe contener un alimento o bebida y una fórmula de pedido.' },
      { id: 'pt-06-08', kind: 'choice', phase: 'transferir', prompt: '¿Cuál pregunta por una preferencia?', hint: 'Busca gosta.', options: ['Você gosta de arroz?', 'Você é arroz?', 'Você tem arroz?'], answer: 'Você gosta de arroz?', explanation: 'Gostar de pregunta por gustos.' },
    ],
    'Gosto de lleva de delante del alimento: no lo calques como gostar algo.',
  ),
  'pt-07': lesson(
    'pt-07', 'Lugares y ubicación', 'A1.2',
    'Puedo decir dónde están lugares comunes y preguntar cómo llegar.',
    'Practicarás hay, ubicación y preguntas sencillas para orientarte.',
    [
      { title: 'Hay', explanation: 'Há presenta existencia o disponibilidad.', examples: ['Há um banco aqui.', 'Há uma farmácia perto.'] },
      { title: 'Ubicación', explanation: 'Em se combina con artículos: no masculino y na femenino.', examples: ['no centro', 'na praça'] },
    ],
    [
      { id: 'pt-07-01', kind: 'choice', phase: 'activar', prompt: '¿Cómo dices “Hay una farmacia”?', hint: 'Usa há y uma.', options: ['Há uma farmácia.', 'É uma farmácia.', 'Tem uma farmácia? no'], answer: 'Há uma farmácia.', explanation: 'Há introduce existencia.' },
      { id: 'pt-07-02', kind: 'choice', phase: 'comprender', prompt: 'Completa: “O banco fica ___ centro.”', hint: 'Em + o se contraen.', options: ['no', 'na', 'de'], answer: 'no', explanation: 'No es la contracción de em + o.' },
      { id: 'pt-07-03', kind: 'order', phase: 'practicar', prompt: 'Ordena la pregunta.', hint: 'Pregunta cómo llegar al centro.', tokens: ['chegar', 'Como', 'ao centro?'], answer: ['Como', 'chegar', 'ao centro?'], explanation: 'Como chegar ao centro? pregunta cómo llegar.' },
      { id: 'pt-07-04', kind: 'choice', phase: 'practicar', prompt: '¿Dónde está la plaza?', hint: 'Plaza es praça y es femenino.', options: ['na praça', 'no praça', 'em praça'], answer: 'na praça', explanation: 'Na es em + a.' },
      { id: 'pt-07-05', kind: 'choice', phase: 'practicar', prompt: '¿Qué significa perto?', hint: 'Es lo contrario de lejos.', options: ['cerca', 'detrás', 'encima'], answer: 'cerca', explanation: 'Perto significa cerca.' },
      { id: 'pt-07-06', kind: 'order', phase: 'transferir', prompt: 'Ordena una indicación.', hint: 'Imperativo + dirección.', tokens: ['direita.', 'Vire', 'à'], answer: ['Vire', 'à', 'direita.'], explanation: 'Vire à direita significa gira a la derecha.' },
      { id: 'pt-07-07', kind: 'open', phase: 'transferir', prompt: 'Escribe dónde hay un lugar en tu ciudad.', hint: 'Usa Há um/uma ... perto.', accepted: [], modelAnswer: 'Há uma farmácia perto.', explanation: 'Debe incluir existencia, un lugar y una ubicación.' },
      { id: 'pt-07-08', kind: 'choice', phase: 'transferir', prompt: '¿Qué pregunta por la ubicación?', hint: 'Usa onde.', options: ['Onde fica o hotel?', 'Como é o hotel?', 'Quando fica o hotel?'], answer: 'Onde fica o hotel?', explanation: 'Onde fica pregunta dónde está algo.' },
    ],
    'Aprende las contracciones como bloques: em + o = no, em + a = na, a + o = ao.',
  ),
  'pt-08': lesson(
    'pt-08', 'Gustos y tiempo libre', 'A1.2',
    'Puedo decir qué me gusta hacer y preguntar por las preferencias de otra persona.',
    'Cerrarás el bloque hablando de actividades y coincidencias de gustos.',
    [
      { title: 'Actividades', explanation: 'Ler, ouvir música, dançar y viajar son actividades frecuentes.', examples: ['Gosto de ler.', 'Gosto de viajar.'] },
      { title: 'Coincidencias', explanation: 'Também confirma un gusto compartido; eu também não comparte una negación.', examples: ['Eu também.', 'Eu também não.'] },
    ],
    [
      { id: 'pt-08-01', kind: 'choice', phase: 'activar', prompt: '¿Cómo dices “Me gusta leer”?', hint: 'Usa gosto de + infinitivo.', options: ['Gosto de ler.', 'Gosto ler.', 'Sou ler.'], answer: 'Gosto de ler.', explanation: 'Gosto de se mantiene delante del infinitivo.' },
      { id: 'pt-08-02', kind: 'choice', phase: 'comprender', prompt: 'Completa: “Você gosta ___ viajar?”', hint: 'Gosta necesita de.', options: ['de', 'em', 'por'], answer: 'de', explanation: 'La estructura es gostar de.' },
      { id: 'pt-08-03', kind: 'order', phase: 'practicar', prompt: 'Ordena la pregunta.', hint: 'Pregunta si le gusta la música.', tokens: ['música?', 'Você', 'gosta', 'de'], answer: ['Você', 'gosta', 'de', 'música?'], explanation: 'Você gosta de música? pregunta por el gusto.' },
      { id: 'pt-08-04', kind: 'choice', phase: 'practicar', prompt: 'Alguien dice “Gosto de cinema”. ¿Qué respondes para coincidir?', hint: 'También.', options: ['Eu também.', 'Eu também não.', 'Eu sou.'], answer: 'Eu também.', explanation: 'Eu também confirma el mismo gusto.' },
      { id: 'pt-08-05', kind: 'choice', phase: 'practicar', prompt: '¿Qué actividad es ouvir música?', hint: 'Escucha el verbo.', options: ['escuchar música', 'leer música', 'comer música'], answer: 'escuchar música', explanation: 'Ouvir significa escuchar.' },
      { id: 'pt-08-06', kind: 'order', phase: 'transferir', prompt: 'Ordena una respuesta negativa.', hint: 'No me gusta bailar.', tokens: ['dançar.', 'Não', 'gosto', 'de'], answer: ['Não', 'gosto', 'de', 'dançar.'], explanation: 'La negación va delante de gosto.' },
      { id: 'pt-08-07', kind: 'open', phase: 'transferir', prompt: 'Escribe una actividad que te guste hacer.', hint: 'Usa Gosto de + infinitivo.', accepted: [], modelAnswer: 'Gosto de ouvir música.', explanation: 'Debe incluir gosto de y una actividad.' },
      { id: 'pt-08-08', kind: 'choice', phase: 'transferir', prompt: '¿Qué pregunta es correcta?', hint: 'Gosta de + actividad.', options: ['Você gosta de dançar?', 'Você gosta dançar?', 'Você é dançar?'], answer: 'Você gosta de dançar?', explanation: 'La preposición de es obligatoria en esta estructura.' },
    ],
    'En esta etapa importa comunicar la preferencia; la fluidez llegará con repaso y producción repetida.',
  ),
  'pt-09': lesson('pt-09', 'Transporte y viajes', 'A2.1', 'Puedo comprar un billete y explicar cómo viajo.', 'Aprenderás a moverte por una ciudad y pedir información de transporte.', [
    { title: 'Transporte', explanation: 'Vou de ônibus/de comboio y vou para Lisboa indican medio y destino.', examples: ['Vou de metrô.', 'Vou para o Porto.'] },
    { title: 'Billetes', explanation: 'Um bilhete de ida e volta sirve para pedir un viaje de ida y regreso.', examples: ['Um bilhete, por favor.', 'Quanto custa?'] },
  ], [
    { id: 'pt-09-01', kind: 'choice', phase: 'activar', prompt: '¿Cómo dices “Voy en metro”?', hint: 'Usa vou de.', options: ['Vou de metrô.', 'Sou metrô.', 'Vou metrô para.'], answer: 'Vou de metrô.', explanation: 'De introduce el medio de transporte.' },
    { id: 'pt-09-02', kind: 'choice', phase: 'comprender', prompt: 'Completa: “Um bilhete ___ Lisboa.”', hint: 'Destino con para.', options: ['para', 'de', 'em'], answer: 'para', explanation: 'Para introduce el destino.' },
    { id: 'pt-09-03', kind: 'order', phase: 'practicar', prompt: 'Ordena el pedido.', hint: 'Cantidad + tipo + cortesía.', tokens: ['favor.', 'Um', 'bilhete,', 'por'], answer: ['Um', 'bilhete,', 'por', 'favor.'], explanation: 'Es una petición cortés de billete.' },
    { id: 'pt-09-04', kind: 'choice', phase: 'practicar', prompt: '¿Qué pregunta por el precio?', hint: 'Usa custa.', options: ['Quanto custa?', 'Onde custa?', 'Quem custa?'], answer: 'Quanto custa?', explanation: 'Quanto custa pregunta cuánto vale.' },
    { id: 'pt-09-05', kind: 'choice', phase: 'practicar', prompt: '¿Qué significa ida e volta?', hint: 'Piensa en dos trayectos.', options: ['ida y vuelta', 'solo ida', 'sin billete'], answer: 'ida y vuelta', explanation: 'Ida e volta incluye ambos trayectos.' },
    { id: 'pt-09-06', kind: 'order', phase: 'transferir', prompt: 'Ordena una pregunta de horario.', hint: 'Pregunta cuándo sale el tren.', tokens: ['parte?', 'Quando', 'o comboio'], answer: ['Quando', 'parte', 'o comboio?'], acceptedOrders: [['Quando', 'parte', 'o comboio?']], explanation: 'Quando parte o comboio? pregunta la hora de salida.' },
    { id: 'pt-09-07', kind: 'open', phase: 'transferir', prompt: 'Pide un billete a una ciudad.', hint: 'Usa Um bilhete para ..., por favor.', accepted: [], modelAnswer: 'Um bilhete para Lisboa, por favor.', explanation: 'Debe incluir billete, destino y cortesía.' },
    { id: 'pt-09-08', kind: 'choice', phase: 'transferir', prompt: '¿Cuál es una respuesta adecuada a “Como você vai?”', hint: 'Medio de transporte.', options: ['Vou de autocarro.', 'Sou autocarro.', 'Tenho autocarro para.'], answer: 'Vou de autocarro.', explanation: 'Vou de + transporte describe cómo viajas.' },
  ], 'En Brasil se usa ônibus y en Portugal autocarro; ambas variantes se conservarán como válidas.'),
  'pt-10': lesson('pt-10', 'Ayer y el fin de semana', 'A2.1', 'Puedo contar acciones recientes usando el pretérito perfeito.', 'Practicarás acciones terminadas y marcadores como ontem y no sábado.', [
    { title: 'Pretérito perfeito', explanation: 'Falei, comi y visitei expresan acciones terminadas.', examples: ['Eu visitei o museu.', 'Nós comemos fora.'] },
    { title: 'Tiempo pasado', explanation: 'Ontem, no sábado y na semana passada sitúan la acción.', examples: ['Ontem trabalhei.', 'No sábado viajei.'] },
  ], [
    { id: 'pt-10-01', kind: 'choice', phase: 'activar', prompt: '¿Cuál significa “Ayer trabajé”?', hint: 'Usa trabalhei.', options: ['Ontem trabalhei.', 'Ontem trabalho.', 'Ontem trabalhar.'], answer: 'Ontem trabalhei.', explanation: 'Trabalhei es el pretérito de trabalhar para eu.' },
    { id: 'pt-10-02', kind: 'choice', phase: 'comprender', prompt: 'Completa: “No sábado ___ um filme.”', hint: 'Ver en pasado.', options: ['vi', 'vejo', 'ver'], answer: 'vi', explanation: 'Vi es el pasado de ver.' },
    { id: 'pt-10-03', kind: 'order', phase: 'practicar', prompt: 'Ordena el relato.', hint: 'Marcador + verbo + actividad.', tokens: ['museu.', 'visitei', 'Ontem', 'o'], answer: ['Ontem', 'visitei', 'o', 'museu.'], explanation: 'Ontem visitei o museu narra una acción terminada.' },
    { id: 'pt-10-04', kind: 'choice', phase: 'practicar', prompt: '¿Qué forma es pasado?', hint: 'Terminación de eu.', options: ['comi', 'como', 'comer'], answer: 'comi', explanation: 'Comi es el pretérito de comer.' },
    { id: 'pt-10-05', kind: 'choice', phase: 'practicar', prompt: '¿Qué significa na semana passada?', hint: 'Es tiempo anterior.', options: ['la semana pasada', 'la próxima semana', 'cada semana'], answer: 'la semana pasada', explanation: 'Passada indica que ya terminó.' },
    { id: 'pt-10-06', kind: 'order', phase: 'transferir', prompt: 'Ordena una frase en pasado.', hint: 'Sujeto + verbo + lugar.', tokens: ['praia.', 'Nós', 'fomos', 'à'], answer: ['Nós', 'fomos', 'à', 'praia.'], explanation: 'Fomos es la forma pasada de ir para nós.' },
    { id: 'pt-10-07', kind: 'open', phase: 'transferir', prompt: 'Escribe una acción que hiciste ayer.', hint: 'Empieza con Ontem y usa pasado.', accepted: [], modelAnswer: 'Ontem visitei um amigo.', explanation: 'Debe incluir un marcador pasado y un verbo terminado.' },
    { id: 'pt-10-08', kind: 'choice', phase: 'transferir', prompt: '¿Cuál cuenta una experiencia pasada?', hint: 'Busca el verbo terminado.', options: ['No domingo cozinhei.', 'No domingo cozinho amanhã.', 'No domingo cozinhar.'], answer: 'No domingo cozinhei.', explanation: 'Cozinhei sitúa la acción en el pasado.' },
  ], 'No traduzcas mecánicamente el pretérito español: aprende cada forma frecuente como una unidad y luego observa sus patrones.'),
  'pt-11': lesson('pt-11', 'Salud y clima', 'A2.1', 'Puedo describir un malestar sencillo y hablar del tiempo.', 'Aprenderás a decir qué te duele, cómo te sientes y qué tiempo hace.', [
    { title: 'Malestar', explanation: 'Estou com dor de... y dói introducen síntomas sencillos.', examples: ['Estou com dor de cabeça.', 'A garganta dói.'] },
    { title: 'Clima', explanation: 'Está calor/frio y está a chover describen el tiempo.', examples: ['Está frio.', 'Está a chover.'] },
  ], [
    { id: 'pt-11-01', kind: 'choice', phase: 'activar', prompt: '¿Cómo dices “Me duele la cabeza”?', hint: 'Usa estou com dor de.', options: ['Estou com dor de cabeça.', 'Sou dor de cabeça.', 'Tenho cabeça dor.'], answer: 'Estou com dor de cabeça.', explanation: 'A dor de cabeça es dolor de cabeza.' },
    { id: 'pt-11-02', kind: 'choice', phase: 'comprender', prompt: 'Completa: “Hoje está ___.”', hint: 'Hace frío.', options: ['frio', 'dor', 'chuva'], answer: 'frio', explanation: 'Está frio describe temperatura.' },
    { id: 'pt-11-03', kind: 'order', phase: 'practicar', prompt: 'Ordena la frase del clima.', hint: 'Está + lloviendo.', tokens: ['chover.', 'Está', 'a'], answer: ['Está', 'a', 'chover.'], explanation: 'En Portugal, está a chover es una forma habitual.' },
    { id: 'pt-11-04', kind: 'choice', phase: 'practicar', prompt: '¿Qué significa tosse?', hint: 'Síntoma.', options: ['tos', 'fiebre', 'dolor'], answer: 'tos', explanation: 'Tosse significa tos.' },
    { id: 'pt-11-05', kind: 'choice', phase: 'practicar', prompt: '¿Qué pregunta por el estado de salud?', hint: 'Usa está se sentindo.', options: ['Como você está se sentindo?', 'Onde você está sentindo?', 'Quando você saúde?'], answer: 'Como você está se sentindo?', explanation: 'Pregunta cómo se siente la persona.' },
    { id: 'pt-11-06', kind: 'order', phase: 'transferir', prompt: 'Ordena un consejo.', hint: 'Imperativo y agua.', tokens: ['água.', 'Beba', 'muita'], answer: ['Beba', 'muita', 'água.'], explanation: 'Beba muita água es un consejo comprensible.' },
    { id: 'pt-11-07', kind: 'open', phase: 'transferir', prompt: 'Describe el clima de hoy.', hint: 'Usa Está ... o Está a ...', accepted: [], modelAnswer: 'Hoje está frio e a chover.', explanation: 'Debe incluir una expresión meteorológica.' },
    { id: 'pt-11-08', kind: 'choice', phase: 'transferir', prompt: '¿Qué respuesta corresponde a “Está calor?”', hint: 'Confirma o niega el clima.', options: ['Sim, está muito calor.', 'Sim, sou calor.', 'Sim, tenho calor clima.'], answer: 'Sim, está muito calor.', explanation: 'Está calor describe la temperatura ambiental.' },
  ], 'El vocabulario de salud no sustituye consejo médico; aquí solo se practica comunicación básica.'),
  'pt-12': lesson('pt-12', 'Compras y preferencias', 'A2.2', 'Puedo preguntar precios, tallas y elegir productos.', 'Practicarás interacciones de compra y comparaciones sencillas.', [
    { title: 'Precio y talla', explanation: 'Quanto custa? y que tamanho? resuelven necesidades en una tienda.', examples: ['Quanto custa esta camisa?', 'Que tamanho é?'] },
    { title: 'Comparar', explanation: 'Mais barato, maior y menor permiten elegir entre productos.', examples: ['Este é mais barato.', 'Quero o maior.'] },
  ], [
    { id: 'pt-12-01', kind: 'choice', phase: 'activar', prompt: '¿Cómo preguntas el precio?', hint: 'Usa quanto custa.', options: ['Quanto custa esta camisa?', 'Quanto é camisa custa?', 'Onde custa camisa?'], answer: 'Quanto custa esta camisa?', explanation: 'Quanto custa pregunta por el precio.' },
    { id: 'pt-12-02', kind: 'choice', phase: 'comprender', prompt: '¿Qué significa tamanho?', hint: 'Se relaciona con ropa.', options: ['talla', 'color', 'precio'], answer: 'talla', explanation: 'Tamanho es talla o tamaño.' },
    { id: 'pt-12-03', kind: 'order', phase: 'practicar', prompt: 'Ordena la elección.', hint: 'Quiero esta camisa.', tokens: ['camisa.', 'Quero', 'esta'], answer: ['Quero', 'esta', 'camisa.'], explanation: 'Esta concuerda con camisa.' },
    { id: 'pt-12-04', kind: 'choice', phase: 'practicar', prompt: '¿Cuál es más barato?', hint: 'Compara precios.', options: ['Este é mais barato.', 'Este é mais barato preço.', 'Este sou barato.'], answer: 'Este é mais barato.', explanation: 'Mais barato forma el comparativo.' },
    { id: 'pt-12-05', kind: 'choice', phase: 'practicar', prompt: '¿Qué significa experimentar?', hint: 'Acción en una tienda.', options: ['probarse', 'pagar', 'vender'], answer: 'probarse', explanation: 'Experimentar ropa es probársela.' },
    { id: 'pt-12-06', kind: 'order', phase: 'transferir', prompt: 'Ordena una petición de talla.', hint: 'Pregunta si hay una talla mayor.', tokens: ['maior?', 'Tem', 'um', 'tamanho'], answer: ['Tem', 'um', 'tamanho', 'maior?'], explanation: 'Tem um tamanho maior? pregunta si existe una talla más grande.' },
    { id: 'pt-12-07', kind: 'open', phase: 'transferir', prompt: 'Escribe una pregunta de compra.', hint: 'Pregunta precio o talla.', accepted: [], modelAnswer: 'Quanto custa esta camisa?', explanation: 'Debe incluir un producto y una pregunta útil.' },
    { id: 'pt-12-08', kind: 'choice', phase: 'transferir', prompt: '¿Qué opción expresa una elección?', hint: 'Quero + demostrativo.', options: ['Quero aquele casaco.', 'Sou aquele casaco.', 'Tenho aquele comprar.'], answer: 'Quero aquele casaco.', explanation: 'Aquele señala un objeto más alejado.' },
  ], 'Las formas este/esta y aquele/aquela deben concordar con el género del sustantivo.'),
  'pt-13': lesson('pt-13', 'Casa y entorno', 'A2.2', 'Puedo describir mi vivienda y preguntar por servicios del barrio.', 'Describirás habitaciones y dirás qué hay cerca de casa.', [
    { title: 'Vivienda', explanation: 'Sala, quarto, cozinha y casa describen espacios cotidianos.', examples: ['A casa tem dois quartos.', 'A cozinha é pequena.'] },
    { title: 'Entorno', explanation: 'Há y fica ayudan a localizar servicios y lugares.', examples: ['Há um mercado perto.', 'A escola fica ao lado.'] },
  ], [
    { id: 'pt-13-01', kind: 'choice', phase: 'activar', prompt: '¿Cómo dices “La casa tiene dos habitaciones”?', hint: 'Usa tem.', options: ['A casa tem dois quartos.', 'A casa é dois quartos.', 'A casa está dois quartos.'], answer: 'A casa tem dois quartos.', explanation: 'Tem expresa que la casa posee o contiene espacios.' },
    { id: 'pt-13-02', kind: 'choice', phase: 'comprender', prompt: 'Completa: “A cozinha ___ pequena.”', hint: 'Estado o característica.', options: ['é', 'tem', 'há'], answer: 'é', explanation: 'É enlaza sujeto y característica.' },
    { id: 'pt-13-03', kind: 'order', phase: 'practicar', prompt: 'Ordena la ubicación.', hint: 'Hay un mercado cerca.', tokens: ['perto.', 'Há', 'um mercado'], answer: ['Há', 'um mercado', 'perto.'], explanation: 'Há um mercado perto indica existencia y proximidad.' },
    { id: 'pt-13-04', kind: 'choice', phase: 'practicar', prompt: '¿Qué significa ao lado?', hint: 'Indica posición.', options: ['al lado', 'lejos', 'dentro'], answer: 'al lado', explanation: 'Ao lado significa al lado.' },
    { id: 'pt-13-05', kind: 'choice', phase: 'practicar', prompt: '¿Cuál describe correctamente una habitación?', hint: 'Artículo y sustantivo.', options: ['um quarto grande', 'uma quarto grande', 'um quartos grande'], answer: 'um quarto grande', explanation: 'Quarto es masculino singular.' },
    { id: 'pt-13-06', kind: 'order', phase: 'transferir', prompt: 'Ordena una pregunta del barrio.', hint: 'Pregunta si hay una farmacia.', tokens: ['perto?', 'Há', 'uma farmácia'], answer: ['Há', 'uma farmácia', 'perto?'], explanation: 'La pregunta busca un servicio cercano.' },
    { id: 'pt-13-07', kind: 'open', phase: 'transferir', prompt: 'Describe una habitación de tu casa.', hint: 'Usa A ... é y un adjetivo.', accepted: [], modelAnswer: 'A sala é grande e confortável.', explanation: 'Debe nombrar una habitación y describirla.' },
    { id: 'pt-13-08', kind: 'choice', phase: 'transferir', prompt: '¿Qué frase localiza una escuela?', hint: 'Usa fica.', options: ['A escola fica perto.', 'A escola tem perto.', 'A escola é fica.'], answer: 'A escola fica perto.', explanation: 'Fica localiza un lugar.' },
  ], 'Distingue há (existencia) de fica (ubicación concreta).'),
  'pt-14': lesson('pt-14', 'Trabajo y estudios', 'A2.2', 'Puedo hablar de mi trabajo o estudios y de mis horarios.', 'Practicarás perfiles cotidianos y preguntas sobre ocupación.', [
    { title: 'Ocupación', explanation: 'Trabalho como... y estudo... presentan actividad laboral o académica.', examples: ['Trabalho como enfermeira.', 'Estudo engenharia.'] },
    { title: 'Motivo', explanation: 'Porque introduce una explicación sencilla.', examples: ['Estudo português porque gosto.', 'Trabalho porque preciso.'] },
  ], [
    { id: 'pt-14-01', kind: 'choice', phase: 'activar', prompt: '¿Cómo dices “Estudio medicina”?', hint: 'Usa estudo.', options: ['Estudo medicina.', 'Sou medicina.', 'Tenho medicina.'], answer: 'Estudo medicina.', explanation: 'Estudo presenta el área académica.' },
    { id: 'pt-14-02', kind: 'choice', phase: 'comprender', prompt: 'Completa: “Trabalho ___ professor.”', hint: 'Profesión con como.', options: ['como', 'de', 'em'], answer: 'como', explanation: 'Trabalho como + profesión.' },
    { id: 'pt-14-03', kind: 'order', phase: 'practicar', prompt: 'Ordena la pregunta.', hint: 'Pregunta qué estudia alguien.', tokens: ['estuda?', 'O que', 'você'], answer: ['O que', 'você', 'estuda?'], explanation: 'O que você estuda? pregunta por los estudios.' },
    { id: 'pt-14-04', kind: 'choice', phase: 'practicar', prompt: '¿Qué significa horário?', hint: 'Se relaciona con el tiempo.', options: ['horario', 'oficina', 'salario'], answer: 'horario', explanation: 'Horário es horario.' },
    { id: 'pt-14-05', kind: 'choice', phase: 'practicar', prompt: 'Completa: “Estudo português ___ gosto de línguas.”', hint: 'Conector de causa o explicación.', options: ['porque', 'mas', 'ou'], answer: 'porque', explanation: 'Porque introduce la razón.' },
    { id: 'pt-14-06', kind: 'order', phase: 'transferir', prompt: 'Ordena una presentación laboral.', hint: 'Trabajo + profesión.', tokens: ['hospital.', 'Trabalho', 'num'], answer: ['Trabalho', 'num', 'hospital.'], explanation: 'Num es la contracción de em + um.' },
    { id: 'pt-14-07', kind: 'open', phase: 'transferir', prompt: 'Escribe dos frases sobre trabajo o estudios.', hint: 'Usa estudo/trabalho y un horario.', accepted: [], modelAnswer: 'Estudo à tarde e trabalho de manhã.', explanation: 'Debe incluir actividad y un momento del día.' },
    { id: 'pt-14-08', kind: 'choice', phase: 'transferir', prompt: '¿Qué pregunta por la profesión?', hint: 'Usa faz.', options: ['O que você faz?', 'O que você é faz?', 'Onde você faz profissão?'], answer: 'O que você faz?', explanation: 'O que você faz? pregunta a qué te dedicas.' },
  ], 'Los nombres de profesiones pueden cambiar por género: professor/professora, enfermeiro/enfermeira.'),
  'pt-15': lesson('pt-15', 'Invitaciones y planes', 'A2.2', 'Puedo invitar a alguien, aceptar o rechazar y acordar un plan.', 'Practicarás propuestas y respuestas corteses en situaciones cotidianas.', [
    { title: 'Invitar', explanation: 'Você quer...? y Vamos... proponen actividades.', examples: ['Você quer ir ao cinema?', 'Vamos jantar?'] },
    { title: 'Responder', explanation: 'Aceitar o rechazar con una razón mantiene la interacción clara.', examples: ['Claro, vamos!', 'Desculpa, não posso.'] },
  ], [
    { id: 'pt-15-01', kind: 'choice', phase: 'activar', prompt: '¿Cómo invitas al cine?', hint: 'Usa quer ir.', options: ['Você quer ir ao cinema?', 'Você é ir cinema?', 'Você tem cinema quer?'], answer: 'Você quer ir ao cinema?', explanation: 'Quer ir formula una invitación.' },
    { id: 'pt-15-02', kind: 'choice', phase: 'comprender', prompt: '¿Cuál acepta una invitación?', hint: 'Respuesta positiva.', options: ['Claro, vamos!', 'Não posso hoje.', 'Talvez amanhã.'], answer: 'Claro, vamos!', explanation: 'Claro, vamos confirma el plan.' },
    { id: 'pt-15-03', kind: 'order', phase: 'practicar', prompt: 'Ordena la propuesta.', hint: 'Vamos + actividad.', tokens: ['jantar?', 'Vamos'], answer: ['Vamos', 'jantar?'], explanation: 'Vamos jantar? propone cenar.' },
    { id: 'pt-15-04', kind: 'choice', phase: 'practicar', prompt: 'Completa: “Desculpa, não ___ hoje.”', hint: 'Poder en primera persona.', options: ['posso', 'pode', 'podem'], answer: 'posso', explanation: 'Posso es la forma de eu de poder.' },
    { id: 'pt-15-05', kind: 'choice', phase: 'practicar', prompt: '¿Qué expresión pregunta por el día?', hint: 'Usa quando.', options: ['Quando nos encontramos?', 'Onde nos encontramos?', 'Quem nos encontramos?'], answer: 'Quando nos encontramos?', explanation: 'Quando pregunta cuándo.' },
    { id: 'pt-15-06', kind: 'order', phase: 'transferir', prompt: 'Ordena un plan completo.', hint: 'Actividad + día.', tokens: ['sábado.', 'no', 'Encontramo-nos'], answer: ['Encontramo-nos', 'no', 'sábado.'], explanation: 'La frase acuerda un encuentro.' },
    { id: 'pt-15-07', kind: 'open', phase: 'transferir', prompt: 'Escribe una invitación breve.', hint: 'Usa Você quer...? o Vamos...?', accepted: [], modelAnswer: 'Você quer tomar um café?', explanation: 'Debe contener una propuesta comprensible.' },
    { id: 'pt-15-08', kind: 'choice', phase: 'transferir', prompt: '¿Qué rechazo es cortés?', hint: 'Incluye disculpa y motivo.', options: ['Desculpa, não posso hoje.', 'Não! Vai embora.', 'Eu não querer.'], answer: 'Desculpa, não posso hoje.', explanation: 'La disculpa y el motivo suavizan el rechazo.' },
  ], 'En conversación real, una respuesta negativa puede incluir una alternativa: talvez amanhã.'),
  'pt-16': lesson('pt-16', 'Experiencias personales', 'A2.2', 'Puedo contar una experiencia pasada y expresar una reacción sencilla.', 'Cerrarás el bloque organizando un relato breve con conectores.', [
    { title: 'Relato', explanation: 'Primeiro, depois y finalmente ordenan hechos pasados.', examples: ['Primeiro cheguei.', 'Depois visitei o museu.'] },
    { title: 'Reacción', explanation: 'Foi interessante, divertido o cansativo expresa una valoración.', examples: ['Foi muito interessante.', 'Foi cansativo.'] },
  ], [
    { id: 'pt-16-01', kind: 'choice', phase: 'activar', prompt: '¿Qué conector significa “después”?', hint: 'Orden temporal.', options: ['depois', 'porque', 'também'], answer: 'depois', explanation: 'Depois ordena la acción posterior.' },
    { id: 'pt-16-02', kind: 'choice', phase: 'comprender', prompt: 'Completa: “A viagem ___ divertida.”', hint: 'Ser en pasado.', options: ['foi', 'é', 'era'], answer: 'foi', explanation: 'Foi presenta una valoración terminada.' },
    { id: 'pt-16-03', kind: 'order', phase: 'practicar', prompt: 'Ordena el relato.', hint: 'Primero llegar, después visitar.', tokens: ['cheguei.', 'Primeiro', 'Depois', 'visitei'], answer: ['Primeiro', 'cheguei.', 'Depois', 'visitei'], explanation: 'Los conectores organizan dos acciones.' },
    { id: 'pt-16-04', kind: 'choice', phase: 'practicar', prompt: '¿Qué significa cansativo?', hint: 'Describe una experiencia.', options: ['cansado/cansador', 'barato', 'rápido'], answer: 'cansado/cansador', explanation: 'Cansativo describe algo agotador.' },
    { id: 'pt-16-05', kind: 'choice', phase: 'practicar', prompt: '¿Cuál es una reacción positiva?', hint: 'Busca interesante.', options: ['Foi muito interessante.', 'Foi nada interessante nunca.', 'Foi não ser.'], answer: 'Foi muito interessante.', explanation: 'La frase valora positivamente la experiencia.' },
    { id: 'pt-16-06', kind: 'order', phase: 'transferir', prompt: 'Ordena el cierre.', hint: 'Finalmente + acción pasada.', tokens: ['casa.', 'Finalmente', 'voltei', 'para'], answer: ['Finalmente', 'voltei', 'para', 'casa.'], explanation: 'Finalmente cierra la secuencia.' },
    { id: 'pt-16-07', kind: 'open', phase: 'transferir', prompt: 'Cuenta una experiencia en dos frases.', hint: 'Usa depois/finalmente y una reacción.', accepted: [], modelAnswer: 'Visitei o museu. Foi muito interessante.', explanation: 'Debe contar una acción pasada y valorarla.' },
    { id: 'pt-16-08', kind: 'choice', phase: 'transferir', prompt: '¿Qué frase está mejor organizada?', hint: 'Conector antes de la segunda acción.', options: ['Primeiro cheguei, depois saí.', 'Depois primeiro cheguei saí.', 'Cheguei depois primeiro.'], answer: 'Primeiro cheguei, depois saí.', explanation: 'Los conectores ordenan el relato.' },
  ], 'Un relato breve necesita una secuencia clara; no hace falta usar tiempos avanzados todavía.'),
  'pt-17': lesson('pt-17', 'Historias y secuencias', 'B1.1', 'Puedo narrar un acontecimiento con contexto, acciones y resultado.', 'Combinarás imperfecto para el contexto y perfecto para acciones terminadas.', [
    { title: 'Contexto', explanation: 'Era, estava y fazia describen el fondo de una historia.', examples: ['Era tarde.', 'Chovia muito.'] },
    { title: 'Acción', explanation: 'Cheguei, vi y aconteceu avanzan la narración.', examples: ['Quando cheguei, começou a chover.'] },
  ], [
    { id: 'pt-17-01', kind: 'choice', phase: 'activar', prompt: '¿Qué forma presenta el contexto?', hint: 'Descripción en progreso.', options: ['Estava cansado.', 'Fiquei cansado.', 'Cansar.'], answer: 'Estava cansado.', explanation: 'Estava describe el estado de fondo.' },
    { id: 'pt-17-02', kind: 'choice', phase: 'comprender', prompt: 'Completa: “Quando eu ___, ele ligou.”', hint: 'Llegar en pasado.', options: ['cheguei', 'chegava sempre', 'chegar'], answer: 'cheguei', explanation: 'Cheguei presenta la acción puntual.' },
    { id: 'pt-17-03', kind: 'order', phase: 'practicar', prompt: 'Ordena la narración.', hint: 'Contexto, después acción.', tokens: ['cheguei.', 'Chovia', 'quando', 'eu'], answer: ['Chovia', 'quando', 'eu', 'cheguei.'], explanation: 'El imperfecto enmarca la llegada.' },
    { id: 'pt-17-04', kind: 'choice', phase: 'practicar', prompt: '¿Qué significa enquanto?', hint: 'Dos acciones simultáneas.', options: ['mientras', 'después', 'aunque'], answer: 'mientras', explanation: 'Enquanto introduce simultaneidad.' },
    { id: 'pt-17-05', kind: 'choice', phase: 'practicar', prompt: 'Elige el resultado.', hint: 'Acción terminada.', options: ['Perdi o autocarro.', 'Perdia o autocarro todos os dias.', 'Perder o autocarro.'], answer: 'Perdi o autocarro.', explanation: 'Perdi narra un hecho puntual.' },
    { id: 'pt-17-06', kind: 'order', phase: 'transferir', prompt: 'Ordena contexto y resultado.', hint: 'Primero contexto, luego resultado.', tokens: ['cedo.', 'Estava', 'cansado,', 'por isso', 'dormi'], answer: ['Estava', 'cansado,', 'por isso', 'dormi', 'cedo.'], explanation: 'Por isso conecta causa y resultado.' },
    { id: 'pt-17-07', kind: 'open', phase: 'transferir', prompt: 'Escribe dos frases de una historia pasada.', hint: 'Incluye contexto y una acción.', accepted: [], modelAnswer: 'Estava a chover quando cheguei a casa.', explanation: 'Debe combinar contexto y acción pasada.' },
    { id: 'pt-17-08', kind: 'choice', phase: 'transferir', prompt: '¿Qué relato tiene secuencia clara?', hint: 'Observa los conectores.', options: ['Primeiro saí, depois voltei.', 'Depois primeiro saí voltei.', 'Saí primeiro depois sem verbo.'], answer: 'Primeiro saí, depois voltei.', explanation: 'Los conectores ordenan la narración.' },
  ], 'El contraste de tiempos se afina con contexto; no se reduce a una traducción palabra por palabra.'),
  'pt-18': lesson('pt-18', 'Opiniones y razones', 'B1.1', 'Puedo expresar una opinión y justificarla con ejemplos.', 'Aprenderás a matizar una opinión y conectar razones.', [
    { title: 'Opinión', explanation: 'Acho que y na minha opinião introducen una postura.', examples: ['Acho que é importante.', 'Na minha opinião, é útil.'] },
    { title: 'Justificar', explanation: 'Porque explica y por isso presenta una consecuencia.', examples: ['Gosto porque é prático.', 'É caro, por isso espero.'] },
  ], [
    { id: 'pt-18-01', kind: 'choice', phase: 'activar', prompt: '¿Cómo introduces una opinión?', hint: 'Usa acho que.', options: ['Acho que é importante.', 'Sou que importante.', 'Tenho que opinião.'], answer: 'Acho que é importante.', explanation: 'Acho que introduce una opinión.' },
    { id: 'pt-18-02', kind: 'choice', phase: 'comprender', prompt: 'Completa: “Gosto desta solução ___ é simples.”', hint: 'Razón.', options: ['porque', 'por isso', 'mas'], answer: 'porque', explanation: 'Porque introduce la razón.' },
    { id: 'pt-18-03', kind: 'order', phase: 'practicar', prompt: 'Ordena opinión y razón.', hint: 'Primero opinión, luego porque.', tokens: ['barato.', 'Acho', 'que', 'é'], answer: ['Acho', 'que', 'é', 'barato.'], explanation: 'La estructura es acho que + oración.' },
    { id: 'pt-18-04', kind: 'choice', phase: 'practicar', prompt: '¿Qué expresa consecuencia?', hint: 'Por eso.', options: ['por isso', 'porque', 'embora'], answer: 'por isso', explanation: 'Por isso introduce el resultado.' },
    { id: 'pt-18-05', kind: 'choice', phase: 'practicar', prompt: '¿Cuál suaviza el desacuerdo?', hint: 'Cortesía conversacional.', options: ['Entendo, mas penso diferente.', 'Você está errado!', 'Não!'], answer: 'Entendo, mas penso diferente.', explanation: 'Reconoce a la otra persona y matiza.' },
    { id: 'pt-18-06', kind: 'order', phase: 'transferir', prompt: 'Ordena un argumento.', hint: 'Opinión + razón + resultado.', tokens: ['útil', 'Acho', 'que', 'é', 'porque', 'ajuda.'], answer: ['Acho', 'que', 'é', 'útil', 'porque', 'ajuda.'], explanation: 'Una razón sostiene la opinión.' },
    { id: 'pt-18-07', kind: 'open', phase: 'transferir', prompt: 'Escribe tu opinión sobre estudiar idiomas y una razón.', hint: 'Usa Acho que ... porque ...', accepted: [], modelAnswer: 'Acho que estudar idiomas é útil porque ajuda a comunicar.', explanation: 'Debe incluir opinión y justificación.' },
    { id: 'pt-18-08', kind: 'choice', phase: 'transferir', prompt: '¿Qué frase añade un ejemplo?', hint: 'Por exemplo.', options: ['Por exemplo, podemos praticar juntos.', 'Por exemplo é opinião.', 'Exemplo porque juntos.'], answer: 'Por exemplo, podemos praticar juntos.', explanation: 'Por exemplo introduce un caso concreto.' },
  ], 'En B1 una opinión gana claridad cuando incluye razón, ejemplo o consecuencia.'),
  'pt-19': lesson('pt-19', 'Mensajes y comunicación digital', 'B1.1', 'Puedo escribir mensajes claros y adaptar el registro.', 'Compararás mensajes informales y formales para pedir o confirmar información.', [
    { title: 'Registro', explanation: 'Olá y Oi pueden ser informales; Prezado/Exma. Senhora son más formales.', examples: ['Oi, Ana!', 'Bom dia, Senhor Silva.'] },
    { title: 'Claridad', explanation: 'Un mensaje útil incluye motivo, petición y cierre.', examples: ['Escrevo para confirmar...', 'Obrigado pela atenção.'] },
  ], [
    { id: 'pt-19-01', kind: 'choice', phase: 'activar', prompt: '¿Qué saludo es informal?', hint: 'Mensaje a un amigo.', options: ['Oi, João!', 'Exmo. Senhor João,', 'A quem possa interessar,'], answer: 'Oi, João!', explanation: 'Oi es un saludo informal.' },
    { id: 'pt-19-02', kind: 'choice', phase: 'comprender', prompt: 'Completa: “Escrevo ___ confirmar a reunião.”', hint: 'Motivo del mensaje.', options: ['para', 'por isso', 'embora'], answer: 'para', explanation: 'Escrevo para + infinitivo presenta el propósito.' },
    { id: 'pt-19-03', kind: 'order', phase: 'practicar', prompt: 'Ordena el cierre.', hint: 'Agradece y despídete.', tokens: ['atenção.', 'Obrigado', 'pela'], answer: ['Obrigado', 'pela', 'atenção.'], explanation: 'Es un cierre formal breve.' },
    { id: 'pt-19-04', kind: 'choice', phase: 'practicar', prompt: '¿Qué petición es más formal?', hint: 'Use poderia.', options: ['Poderia enviar o documento?', 'Manda o documento!', 'Envia já!'], answer: 'Poderia enviar o documento?', explanation: 'Poderia suaviza la petición.' },
    { id: 'pt-19-05', kind: 'choice', phase: 'practicar', prompt: '¿Qué significa anexo?', hint: 'Aparece en correos.', options: ['archivo adjunto', 'asunto', 'contraseña'], answer: 'archivo adjunto', explanation: 'Anexo es un archivo adjunto.' },
    { id: 'pt-19-06', kind: 'order', phase: 'transferir', prompt: 'Ordena un mensaje.', hint: 'Saludo, motivo y petición.', tokens: ['reunião?', 'Olá,', 'podemos', 'confirmar', 'a'], answer: ['Olá,', 'podemos', 'confirmar', 'a', 'reunião?'], explanation: 'El mensaje va directo y es comprensible.' },
    { id: 'pt-19-07', kind: 'open', phase: 'transferir', prompt: 'Escribe un mensaje para confirmar una cita.', hint: 'Incluye saludo y confirmación.', accepted: [], modelAnswer: 'Olá, escrevo para confirmar a reunião de amanhã.', explanation: 'Debe adaptar el registro y comunicar el propósito.' },
    { id: 'pt-19-08', kind: 'choice', phase: 'transferir', prompt: '¿Qué cierre es formal?', hint: 'Correo profesional.', options: ['Atenciosamente,', 'Beijos!', 'Até logo, amigo!'], answer: 'Atenciosamente,', explanation: 'Atenciosamente es un cierre formal.' },
  ], 'El registro depende de la relación y del canal; no existe una única frase correcta para todo contexto.'),
  'pt-20': lesson('pt-20', 'Trabajo y proyectos', 'B1.2', 'Puedo explicar una tarea, proponer una solución y acordar próximos pasos.', 'Practicarás lenguaje de coordinación y planes próximos.', [
    { title: 'Proponer', explanation: 'Podemos y vamos a permiten sugerir acciones.', examples: ['Podemos rever o plano.', 'Vamos a começar amanhã.'] },
    { title: 'Acordar', explanation: 'Então combinamos y fica decidido cierran acuerdos.', examples: ['Então combinamos às dez.', 'Fica decidido.'] },
  ], [
    { id: 'pt-20-01', kind: 'choice', phase: 'activar', prompt: '¿Cómo propones una acción?', hint: 'Usa podemos.', options: ['Podemos rever o plano.', 'Somos rever o plano.', 'Temos rever o plano.'], answer: 'Podemos rever o plano.', explanation: 'Podemos propone una posibilidad.' },
    { id: 'pt-20-02', kind: 'choice', phase: 'comprender', prompt: 'Completa: “Vamos ___ começar amanhã.”', hint: 'Ir + a + infinitivo.', options: ['a', 'de', 'em'], answer: 'a', explanation: 'Vamos a + infinitivo expresa plan próximo.' },
    { id: 'pt-20-03', kind: 'order', phase: 'practicar', prompt: 'Ordena la propuesta.', hint: 'Podemos + revisar + objeto.', tokens: ['o plano.', 'Podemos', 'rever'], answer: ['Podemos', 'rever', 'o plano.'], explanation: 'La propuesta es clara y accionable.' },
    { id: 'pt-20-04', kind: 'choice', phase: 'practicar', prompt: '¿Qué significa prazo?', hint: 'En un proyecto.', options: ['plazo', 'problema', 'precio'], answer: 'plazo', explanation: 'Prazo es el plazo disponible.' },
    { id: 'pt-20-05', kind: 'choice', phase: 'practicar', prompt: '¿Qué frase acuerda un horario?', hint: 'Combinamos.', options: ['Combinamos às dez.', 'Somos às dez.', 'Temos dez combinar.'], answer: 'Combinamos às dez.', explanation: 'Combinamos confirma el acuerdo.' },
    { id: 'pt-20-06', kind: 'order', phase: 'transferir', prompt: 'Ordena próximos pasos.', hint: 'Primero revisar, después enviar.', tokens: ['enviar.', 'Depois', 'vamos', 'rever', 'e'], answer: ['Depois', 'vamos', 'rever', 'e', 'enviar.'], explanation: 'La secuencia organiza el trabajo.' },
    { id: 'pt-20-07', kind: 'open', phase: 'transferir', prompt: 'Propón una solución para un proyecto.', hint: 'Usa Podemos ... porque ...', accepted: [], modelAnswer: 'Podemos mudar o plano porque é mais simples.', explanation: 'Debe contener propuesta y razón.' },
    { id: 'pt-20-08', kind: 'choice', phase: 'transferir', prompt: '¿Qué cierre confirma el acuerdo?', hint: 'Decisión final.', options: ['Fica decidido.', 'Talvez nunca.', 'Não sei projeto.'], answer: 'Fica decidido.', explanation: 'Fica decidido confirma el acuerdo.' },
  ], 'Las tareas B1 deben conectar acciones y razones, no solo nombrar vocabulario.'),
  'pt-21': lesson('pt-21', 'Textos y noticias', 'B1.2', 'Puedo identificar la idea principal y detalles de textos breves.', 'Trabajarás estrategias para comprender titulares, conectores y resúmenes.', [
    { title: 'Idea principal', explanation: 'O título y la primera frase suelen orientar el tema.', examples: ['Uma nova medida foi anunciada.', 'O texto fala de transporte.'] },
    { title: 'Conectores', explanation: 'No entanto contrasta; por isso presenta consecuencia.', examples: ['Choveu; no entanto, saímos.', 'Por isso, o evento mudou.'] },
  ], [
    { id: 'pt-21-01', kind: 'choice', phase: 'activar', prompt: '¿Qué ayuda a predecir el tema?', hint: 'Está al comienzo de la noticia.', options: ['O título', 'La última coma', 'Una palabra aislada'], answer: 'O título', explanation: 'El título orienta sobre el contenido.' },
    { id: 'pt-21-02', kind: 'choice', phase: 'comprender', prompt: 'Completa: “Choveu; ___, o evento aconteceu.”', hint: 'Contraste.', options: ['no entanto', 'por isso', 'porque'], answer: 'no entanto', explanation: 'No entanto introduce contraste.' },
    { id: 'pt-21-03', kind: 'order', phase: 'practicar', prompt: 'Ordena el resumen.', hint: 'Tema y consecuencia.', tokens: ['mudou.', 'O evento', 'por isso'], answer: ['O evento', 'mudou', 'por isso.'], acceptedOrders: [['Por isso,', 'o evento', 'mudou.']], explanation: 'Un resumen conserva la idea principal y su resultado.' },
    { id: 'pt-21-04', kind: 'choice', phase: 'practicar', prompt: '¿Qué significa principal?', hint: 'Idea más importante.', options: ['principal', 'secundario', 'antiguo'], answer: 'principal', explanation: 'Principal indica lo más importante.' },
    { id: 'pt-21-05', kind: 'choice', phase: 'practicar', prompt: '¿Qué conector presenta consecuencia?', hint: 'Resultado.', options: ['por isso', 'no entanto', 'embora'], answer: 'por isso', explanation: 'Por isso presenta una consecuencia.' },
    { id: 'pt-21-06', kind: 'order', phase: 'transferir', prompt: 'Ordena un resumen claro.', hint: 'Primero tema, luego detalle.', tokens: ['sobre', 'O texto', 'fala', 'educação.'], answer: ['O texto', 'fala', 'sobre', 'educação.'], explanation: 'La estructura resume el tema del texto.' },
    { id: 'pt-21-07', kind: 'open', phase: 'transferir', prompt: 'Escribe un resumen de una noticia en una frase.', hint: 'Usa O texto fala de... y un tema.', accepted: [], modelAnswer: 'O texto fala de uma nova medida de transporte.', explanation: 'Debe identificar claramente el tema.' },
    { id: 'pt-21-08', kind: 'choice', phase: 'transferir', prompt: '¿Qué estrategia ayuda si no conoces una palabra?', hint: 'Usa el contexto.', options: ['Inferir por el contexto.', 'Parar siempre.', 'Traducir cada coma.'], answer: 'Inferir por el contexto.', explanation: 'El contexto ayuda a comprender sin traducir todo.' },
  ], 'No necesitas entender cada palabra para identificar la idea principal.'),
  'pt-22': lesson('pt-22', 'Problemas y soluciones', 'B1.2', 'Puedo explicar un problema y proponer alternativas razonables.', 'Practicarás sugerencias, consecuencias y lenguaje de solución.', [
    { title: 'Sugerir', explanation: 'Deveria y seria melhor introducen recomendaciones.', examples: ['Deveria falar com ela.', 'Seria melhor esperar.'] },
    { title: 'Causa', explanation: 'Como y porque explican un problema.', examples: ['Atrasou porque choveu.', 'Como está tarde, vamos sair.'] },
  ], [
    { id: 'pt-22-01', kind: 'choice', phase: 'activar', prompt: '¿Qué frase da un consejo?', hint: 'Usa deveria.', options: ['Deveria descansar.', 'Descanso ontem.', 'Sou descanso.'], answer: 'Deveria descansar.', explanation: 'Deveria expresa recomendación.' },
    { id: 'pt-22-02', kind: 'choice', phase: 'comprender', prompt: 'Completa: “Seria melhor ___ amanhã.”', hint: 'Infinitivo.', options: ['tentar', 'tentamos', 'tentado'], answer: 'tentar', explanation: 'Seria melhor + infinitivo sugiere una alternativa.' },
    { id: 'pt-22-03', kind: 'order', phase: 'practicar', prompt: 'Ordena problema y causa.', hint: 'Resultado, después porque.', tokens: ['atrasou', 'porque', 'choveu.'], answer: ['Atrasou', 'porque', 'choveu.'], explanation: 'Porque conecta problema y causa.' },
    { id: 'pt-22-04', kind: 'choice', phase: 'practicar', prompt: '¿Qué significa solução?', hint: 'Respuesta al problema.', options: ['solución', 'situación', 'selección'], answer: 'solución', explanation: 'Solução es solución.' },
    { id: 'pt-22-05', kind: 'choice', phase: 'practicar', prompt: '¿Cuál propone una alternativa?', hint: 'Otra posibilidad.', options: ['Podemos tentar outra opção.', 'Não há nada.', 'Problema opção sem verbo.'], answer: 'Podemos tentar outra opção.', explanation: 'Podemos tentar presenta una alternativa.' },
    { id: 'pt-22-06', kind: 'order', phase: 'transferir', prompt: 'Ordena una propuesta.', hint: 'Problema + solución.', tokens: ['um plano.', 'Deveríamos', 'fazer'], answer: ['Deveríamos', 'fazer', 'um plano.'], explanation: 'Deveríamos hace la propuesta más prudente.' },
    { id: 'pt-22-07', kind: 'open', phase: 'transferir', prompt: 'Explica un problema y propone una solución.', hint: 'Usa porque y deveríamos.', accepted: [], modelAnswer: 'Está tarde porque choveu; deveríamos esperar.', explanation: 'Debe incluir problema, causa y recomendación.' },
    { id: 'pt-22-08', kind: 'choice', phase: 'transferir', prompt: '¿Qué respuesta coopera?', hint: 'Reconoce y propone.', options: ['Entendo. Podemos procurar outra solução.', 'Não é problema meu.', 'Você sempre erra.'], answer: 'Entendo. Podemos procurar outra solução.', explanation: 'La respuesta mantiene una interacción colaborativa.' },
  ], 'Una buena solución explica por qué es adecuada y deja claro el siguiente paso.'),
  'pt-23': lesson('pt-23', 'Cultura y comparación', 'B1.2', 'Puedo comparar hábitos y expresar diferencias culturales con respeto.', 'Compararás costumbres sin convertir una diferencia en un juicio absoluto.', [
    { title: 'Comparar', explanation: 'Mais... do que y menos... do que expresan diferencias.', examples: ['É mais comum do que aqui.', 'É menos formal do que antes.'] },
    { title: 'Matizar', explanation: 'Em alguns lugares y depende de relativizan una afirmación.', examples: ['Depende da região.', 'Em alguns lugares, sim.'] },
  ], [
    { id: 'pt-23-01', kind: 'choice', phase: 'activar', prompt: '¿Cómo dices “más común que”?', hint: 'Comparativo.', options: ['mais comum do que', 'mais comum de que', 'muito comum que'], answer: 'mais comum do que', explanation: 'La estructura es mais + adjetivo + do que.' },
    { id: 'pt-23-02', kind: 'choice', phase: 'comprender', prompt: 'Completa: “Depende ___ região.”', hint: 'De + a.', options: ['da', 'do', 'de'], answer: 'da', explanation: 'Da es la contracción de de + a.' },
    { id: 'pt-23-03', kind: 'order', phase: 'practicar', prompt: 'Ordena la comparación.', hint: 'Costumbre + comparativo.', tokens: ['do que', 'aqui.', 'É mais comum'], answer: ['É mais comum', 'do que', 'aqui.'], explanation: 'Compara frecuencia de una costumbre.' },
    { id: 'pt-23-04', kind: 'choice', phase: 'practicar', prompt: '¿Qué expresión matiza una generalización?', hint: 'No todos los lugares.', options: ['em alguns lugares', 'sempre em todo lugar', 'nunca'], answer: 'em alguns lugares', explanation: 'Matiza la afirmación cultural.' },
    { id: 'pt-23-05', kind: 'choice', phase: 'practicar', prompt: '¿Qué respuesta es respetuosa?', hint: 'Reconoce diversidad.', options: ['É diferente, mas interessante.', 'É errado sempre.', 'Ninguém faz isso.'], answer: 'É diferente, mas interessante.', explanation: 'Describe sin juzgar.' },
    { id: 'pt-23-06', kind: 'order', phase: 'transferir', prompt: 'Ordena una comparación matizada.', hint: 'Depende de la región.', tokens: ['região.', 'Depende', 'da'], answer: ['Depende', 'da', 'região.'], explanation: 'Depende da região evita una generalización.' },
    { id: 'pt-23-07', kind: 'open', phase: 'transferir', prompt: 'Compara un hábito de dos lugares con respeto.', hint: 'Usa mais/menos do que y depende.', accepted: [], modelAnswer: 'Depende da região, mas é mais comum aqui do que lá.', explanation: 'Debe comparar y matizar.' },
    { id: 'pt-23-08', kind: 'choice', phase: 'transferir', prompt: '¿Qué palabra introduce contraste?', hint: 'Pero.', options: ['mas', 'porque', 'também'], answer: 'mas', explanation: 'Mas introduce contraste.' },
  ], 'Las comparaciones culturales deben describir tendencias, no presentar estereotipos como hechos universales.'),
  'pt-24': lesson('pt-24', 'Proyecto de comunicación', 'B1 consolidación', 'Puedo preparar y presentar una propuesta breve con argumentos.', 'Integrarás organización, razones, registro y próximos pasos en una tarea final.', [
    { title: 'Estructura', explanation: 'Una propuesta presenta situación, objetivo, solución y acción siguiente.', examples: ['O problema é...', 'A proposta é...', 'O próximo passo é...'] },
    { title: 'Revisión', explanation: 'Revisa conectores, concordancia y claridad antes de presentar.', examples: ['por isso', 'no entanto', 'finalmente'] },
  ], [
    { id: 'pt-24-01', kind: 'choice', phase: 'activar', prompt: '¿Qué parte presenta el problema?', hint: 'O problema...', options: ['O problema é...', 'Finalmente...', 'Obrigado pela atenção.'], answer: 'O problema é...', explanation: 'Presenta la situación inicial.' },
    { id: 'pt-24-02', kind: 'choice', phase: 'comprender', prompt: '¿Qué parte presenta la solución?', hint: 'A proposta...', options: ['A proposta é...', 'Ontem foi...', 'Até logo...'], answer: 'A proposta é...', explanation: 'Presenta la idea que se propone.' },
    { id: 'pt-24-03', kind: 'order', phase: 'practicar', prompt: 'Ordena una mini propuesta.', hint: 'Problema, solución y siguiente paso.', tokens: ['amanhã.', 'O problema é', 'a comunicação.', 'A proposta é', 'uma reunião.', 'O próximo passo é'], answer: ['O problema é', 'a comunicação.', 'A proposta é', 'uma reunião.', 'O próximo passo é', 'amanhã.'], explanation: 'La secuencia hace la propuesta comprensible.' },
    { id: 'pt-24-04', kind: 'choice', phase: 'practicar', prompt: '¿Qué conector organiza el cierre?', hint: 'Finalmente.', options: ['finalmente', 'embora', 'talvez'], answer: 'finalmente', explanation: 'Finalmente introduce el cierre.' },
    { id: 'pt-24-05', kind: 'choice', phase: 'practicar', prompt: '¿Qué revisas antes de presentar?', hint: 'Calidad del mensaje.', options: ['claridad y conectores', 'solo la primera palabra', 'nada'], answer: 'claridad y conectores', explanation: 'La revisión mejora comprensión y cohesión.' },
    { id: 'pt-24-06', kind: 'order', phase: 'transferir', prompt: 'Ordena la conclusión.', hint: 'Por eso + propuesta.', tokens: ['proponho', 'Por isso,', 'esta solução.'], answer: ['Por isso,', 'proponho', 'esta solução.'], explanation: 'Por isso conecta razones y propuesta.' },
    { id: 'pt-24-07', kind: 'open', phase: 'transferir', prompt: 'Escribe una propuesta breve con problema, solución y siguiente paso.', hint: 'Usa O problema..., A proposta... y O próximo passo...', accepted: [], modelAnswer: 'O problema é o atraso. A proposta é mudar o plano. O próximo passo é falar amanhã.', explanation: 'Debe integrar las tres partes del proyecto.' },
    { id: 'pt-24-08', kind: 'choice', phase: 'transferir', prompt: '¿Qué cierre profesional es adecuado?', hint: 'Agradece la atención.', options: ['Obrigado pela atenção.', 'Tchau, qualquer coisa.', 'Acabou palavra.'], answer: 'Obrigado pela atenção.', explanation: 'Es un cierre profesional claro.' },
  ], 'Este proyecto consolida B1 inicial; no sustituye una evaluación externa de certificación.'),
  'pt-25': lesson('pt-25', 'Argumentación formal', 'B2.1', 'Puedo defender una posición con razones, ejemplos y matices.', 'Practicarás escritura formal y contraargumentos.', [
    { title: 'Estructura', explanation: 'Uma posição clara se apoia em razões e exemplos.', examples: ['Defendo que...', 'Além disso...'] },
    { title: 'Contraste', explanation: 'No entanto y apesar de introducen oposición o concesión.', examples: ['No entanto, é caro.', 'Apesar de difícil, é útil.'] },
  ], [
    { id: 'pt-25-01', kind: 'choice', phase: 'activar', prompt: '¿Qué introduce una posición?', hint: 'Defiendo que.', options: ['Defendo que...', 'Acabei que...', 'Tenho de que...'], answer: 'Defendo que...', explanation: 'Defendo que presenta una postura.' },
    { id: 'pt-25-02', kind: 'choice', phase: 'comprender', prompt: 'Completa: “___, a proposta é viável.”', hint: 'Conector de contraste.', options: ['No entanto', 'Por exemplo', 'Finalmente'], answer: 'No entanto', explanation: 'No entanto contrasta con la idea anterior.' },
    { id: 'pt-25-03', kind: 'order', phase: 'practicar', prompt: 'Ordena el argumento.', hint: 'Posición + razón.', tokens: ['eficiente.', 'Defendo', 'que', 'é'], answer: ['Defendo', 'que', 'é', 'eficiente.'], explanation: 'La estructura presenta una posición.' },
    { id: 'pt-25-04', kind: 'choice', phase: 'practicar', prompt: '¿Qué significa apesar de?', hint: 'Concesión.', options: ['a pesar de', 'por causa de', 'antes de'], answer: 'a pesar de', explanation: 'Apesar de introduce una concesión.' },
    { id: 'pt-25-05', kind: 'choice', phase: 'practicar', prompt: '¿Qué añade una razón?', hint: 'Además.', options: ['Além disso', 'Embora', 'Ou seja'], answer: 'Além disso', explanation: 'Além disso añade información.' },
    { id: 'pt-25-06', kind: 'order', phase: 'transferir', prompt: 'Ordena un contraargumento.', hint: 'Concesión y posición.', tokens: ['mas', 'é', 'útil.', 'Apesar', 'de', 'caro,'], answer: ['Apesar', 'de', 'caro,', 'é', 'útil.'], explanation: 'La concesión matiza el argumento.' },
    { id: 'pt-25-07', kind: 'open', phase: 'transferir', prompt: 'Escribe una opinión formal con una razón y un matiz.', hint: 'Usa Defendo que... no entanto...', accepted: [], modelAnswer: 'Defendo que a proposta é útil; no entanto, é cara.', explanation: 'Debe incluir posición, razón o evaluación y contraste.' },
    { id: 'pt-25-08', kind: 'choice', phase: 'transferir', prompt: '¿Qué cierre resume el argumento?', hint: 'En conclusión.', options: ['Em conclusão, recomendo a proposta.', 'Olá, proposta.', 'Talvez início.'], answer: 'Em conclusão, recomendo a proposta.', explanation: 'El cierre sintetiza la posición.' },
  ], 'En B2 importa sostener una posición y reconocer límites, no solo usar conectores.'),
  'pt-26': lesson('pt-26', 'Mediación y síntesis', 'B2.1', 'Puedo resumir información y explicarla a otra persona con claridad.', 'Transformarás información extensa en una explicación útil.', [
    { title: 'Resumir', explanation: 'Em resumo y segundo o relatório introducen síntesis y fuente.', examples: ['Em resumo, há três opções.', 'Segundo o relatório...'] },
    { title: 'Reformular', explanation: 'Ou seja y isto significa hacen la información más accesible.', examples: ['Ou seja, precisamos de tempo.'] },
  ], [
    { id: 'pt-26-01', kind: 'choice', phase: 'activar', prompt: '¿Qué introduce un resumen?', hint: 'En resumen.', options: ['Em resumo', 'Em detalhe', 'Em contrário'], answer: 'Em resumo', explanation: 'Em resumo señala síntesis.' },
    { id: 'pt-26-02', kind: 'choice', phase: 'comprender', prompt: 'Completa: “___ o relatório, os custos aumentaram.”', hint: 'Según.', options: ['Segundo', 'Durante', 'Apesar'], answer: 'Segundo', explanation: 'Segundo introduce la fuente.' },
    { id: 'pt-26-03', kind: 'order', phase: 'practicar', prompt: 'Ordena la reformulación.', hint: 'Ou seja + explicación.', tokens: ['tempo.', 'Ou seja,', 'precisamos', 'de'], answer: ['Ou seja,', 'precisamos', 'de', 'tempo.'], explanation: 'Ou seja reformula la información.' },
    { id: 'pt-26-04', kind: 'choice', phase: 'practicar', prompt: '¿Qué significa fonte?', hint: 'Origen de la información.', options: ['fuente', 'forma', 'fase'], answer: 'fuente', explanation: 'Fonte es fuente.' },
    { id: 'pt-26-05', kind: 'choice', phase: 'practicar', prompt: '¿Qué evita una buena mediación?', hint: 'Claridad para la audiencia.', options: ['copiar sin explicar', 'adaptar el vocabulario', 'organizar ideas'], answer: 'copiar sin explicar', explanation: 'La mediación adapta y explica, no copia.' },
    { id: 'pt-26-06', kind: 'order', phase: 'transferir', prompt: 'Ordena una síntesis.', hint: 'Fuente, idea principal y consecuencia.', tokens: ['aumentaram.', 'Segundo o relatório,', 'os custos'], answer: ['Segundo o relatório,', 'os custos', 'aumentaram.'], explanation: 'La síntesis mantiene fuente y dato.' },
    { id: 'pt-26-07', kind: 'open', phase: 'transferir', prompt: 'Explica una información técnica en una frase sencilla.', hint: 'Usa Ou seja...', accepted: [], modelAnswer: 'Ou seja, precisamos de mais tempo para terminar.', explanation: 'Debe reformular con claridad para otra persona.' },
    { id: 'pt-26-08', kind: 'choice', phase: 'transferir', prompt: '¿Qué frase señala una conclusión?', hint: 'Por lo tanto.', options: ['Assim, podemos decidir.', 'Talvez começar.', 'Onde está a fonte?'], answer: 'Assim, podemos decidir.', explanation: 'Assim conecta la información con una conclusión.' },
  ], 'La mediación se evalúa por la utilidad para quien escucha, no por repetir todo el texto original.'),
  'pt-27': lesson('pt-27', 'Negociación profesional', 'B2.2', 'Puedo negociar condiciones, prioridades y compromisos.', 'Practicarás concesiones, propuestas y acuerdos profesionales.', [
    { title: 'Condiciones', explanation: 'Se pudéssemos y seria possível suavizan una petición.', examples: ['Se pudéssemos alterar o prazo...', 'Seria possível rever o preço?'] },
    { title: 'Acuerdo', explanation: 'Podemos concordar y fica combinado cierran una negociación.', examples: ['Podemos concordar nisso.', 'Fica combinado.'] },
  ], [
    { id: 'pt-27-01', kind: 'choice', phase: 'activar', prompt: '¿Qué petición es más diplomática?', hint: 'Condicional.', options: ['Seria possível alterar o prazo?', 'Altere o prazo!', 'Altera já.'], answer: 'Seria possível alterar o prazo?', explanation: 'Seria possível suaviza la petición.' },
    { id: 'pt-27-02', kind: 'choice', phase: 'comprender', prompt: 'Completa: “Se ___, poderíamos começar amanhã.”', hint: 'Poder en imperfecto de subjuntivo.', options: ['pudéssemos', 'podemos', 'poderemos'], answer: 'pudéssemos', explanation: 'Se pudéssemos plantea una condición hipotética.' },
    { id: 'pt-27-03', kind: 'order', phase: 'practicar', prompt: 'Ordena la propuesta.', hint: 'Podríamos + revisar + contrato.', tokens: ['o contrato.', 'Poderíamos', 'rever'], answer: ['Poderíamos', 'rever', 'o contrato.'], explanation: 'Poderíamos presenta una opción negociable.' },
    { id: 'pt-27-04', kind: 'choice', phase: 'practicar', prompt: '¿Qué significa prazo?', hint: 'Condición temporal.', options: ['plazo', 'plano', 'plaza'], answer: 'plazo', explanation: 'Prazo es el tiempo acordado.' },
    { id: 'pt-27-05', kind: 'choice', phase: 'practicar', prompt: '¿Qué respuesta concede parcialmente?', hint: 'Acepta con condición.', options: ['Aceito, desde que ajustemos o preço.', 'Aceito tudo sem pensar.', 'Não há conversa.'], answer: 'Aceito, desde que ajustemos o preço.', explanation: 'Desde que introduce una condición.' },
    { id: 'pt-27-06', kind: 'order', phase: 'transferir', prompt: 'Ordena el cierre del acuerdo.', hint: 'Entonces queda combinado.', tokens: ['combinado.', 'Então', 'fica'], answer: ['Então', 'fica', 'combinado.'], explanation: 'Confirma el compromiso final.' },
    { id: 'pt-27-07', kind: 'open', phase: 'transferir', prompt: 'Escribe una propuesta de negociación con una condición.', hint: 'Usa Seria possível... desde que...', accepted: [], modelAnswer: 'Seria possível mudar a data, desde que todos concordem.', explanation: 'Debe incluir propuesta y condición.' },
    { id: 'pt-27-08', kind: 'choice', phase: 'transferir', prompt: '¿Qué mantiene un tono profesional?', hint: 'Reconoce la preocupación.', options: ['Compreendo a preocupação; vamos procurar uma solução.', 'Isso é absurdo.', 'Faça como digo.'], answer: 'Compreendo a preocupação; vamos procurar uma solução.', explanation: 'Reconoce y abre espacio para solucionar.' },
  ], 'La negociación B2 combina precisión, cortesía y capacidad de ceder sin perder el objetivo.'),
  'pt-28': lesson('pt-28', 'Presentación de propuestas', 'B2.2', 'Puedo presentar una propuesta compleja y responder preguntas.', 'Integrarás estructura, datos, objeciones y cierre profesional.', [
    { title: 'Presentar', explanation: 'Primero, de seguida y por fim guían una presentación.', examples: ['Primeiro, explico o problema.', 'Por fim, apresento a solução.'] },
    { title: 'Responder', explanation: 'É uma boa questão y com base nos dados permiten responder con calma.', examples: ['É uma boa questão.', 'Com base nos dados...'] },
  ], [
    { id: 'pt-28-01', kind: 'choice', phase: 'activar', prompt: '¿Qué introduce la primera parte?', hint: 'Primero.', options: ['Primeiro', 'Por fim', 'Em conclusão'], answer: 'Primeiro', explanation: 'Primeiro inicia la estructura.' },
    { id: 'pt-28-02', kind: 'choice', phase: 'comprender', prompt: 'Completa: “___, apresento os resultados.”', hint: 'Finalmente.', options: ['Por fim', 'Antes de', 'Apesar de'], answer: 'Por fim', explanation: 'Por fim introduce la última parte.' },
    { id: 'pt-28-03', kind: 'order', phase: 'practicar', prompt: 'Ordena el inicio de una presentación.', hint: 'Problema, contexto y propuesta.', tokens: ['o problema.', 'Primeiro,', 'explico', 'Depois,', 'apresento', 'a solução.'], answer: ['Primeiro,', 'explico', 'o problema.', 'Depois,', 'apresento', 'a solução.'], explanation: 'La estructura guía a la audiencia.' },
    { id: 'pt-28-04', kind: 'choice', phase: 'practicar', prompt: '¿Qué frase gana tiempo para responder?', hint: 'Respuesta profesional.', options: ['É uma boa questão.', 'Não sei nada.', 'Não pergunte.'], answer: 'É uma boa questão.', explanation: 'Reconoce la pregunta y permite responder.' },
    { id: 'pt-28-05', kind: 'choice', phase: 'practicar', prompt: '¿Qué introduce evidencia?', hint: 'Basado en datos.', options: ['Com base nos dados', 'Sem qualquer razão', 'Talvez ontem'], answer: 'Com base nos dados', explanation: 'Introduce la base de la afirmación.' },
    { id: 'pt-28-06', kind: 'order', phase: 'transferir', prompt: 'Ordena el cierre.', hint: 'Resumen y próximos pasos.', tokens: ['passos.', 'Em conclusão,', 'esta proposta', 'define', 'os próximos'], answer: ['Em conclusão,', 'esta proposta', 'define', 'os próximos', 'passos.'], explanation: 'El cierre resume y orienta la acción.' },
    { id: 'pt-28-07', kind: 'open', phase: 'transferir', prompt: 'Escribe el esquema de una propuesta en tres frases.', hint: 'Problema, solución y próximos pasos.', accepted: [], modelAnswer: 'O problema é o atraso. A solução é reorganizar a equipa. Por fim, definimos os próximos passos.', explanation: 'Debe presentar problema, solución y acción siguiente.' },
    { id: 'pt-28-08', kind: 'choice', phase: 'transferir', prompt: '¿Cuál responde a una objeción?', hint: 'Reconoce y fundamenta.', options: ['Compreendo; com base nos dados, a opção é viável.', 'Não concordo porque sim.', 'A pergunta acabou.'], answer: 'Compreendo; com base nos dados, a opção é viável.', explanation: 'Reconoce la objeción y aporta fundamento.' },
  ], 'La presentación B2 debe ser clara, estructurada y capaz de responder preguntas, no solo memorizar frases.'),
  'pt-29': lesson('pt-29', 'Precisión y registro', 'B2.2', 'Puedo adaptar tono, precisión y cortesía a distintas situaciones.', 'Revisarás cómo cambia un mensaje al pasar de informal a formal.', [
    { title: 'Modalizar', explanation: 'Talvez, poderia y parece-me suavizan afirmaciones o peticiones.', examples: ['Poderia enviar o ficheiro?', 'Parece-me uma boa opção.'] },
    { title: 'Editar', explanation: 'La revisión busca claridad, concordancia y registro adecuado.', examples: ['Informal: Oi!', 'Formal: Bom dia, Senhor Silva.'] },
  ], [
    { id: 'pt-29-01', kind: 'choice', phase: 'activar', prompt: '¿Qué petición es más cortés?', hint: 'Modalizador formal.', options: ['Poderia enviar o ficheiro?', 'Envia o ficheiro!', 'Manda já!'], answer: 'Poderia enviar o ficheiro?', explanation: 'Poderia suaviza la petición.' },
    { id: 'pt-29-02', kind: 'choice', phase: 'comprender', prompt: 'Completa: “___ uma boa opção.”', hint: 'Opinión matizada.', options: ['Parece-me', 'Sou-me', 'Tenho-me'], answer: 'Parece-me', explanation: 'Parece-me expresa una impresión.' },
    { id: 'pt-29-03', kind: 'order', phase: 'practicar', prompt: 'Ordena un saludo formal.', hint: 'Saludo + tratamiento.', tokens: ['Senhora', 'Bom dia,', 'Doutora.'], answer: ['Bom dia,', 'Senhora', 'Doutora.'], explanation: 'El saludo debe adaptarse al destinatario.' },
    { id: 'pt-29-04', kind: 'choice', phase: 'practicar', prompt: '¿Qué cierre es profesional?', hint: 'Correo formal.', options: ['Com os melhores cumprimentos,', 'Beijos!', 'Até já, colega!'], answer: 'Com os melhores cumprimentos,', explanation: 'Es un cierre formal.' },
    { id: 'pt-29-05', kind: 'choice', phase: 'practicar', prompt: '¿Qué revisas primero?', hint: 'Mensaje eficaz.', options: ['propósito y destinatario', 'solo la longitud', 'solo las comas'], answer: 'propósito y destinatario', explanation: 'Registro depende del propósito y destinatario.' },
    { id: 'pt-29-06', kind: 'order', phase: 'transferir', prompt: 'Ordena una petición formal.', hint: 'Saludo, petición y cierre.', tokens: ['atenção.', 'Bom dia,', 'Poderia', 'confirmar', 'a reunião?', 'Obrigado pela'], answer: ['Bom dia,', 'Poderia', 'confirmar', 'a reunião?', 'Obrigado pela', 'atenção.'], explanation: 'La secuencia forma un mensaje coherente.' },
    { id: 'pt-29-07', kind: 'open', phase: 'transferir', prompt: 'Reescribe una petición informal en registro formal.', hint: 'Usa Poderia... y un cierre.', accepted: [], modelAnswer: 'Poderia enviar o documento, por favor? Agradeço a atenção.', explanation: 'Debe adaptar tono y cortesía.' },
    { id: 'pt-29-08', kind: 'choice', phase: 'transferir', prompt: '¿Qué modalizador expresa cautela?', hint: 'No afirma de forma absoluta.', options: ['Parece-me que...', 'É sempre...', 'Sem dúvida nenhuma...'], answer: 'Parece-me que...', explanation: 'Parece-me que presenta una valoración cautelosa.' },
  ], 'La precisión B2 incluye elegir el grado de certeza y cortesía, no solo evitar errores gramaticales.'),
  'pt-30': lesson('pt-30', 'Informes y datos', 'B2.2', 'Puedo describir tendencias y extraer conclusiones de información.', 'Interpretarás cambios en datos y los presentarás de forma comprensible.', [
    { title: 'Tendencias', explanation: 'Aumentar, diminuir, manter-se y crescer describen cambios.', examples: ['Os preços aumentaram.', 'A procura diminuiu.'] },
    { title: 'Conclusiones', explanation: 'Os dados mostram y isto sugere conectan evidencia y conclusión.', examples: ['Os dados mostram uma tendência.', 'Isto sugere uma mudança.'] },
  ], [
    { id: 'pt-30-01', kind: 'choice', phase: 'activar', prompt: '¿Qué verbo indica subida?', hint: 'Tendencia ascendente.', options: ['aumentou', 'diminuiu', 'manteve-se'], answer: 'aumentou', explanation: 'Aumentou indica crecimiento.' },
    { id: 'pt-30-02', kind: 'choice', phase: 'comprender', prompt: 'Completa: “A procura ___ 10%.”', hint: 'Bajó.', options: ['diminuiu', 'cresceu', 'ficou'], answer: 'diminuiu', explanation: 'Diminuiu indica reducción.' },
    { id: 'pt-30-03', kind: 'order', phase: 'practicar', prompt: 'Ordena la descripción.', hint: 'Datos + tendencia.', tokens: ['aumentou.', 'A procura', 'no último ano'], answer: ['A procura', 'aumentou', 'no último ano.'], explanation: 'La frase sitúa el cambio en el tiempo.' },
    { id: 'pt-30-04', kind: 'choice', phase: 'practicar', prompt: '¿Qué significa manter-se estável?', hint: 'Sin cambio.', options: ['mantenerse estable', 'subir rápidamente', 'desaparecer'], answer: 'mantenerse estable', explanation: 'No hay variación importante.' },
    { id: 'pt-30-05', kind: 'choice', phase: 'practicar', prompt: '¿Qué introduce una conclusión?', hint: 'Los datos sugieren.', options: ['Isto sugere que...', 'Isto pergunta que...', 'Isto começa que...'], answer: 'Isto sugere que...', explanation: 'Sugere conecta evidencia con inferencia.' },
    { id: 'pt-30-06', kind: 'order', phase: 'transferir', prompt: 'Ordena una conclusión de datos.', hint: 'Evidencia y consecuencia.', tokens: ['uma tendência.', 'Os dados', 'mostram'], answer: ['Os dados', 'mostram', 'uma tendência.'], explanation: 'Presenta una interpretación prudente.' },
    { id: 'pt-30-07', kind: 'open', phase: 'transferir', prompt: 'Describe una tendencia y una posible conclusión.', hint: 'Usa aumentou/diminuiu e Isto sugere...', accepted: [], modelAnswer: 'A procura aumentou; isto sugere que o serviço é útil.', explanation: 'Debe describir cambio y extraer una conclusión.' },
    { id: 'pt-30-08', kind: 'choice', phase: 'transferir', prompt: '¿Qué evita exagerar una conclusión?', hint: 'Lenguaje prudente.', options: ['parece indicar', 'demuestra siempre', 'sin ninguna duda'], answer: 'parece indicar', explanation: 'Parece indicar mantiene cautela con los datos.' },
  ], 'Describe primero el dato observable y después separa claramente tu interpretación.'),
  'pt-31': lesson('pt-31', 'Debate y mediación avanzada', 'B2 consolidación', 'Puedo debatir una cuestión compleja y reformular posiciones.', 'Practicarás turnos, concesiones y síntesis de posiciones opuestas.', [
    { title: 'Conceder', explanation: 'É verdade que y embora reconocen un punto antes de matizar.', examples: ['É verdade que é caro, mas é eficaz.', 'Embora difícil, é possível.'] },
    { title: 'Reformular', explanation: 'Ou seja y em outras palavras aclaran la posición de otra persona.', examples: ['Em outras palavras, quer mais tempo.'] },
  ], [
    { id: 'pt-31-01', kind: 'choice', phase: 'activar', prompt: '¿Qué reconoce un argumento contrario?', hint: 'Concesión.', options: ['É verdade que...', 'Nunca...', 'Não importa...'], answer: 'É verdade que...', explanation: 'Reconoce el punto antes de responder.' },
    { id: 'pt-31-02', kind: 'choice', phase: 'comprender', prompt: 'Completa: “___ difícil, é possível.”', hint: 'Aunque.', options: ['Embora', 'Porque', 'Por isso'], answer: 'Embora', explanation: 'Embora introduce concesión.' },
    { id: 'pt-31-03', kind: 'order', phase: 'practicar', prompt: 'Ordena la concesión.', hint: 'Reconoce y contrasta.', tokens: ['eficaz.', 'É verdade que', 'é caro,', 'mas'], answer: ['É verdade que', 'é caro,', 'mas', 'eficaz.'], explanation: 'La estructura equilibra dos puntos.' },
    { id: 'pt-31-04', kind: 'choice', phase: 'practicar', prompt: '¿Qué significa em outras palavras?', hint: 'Reformular.', options: ['en otras palabras', 'en otro momento', 'en otra ciudad'], answer: 'en otras palabras', explanation: 'Introduce una reformulación.' },
    { id: 'pt-31-05', kind: 'choice', phase: 'practicar', prompt: '¿Qué respuesta mantiene el turno?', hint: 'Debate respetuoso.', options: ['Posso acrescentar um ponto?', 'Cale-se.', 'Já falei tudo.'], answer: 'Posso acrescentar um ponto?', explanation: 'Pide la palabra de forma cortés.' },
    { id: 'pt-31-06', kind: 'order', phase: 'transferir', prompt: 'Ordena una síntesis.', hint: 'Ambas posiciones y conclusión.', tokens: ['posições.', 'As duas', 'são válidas', 'em parte'], answer: ['As duas', 'posições', 'são válidas', 'em parte.'], explanation: 'La síntesis reconoce matices.' },
    { id: 'pt-31-07', kind: 'open', phase: 'transferir', prompt: 'Resume dos posiciones y ofrece una conclusión.', hint: 'Usa É verdade que..., mas... y em conclusão.', accepted: [], modelAnswer: 'É verdade que custa mais, mas é eficaz; em conclusão, vale a pena.', explanation: 'Debe incluir concesión y síntesis.' },
    { id: 'pt-31-08', kind: 'choice', phase: 'transferir', prompt: '¿Qué frase reformula sin deformar?', hint: 'Según lo que entiendo...', options: ['Se entendi bem, a proposta prioriza a segurança.', 'Você disse algo errado.', 'Não vou repetir.'], answer: 'Se entendi bem, a proposta prioriza a segurança.', explanation: 'Comprueba comprensión y reformula.' },
  ], 'La mediación avanzada conserva la intención de la otra persona y la hace accesible.'),
  'pt-32': lesson('pt-32', 'Proyecto final B2', 'B2 consolidación', 'Puedo investigar, presentar y defender una propuesta detallada.', 'Integrarás fuentes, datos, argumentos, registro y defensa oral.', [
    { title: 'Proyecto', explanation: 'Una propuesta B2 necesita problema, evidencia, alternativas y decisión.', examples: ['Com base nos dados...', 'A alternativa recomendada é...'] },
    { title: 'Defensa', explanation: 'Responde objeciones, reconoce límites y justifica prioridades.', examples: ['É uma preocupação válida.', 'A prioridade é...'] },
  ], [
    { id: 'pt-32-01', kind: 'choice', phase: 'activar', prompt: '¿Qué respalda una propuesta?', hint: 'Evidencia.', options: ['dados e fontes', 'solo opinión', 'una frase aislada'], answer: 'dados e fontes', explanation: 'Datos y fuentes aumentan credibilidad.' },
    { id: 'pt-32-02', kind: 'choice', phase: 'comprender', prompt: 'Completa: “Com base ___ dados...”', hint: 'En + os.', options: ['nos', 'nas', 'no'], answer: 'nos', explanation: 'Nos es em + os.' },
    { id: 'pt-32-03', kind: 'order', phase: 'practicar', prompt: 'Ordena la recomendación.', hint: 'Sujeto, adjetivo y decisión.', tokens: ['esta.', 'A', 'alternativa', 'recomendada', 'é'], answer: ['A', 'alternativa', 'recomendada', 'é', 'esta.'], explanation: 'La propuesta debe conectar evidencia y decisión.' },
    { id: 'pt-32-04', kind: 'choice', phase: 'practicar', prompt: '¿Qué reconoce una objeción?', hint: 'Respuesta diplomática.', options: ['É uma preocupação válida.', 'Isso não interessa.', 'Não há problema.'], answer: 'É uma preocupação válida.', explanation: 'Reconoce la objeción antes de responder.' },
    { id: 'pt-32-05', kind: 'choice', phase: 'practicar', prompt: '¿Qué expresa prioridad?', hint: 'Lo más importante.', options: ['A prioridade é...', 'A possibilidade foi...', 'A dúvida será...'], answer: 'A prioridade é...', explanation: 'Presenta la prioridad del proyecto.' },
    { id: 'pt-32-06', kind: 'order', phase: 'transferir', prompt: 'Ordena el cierre.', hint: 'Recomendación y próximos pasos.', tokens: ['próximos passos.', 'Recomendo', 'esta opção', 'e'], answer: ['Recomendo', 'esta opção', 'e', 'os próximos passos.'], explanation: 'Cierra con decisión y acción.' },
    { id: 'pt-32-07', kind: 'open', phase: 'transferir', prompt: 'Presenta una propuesta B2 en tres frases y responde una posible objeción.', hint: 'Incluye datos, recomendación y una concesión.', accepted: [], modelAnswer: 'Com base nos dados, recomendo esta opção. É mais eficiente. É uma preocupação válida, mas podemos controlar o custo.', explanation: 'Debe integrar evidencia, decisión y respuesta a objeción.' },
    { id: 'pt-32-08', kind: 'choice', phase: 'transferir', prompt: '¿Qué demuestra una buena defensa?', hint: 'Respuesta fundamentada.', options: ['responde y justifica', 'repite la conclusión', 'evita preguntas'], answer: 'responde y justifica', explanation: 'Defender una propuesta implica responder y justificar.' },
  ], 'Este proyecto cierra el recorrido B2 del curso, pero no equivale a una certificación oficial.'),
};
