export type RussianDiagnosticCheck = [
  prompt: string,
  answer: string,
  wrongOne: string,
  wrongTwo: string,
  explanation: string,
];

export const russianDiagnosticChecks: Record<
  string,
  [RussianDiagnosticCheck, RussianDiagnosticCheck, RussianDiagnosticCheck]
> = {
  'ru-13': [
    [
      'Completa: Здесь нет ___.',
      'аптеки',
      'аптека',
      'аптекой',
      'нет exige genitivo: аптеки.',
    ],
    [
      'Completa: Это ___ район.',
      'тихий',
      'тихая',
      'тихое',
      'район es masculino y exige тихий.',
    ],
    [
      'Completa: Магазин рядом с ___.',
      'домом',
      'дом',
      'дома',
      'рядом с exige instrumental: домом.',
    ],
  ],
  'ru-14': [
    [
      'Vas ahora a pie. Completa: Я ___ в магазин.',
      'иду',
      'еду',
      'хожу',
      'иду expresa un desplazamiento a pie en curso.',
    ],
    [
      'Vas ahora en autobús. Completa: Я ___ на автобусе.',
      'еду',
      'иду',
      'езжу',
      'еду expresa un trayecto actual en vehículo.',
    ],
    [
      'Da una indicación cortés a una persona.',
      'Идите прямо.',
      'Идёшь прямо.',
      'Идти прямо.',
      'Идите es el imperativo cortés o plural.',
    ],
  ],
  'ru-15': [
    [
      'Ana trabajó en casa. Completa: Анна ___ дома.',
      'работала',
      'работал',
      'работали',
      'El pasado femenino termina en -ла.',
    ],
    [
      'Enfatiza dos horas de actividad.',
      'Вчера я читал два часа.',
      'Вчера я прочитал два часа.',
      'Вчера я читать два часа.',
      'El imperfectivo читал presenta duración.',
    ],
    [
      'Enfatiza que terminaste el libro.',
      'Я прочитал книгу.',
      'Я читал книгу два часа.',
      'Я прочитать книгу.',
      'El perfectivo прочитал presenta resultado.',
    ],
  ],
  'ru-16': [
    [
      'Completa: Завтра я ___ работать.',
      'буду',
      'был',
      'есть',
      'буду + infinitivo forma el futuro imperfectivo.',
    ],
    [
      'Expresa una intención.',
      'Я собираюсь учиться.',
      'Я собираю учиться.',
      'Я учился завтра.',
      'собираться + infinitivo expresa intención.',
    ],
    [
      'Propón una reunión a varias personas.',
      'Давайте встретимся в пять.',
      'Давай встретился в пять.',
      'Встречались в пять завтра.',
      'Давайте + perfectivo propone una acción conjunta.',
    ],
  ],
  'ru-17': [
    [
      'Expresa que te encuentras mal.',
      'Мне плохо.',
      'Я плохо есть.',
      'Меня плохой.',
      'El estado impersonal usa dativo: мне.',
    ],
    [
      'Da el consejo “debe descansar”.',
      'Вам нужно отдыхать.',
      'Вы нужно отдыхаете.',
      'Вам отдыхал нужно.',
      'нужно se combina con infinitivo.',
    ],
    [
      'Indica que fumar está prohibido.',
      'Нельзя курить.',
      'Не можно куришь.',
      'Нельзя курит.',
      'нельзя requiere infinitivo.',
    ],
  ],
  'ru-18': [
    [
      'Expresa una habilidad aprendida.',
      'Я умею плавать.',
      'Я могу плавал.',
      'Я умею плыву.',
      'уметь se combina con infinitivo.',
    ],
    [
      'Expresa posibilidad de venir mañana.',
      'Я могу прийти завтра.',
      'Я умею прийти завтра.',
      'Я могу пришёл завтра.',
      'мочь + infinitivo expresa posibilidad.',
    ],
    [
      'Completa: Я интересуюсь ___.',
      'музыкой',
      'музыка',
      'музыку',
      'интересоваться exige instrumental.',
    ],
  ],
  'ru-19': [
    [
      'Pide ayuda cortésmente.',
      'Помогите, пожалуйста.',
      'Помогаете, пожалуйста.',
      'Помочь ты.',
      'Помогите es imperativo cortés/plural.',
    ],
    [
      'Pregunta qué significa algo.',
      'Что это значит?',
      'Что это значение?',
      'Как это значишь?',
      'Что это значит? es la fórmula idiomática.',
    ],
    [
      'Completa: У меня нет ___.',
      'билета',
      'билет',
      'билетом',
      'нет exige genitivo.',
    ],
  ],
  'ru-20': [
    [
      'Pregunta cómo llegar en transporte.',
      'Как доехать до вокзала?',
      'Как идти вокзал?',
      'Где доехать вокзалом?',
      'доехать до exige genitivo.',
    ],
    [
      'Contrasta llegada pasada y salida futura.',
      'Вчера я приехал, а завтра уеду.',
      'Вчера я приеду, а завтра уехал.',
      'Вчера я приехать, завтра уезжал.',
      'Los tiempos y prefijos corresponden a cada momento.',
    ],
    [
      'Pide que hablen más despacio.',
      'Говорите медленнее, пожалуйста.',
      'Говорите медленный.',
      'Скажите медленнее вчера.',
      'El comparativo adverbial медленнее modifica говорите.',
    ],
  ],
  'ru-21': [
    [
      'Crea el fondo de una narración.',
      'Когда я шёл домой, шёл дождь.',
      'Когда я пришёл домой, шёл дождь.',
      'Когда я идти домой, дождь.',
      'El imperfectivo шёл presenta una acción en curso.',
    ],
    [
      'Presenta un encuentro completado.',
      'Я встретил старого друга.',
      'Я встречал старого друга два часа.',
      'Я встречу друга вчера.',
      'встретил presenta el evento como completo.',
    ],
    [
      'Marca llegada y salida.',
      'Поезд приехал и уехал.',
      'Поезд ходил и ехал.',
      'Поезд пришёл и ушёл пешком.',
      'при-/у- con ехать expresan llegada y salida del vehículo.',
    ],
  ],
  'ru-22': [
    [
      'Completa: Я отвечаю ___ отчёты.',
      'за',
      'на',
      'о',
      'отвечать за rige acusativo.',
    ],
    [
      'Expresa estudios terminados.',
      'Я окончил университет.',
      'Я учился университет.',
      'Я окончить университет.',
      'окончить + acusativo presenta finalización.',
    ],
    [
      'Completa: Я планирую ___ в этой области.',
      'развиваться',
      'развиваюсь',
      'развивался',
      'планировать se combina con infinitivo.',
    ],
  ],
  'ru-23': [
    [
      'Introduce una postura personal.',
      'Я считаю, что это полезно.',
      'Я считаю это полезный.',
      'Мне считаю полезно.',
      'считать, что introduce una proposición.',
    ],
    [
      'Introduce la razón, no el resultado.',
      'потому что',
      'поэтому',
      'несмотря на',
      'потому что introduce causa.',
    ],
    [
      'Introduce una consecuencia.',
      'поэтому',
      'потому что',
      'хотя',
      'поэтому introduce resultado.',
    ],
  ],
  'ru-24': [
    [
      'Elige un titular natural.',
      'В городе открыли новую школу',
      'В городе открыла новая школу',
      'Город открыл новую школой',
      'La construcción impersonal plural centra el acontecimiento.',
    ],
    [
      'Atribuye información al alcalde.',
      'По словам мэра, проект завершён.',
      'По словам мэр, проект завершил.',
      'Мэр словами проект.',
      'по словам exige genitivo.',
    ],
    [
      'Describe un proceso en curso sin agente.',
      'Мост строится с прошлого года.',
      'Мост строит с прошлого года.',
      'Мост построился кем-то сейчас.',
      'строится funciona como pasiva refleja.',
    ],
  ],
  'ru-25': [
    [
      'Expresa una condición real.',
      'Если будет дождь, мы останемся дома.',
      'Если был бы дождь, мы останемся вчера.',
      'Если дождь, мы оставались завтра.',
      'La condición real combina если con futuro.',
    ],
    [
      'Expresa una elección hipotética.',
      'Я бы выбрал поезд.',
      'Я буду бы выбрать поезд.',
      'Я выбрал поезд завтра бы есть.',
      'бы + pasado expresa hipótesis.',
    ],
    [
      'Compara velocidad.',
      'Поезд быстрее, чем автобус.',
      'Поезд более быстро автобуса есть.',
      'Поезд быстрый чем автобусом.',
      'El comparativo usa быстрее, чем.',
    ],
  ],
  'ru-26': [
    [
      'Reacciona a una buena noticia.',
      'Поздравляю!',
      'Мне очень жаль.',
      'Не согласен.',
      'Поздравляю felicita.',
    ],
    [
      'Reacciona a una pérdida.',
      'Мне очень жаль.',
      'Поздравляю!',
      'Это замечательно!',
      'Мне жаль expresa empatía.',
    ],
    [
      'Atenúa un desacuerdo.',
      'Я понимаю, но не совсем согласен.',
      'Ты совершенно неправ.',
      'Я не слушаю.',
      'не совсем y el reconocimiento previo suavizan la respuesta.',
    ],
  ],
  'ru-27': [
    [
      'Completa: Это фильм, ___ получил премию.',
      'который',
      'которая',
      'которое',
      'который concuerda con фильм.',
    ],
    [
      'Completa: Сюжет был ___.',
      'убедительным',
      'убедительный',
      'убедительного',
      'El predicativo con был aparece en instrumental.',
    ],
    [
      'Recomienda la película a una persona.',
      'Я советую вам посмотреть фильм.',
      'Я советую вы смотрите фильм.',
      'Я совет фильм вам.',
      'советовать + dativo + infinitivo.',
    ],
  ],
  'ru-28': [
    [
      'Formula una pregunta de investigación.',
      'Как жители добираются до работы?',
      'Жители работа как?',
      'Кто работа добирается где?',
      'La pregunta delimita población y conducta.',
    ],
    [
      'Atribuye el dato a una encuesta.',
      'По данным опроса, половина ездит на автобусе.',
      'Опросом половина автобус.',
      'По данные опрос, половина едет.',
      'по данным exige genitivo.',
    ],
    [
      'Introduce una conclusión.',
      'Таким образом',
      'Например',
      'Во-первых',
      'Таким образом sintetiza una inferencia.',
    ],
  ],
  'ru-29': [
    [
      'Presenta una convicción.',
      'Я убеждён, что изменения необходимы.',
      'Я убеждаю изменения необходимый.',
      'Мне убеждён изменения.',
      'убеждён, что introduce una tesis firme.',
    ],
    [
      'Construye una concesión.',
      'Хотя проект дорогой, он полезен.',
      'Потому что проект дорогой, но.',
      'Хотя проект и поэтому полезен.',
      'Хотя introduce una objeción reconocida.',
    ],
    [
      'Matiza una predicción.',
      'Это, вероятно, улучшит ситуацию.',
      'Это точно всегда решит всё.',
      'Это вероятность улучшал.',
      'вероятно evita certeza excesiva.',
    ],
  ],
  'ru-30': [
    [
      'Elige una nominalización natural.',
      'развитие общественного транспорта',
      'развивать общественный транспортом',
      'развитый транспорта общество',
      'развитие condensa el proceso de desarrollar.',
    ],
    [
      'Retoma una idea anterior.',
      'Этот подход требует инвестиций.',
      'Эта подход требует инвестиции.',
      'Подход этот требуют.',
      'этот подход concuerda y funciona como referencia.',
    ],
    [
      'Introduce una conclusión lógica.',
      'Следовательно, план нужно изменить.',
      'Например, план поэтому.',
      'Следствие план изменяет.',
      'следовательно marca inferencia.',
    ],
  ],
  'ru-31': [
    [
      'Solicita el turno.',
      'Можно я добавлю?',
      'Я добавляю тебя?',
      'Можно добавил?',
      'Можно я…? negocia el turno.',
    ],
    [
      'Recuerda un acuerdo compartido.',
      'Мы же договорились.',
      'Мы договорились ли же?',
      'Нас же договорил.',
      'же enfatiza información compartida.',
    ],
    [
      'Verifica una interpretación.',
      'Если я правильно понял, встреча в шесть.',
      'Если я правильно понимаю вчера.',
      'Правильно встреча понял шесть.',
      'La cláusula condicional comprueba lo entendido.',
    ],
  ],
  'ru-32': [
    [
      'Completa: Согласно ___, спрос растёт.',
      'исследованию',
      'исследование',
      'исследованием',
      'согласно exige dativo.',
    ],
    [
      'Introduce una causa problemática.',
      'Из-за пробок люди опаздывают.',
      'Благодаря пробкам люди опаздывают.',
      'Пробки из-за люди.',
      'из-за presenta aquí una causa negativa.',
    ],
    [
      'Destaca un caso concreto.',
      'В частности, вырос спрос на автобусы.',
      'Следовательно пример автобусы.',
      'Вопреки частности спрос.',
      'в частности especifica un ejemplo relevante.',
    ],
  ],
  'ru-33': [
    [
      'Abre un correo profesional.',
      'Благодарю за ваше письмо.',
      'Спасибо за твоё письмецо.',
      'Эй, письмо получил.',
      'La fórmula mantiene registro formal.',
    ],
    [
      'Introduce una aclaración cortés.',
      'Позвольте уточнить один вопрос.',
      'Объясните нормально.',
      'Я уточнял тебя вопрос.',
      'Позвольте уточнить reduce la imposición.',
    ],
    [
      'Confirma un acuerdo.',
      'Хотел бы подтвердить нашу договорённость.',
      'Хочу сказать договор.',
      'Подтверждаю мы договорились бы.',
      'La colocación confirmar un acuerdo es подтвердить договорённость.',
    ],
  ],
  'ru-34': [
    [
      'Introduce una definición formal.',
      'Под инфляцией понимается рост цен.',
      'Инфляция понимает цены.',
      'Под инфляцию понимают ростом.',
      'под + instrumental enmarca el término definido.',
    ],
    [
      'Introduce una paráfrasis.',
      'Иными словами',
      'Несмотря на',
      'В результате',
      'Иными словами reformula.',
    ],
    [
      'Ordena el primer paso.',
      'Прежде всего нужно собрать данные.',
      'Наконец сначала данные.',
      'Прежде данные собирали всего.',
      'Прежде всего introduce prioridad inicial.',
    ],
  ],
  'ru-35': [
    [
      'Elige el participio pasivo correcto.',
      'документ, подписанный директором',
      'документ, подписавший директора',
      'документ, подписанным директор',
      'подписанный concuerda con документ; el agente va en instrumental.',
    ],
    [
      'Elige el gerundio con sujeto compartido.',
      'Проверив данные, аналитик отправил отчёт.',
      'Проверив данные, отчёт был отправлен.',
      'Проверяя, данные отправили аналитика.',
      'El analista realiza ambas acciones.',
    ],
    [
      'Elige el registro profesional.',
      'Просим вас подтвердить получение.',
      'Подтверди, что получил.',
      'Ну ты получил?',
      'Просим вас… corresponde a registro formal.',
    ],
  ],
  'ru-36': [
    [
      'Formula una propuesta concreta.',
      'Предлагаю запустить пилотный проект.',
      'Я про проект может быть.',
      'Проект предлагал запущенный.',
      'предлагаю + infinitivo recomienda una acción.',
    ],
    [
      'Relaciona evidencia y tendencia.',
      'Данные показывают, что спрос растёт.',
      'Данные показывает спрос растут.',
      'Спрос доказывает все данные.',
      'El plural данные exige показывают.',
    ],
    [
      'Reconoce una dificultad.',
      'Несмотря на затраты, проект оправдан.',
      'Затраты не существуют.',
      'Несмотря затраты проектом.',
      'несмотря на + acusativo introduce concesión.',
    ],
  ],
};

export const russianAcceptedOrderSentences: Record<string, string[]> = {
  'ru-13': ['Рядом с домом магазин.'],
  'ru-15': ['Книгу я прочитал.'],
  'ru-16': ['Я буду работать завтра.'],
  'ru-17': ['Голова у меня болит.'],
  'ru-18': ['Музыкой я интересуюсь.'],
  'ru-19': ['Пожалуйста, помогите.'],
  'ru-20': ['До вокзала как доехать?'],
  'ru-21': ['Когда начался дождь, я шёл домой.'],
  'ru-22': ['Университет я окончил.'],
  'ru-24': ['Новую школу открыли в городе.'],
  'ru-26': ['Я понимаю, но согласен не совсем.'],
  'ru-28': ['Половина пользуется автобусом, по данным опроса.'],
  'ru-31': ['Встреча в шесть, если я правильно понял.'],
  'ru-32': ['Спрос растёт, согласно исследованию.'],
  'ru-33': ['За ваше письмо благодарю.'],
};
